FairRootGroup/FairRoot

example/Tutorial3/macro/startAll.sh.in, example/Tutorial3/macro/startAllGeneric.sh.in, example/Tutorial3/macro/startAllProxy.sh.in, example/Tutorial3/macro/startPushPull.sh.in, example/Tutorial3/macro/startThree.sh.in
=> add mcEngine string to start scripts

base/event/FairLink.h
Small fix of operator< in FairLink. The original one still had problems with -1 values
=> Fix operator< in FairLink

fairmq/CMakeLists.txt, fairmq/examples/1-sampler-sink/FairMQExample1Sampler.cxx, fairmq/examples/1-sampler-sink/FairMQExample1Sampler.h, fairmq/examples/1-sampler-sink/FairMQExample1Sink.cxx, fairmq/examples/1-sampler-sink/FairMQExample1Sink.h, fairmq/examples/1-sampler-sink/runExample1Sampler.cxx, fairmq/examples/1-sampler-sink/runExample1Sink.cxx, fairmq/examples/1-sampler-sink/sampler-sink.json, fairmq/examples/2-sampler-processor-sink/FairMQExample2Processor.cxx, fairmq/examples/2-sampler-processor-sink/FairMQExample2Processor.h, fairmq/examples/2-sampler-processor-sink/FairMQExample2Sampler.cxx, fairmq/examples/2-sampler-processor-sink/FairMQExample2Sampler.h, fairmq/examples/2-sampler-processor-sink/FairMQExample2Sink.cxx, fairmq/examples/2-sampler-processor-sink/FairMQExample2Sink.h, fairmq/examples/2-sampler-processor-sink/runExample2Processor.cxx, fairmq/examples/2-sampler-processor-sink/runExample2Sampler.cxx, fairmq/examples/2-sampler-processor-sink/runExample2Sink.cxx, fairmq/examples/2-sampler-processor-sink/sampler-processor-sink.json, fairmq/options/FairMQProgOptions.cxx, fairmq/options/FairMQProgOptions.h, fairmq/options/ProgOptionTest/macro/ConfigFileTest.cfg.in, fairmq/options/ProgOptionTest/macro/start-bsampler-sink.sh.in, fairmq/options/ProgOptionTest/macro/testMQOptions1.sh.in, fairmq/options/ProgOptionTest/macro/testMQOptions4.sh.in, fairmq/options/ProgOptionTest/run/runOptTestSampler.cxx, fairmq/options/ProgOptionTest/run/runOptTestSink.cxx, fairmq/options/ProgOptionTest/run/testMQoptions1.cxx, fairmq/options/ProgOptionTest/run/testMQoptions2.cxx, fairmq/run/runBenchmarkSampler.cxx
- fairmq/examples/1-sampler-sink (one Sampler, one Sink)
- fairmq/examples/2-sampler-processor-sink (one Sampler, two Processors, one Sink)
=> Add two simple FairMQ examples

base/source/MRevBuffer.cxx, geane/FairGeanePro.cxx, trackbase/FairGeaneUtil.cxx, trackbase/FairTrackParP.cxx
Fix coverity issues 10061, 10107,10168, 10169,10189, 10198
=> Rc v 15.07 fixes 

base/source/FairMbsStreamSource.cxx
Give proper number of double words to Unpack function of FairMbsStreamSource.
=> fixed: number of double words (issue79)

fairmq/CMakeLists.txt, fairmq/FairMQLogger.cxx, fairmq/FairMQLogger.h, fairmq/FairMQTransportFactory.h, fairmq/logger/CMakeLists.txt, fairmq/logger/logger.cxx, fairmq/logger/logger.h, fairmq/logger/logger_def.h, fairmq/logger/run/testLogger.cxx, fairmq/options/FairMQParser.cxx, fairmq/options/FairMQProgOptions.cxx, fairmq/options/FairMQProgOptions.h, fairmq/options/FairProgOptions.cxx, fairmq/options/FairProgOptions.h
- Replace the fairmq logger with one based on Boost.Log
- Adapt FairProgOptions to configure the new logger
=> fairmq logger

example/CMakeLists.txt
Do not build tests that need simulation if in Reco mode
=> Reco only option

fairmq/FairMQChannel.cxx, fairmq/FairMQChannel.h, fairmq/FairMQDevice.cxx, fairmq/FairMQDevice.h, fairmq/FairMQSocket.h, fairmq/nanomsg/FairMQSocketNN.cxx, fairmq/nanomsg/FairMQSocketNN.h, fairmq/test/CMakeLists.txt, fairmq/test/runTransferTimeoutTest.cxx, fairmq/zeromq/FairMQSocketZMQ.cxx, fairmq/zeromq/FairMQSocketZMQ.h
- FairMQ: Add methods for setting timeout on blocking Send/Receive calls (and a test for it).
- FairMQDevice: Extend Doxygen documentation
=> Add methods to set timeout on blocking Send/Receive

base/steer/FairRunAnaProof.cxx, fairmq/FairMQStateMachine.cxx
A few minor issues when building.
=> Fix wrong string comparison

examples/simulation/Tutorial2/macros/create_digis_mixed.C
Use the new source and mixed source  classes directly from macro
=> remove obsolete function

base/steer/FairRunAnaProof.h, examples/advanced/Tutorial3/macro/run_DiReLo.C, examples/advanced/Tutorial3/macro/run_DiRePr.C, examples/advanced/Tutorial3/macro/run_sim_sep.C
Added default values to FairRunAnaProof::Run(Int_t NStart=0 ,Int_t NStop=0)
Plus few bug fixes in the macros of Tutorial3.
=> FairRunAnaProof and Tutorial3 fixes

base/sim/FairBaseParSet.cxx, base/sim/FairBaseParSet.h, base/steer/FairRunSim.cxx, examples/simulation/Tutorial2/macros/read_digis.C, examples/simulation/Tutorial2/macros/run_tutorial2.C, examples/simulation/rutherford/macros/run_rutherford.C, parbase/FairParamList.cxx, parbase/FairParamList.h
Random seed s are stored now in the base parameters. 
Tutorial2 shows how to access it after initialising the run.
=> Issue #147 Store random seeds in the parameters

base/MQ/policies/Serialization/RootSerializer.h, examples/MQ/GenericDevices/CMakeLists.txt, examples/MQ/GenericDevices/data_struct/MyDigi.cxx, examples/MQ/GenericDevices/data_struct/MyDigi.h, examples/MQ/GenericDevices/data_struct/MyHit.cxx, examples/MQ/GenericDevices/data_struct/MyHit.h, examples/MQ/GenericDevices/data_struct/Tuto7Payload.proto, examples/MQ/GenericDevices/devices/policy/serialization/MyDigiSerializer_protobuff.h, examples/MQ/GenericDevices/devices/policy/serialization/MyHitSerializer.h, examples/MQ/GenericDevices/devices/policy/serialization/MyHitSerializer_protobuff.h, examples/MQ/GenericDevices/run/runFileSinkT7.cxx, examples/MQ/GenericDevices/run/runProcessorT7.cxx, examples/MQ/GenericDevices/run/runSamplerT7.cxx, examples/MQ/GenericDevices/run/scripts/startGenericMQTutoAll.sh.in
* extend RootDeserializer policy to any class deriving from TObject.
=> * add Google Protocol Buffer serialization policy in tutorial 7

examples/MQ/9-PixelDetector/src/PixelDigiSource.h, examples/MQ/9-PixelDetector/src/PixelDigiWriteToFile.h
To make root6 compilation process satisfied.
=> Adding std:: to fstream declarations

examples/MQ/9-PixelDetector/src/PixelContFact.cxx, examples/MQ/9-PixelDetector/src/PixelContFact.h, examples/MQ/9-PixelDetector/src/PixelDigi.h, examples/MQ/9-PixelDetector/src/PixelDigiPar.cxx, examples/MQ/9-PixelDetector/src/PixelDigiPar.h, examples/MQ/9-PixelDetector/src/PixelDigiSource.h, examples/MQ/9-PixelDetector/src/PixelGeo.cxx, examples/MQ/9-PixelDetector/src/PixelGeo.h, examples/MQ/9-PixelDetector/src/PixelGeoPar.h, examples/MQ/9-PixelDetector/src/PixelHit.h, examples/MQ/9-PixelDetector/src/PixelTrack.h
=> correct the includes of the new example

base/sim/FairDetector.cxx, base/sim/FairGeaneApplication.cxx, base/sim/FairMCApplication.cxx, base/steer/FairRadGridManager.cxx, base/steer/FairRadLenManager.cxx, base/steer/FairRadMapManager.cxx, examples/MQ/9-PixelDetector/src/Pixel.cxx, examples/advanced/Tutorial3/simulation/FairTestDetector.cxx, examples/common/gconfig/DecayConfig.C, examples/common/gconfig/SetCuts.C, examples/common/gconfig/UserDecay.C, examples/common/gconfig/flConfig.C, examples/simulation/Tutorial1/src/FairTutorialDet1.cxx, examples/simulation/Tutorial2/src/FairTutorialDet2.cxx, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx, examples/simulation/Tutorial4/src/tools/FairTutorialDet4GeoHandler.cxx, examples/simulation/rutherford/src/FairRutherford.cxx, geane/FairGeanePro.cxx
Use the static TVirualMC::GetMC() method instead of the global pointer
=> Remove gMC

MbsAPI/fLmd.c, examples/MQ/9-PixelDetector/src/PixelDigiBinSource.cxx, examples/MQ/9-PixelDetector/src/PixelDigiSource.cxx, examples/MQ/9-PixelDetector/src/PixelDigiWriteToBinFile.cxx, examples/MQ/9-PixelDetector/src/PixelDigiWriteToFile.cxx, generators/FairAsciiGenerator.cxx, generators/FairShieldGenerator.cxx, generators/FairUrqmdGenerator.cxx
Fix Coverity issues 58883, 58903, 76319, 93106, 93108, 93109, 93110, 93111
Fix Coverity issues 58904, 58905, 59225, 59226, 59227
=> Fix Coverity issue.

base/source/rclose.c, base/steer/FairRootManager.cxx, base/steer/FairRunAnaProof.cxx, fairtools/FairSystemInfo.cxx, generators/FairEvtGenGenerator.cxx, geobase/FairGeoMedium.cxx
Fix coverity issues 98827, 59224, 58882, 58913, 10175, 98828, 59223.
=> Fix coverity issues.

examples/MQ/3-dds/ex3-dds-topology.xml, examples/MQ/serialization/test/runFileSinkT7Test.cxx, examples/MQ/serialization/test/runProcessorT7Test.cxx, examples/MQ/serialization/test/runSamplerT7Test.cxx, examples/MQ/serialization/test/startGenEx2TestRoot.sh.in, fairmq/FairMQDevice.cxx, fairmq/logger/logger.cxx, fairmq/logger/logger.h, fairmq/options/FairMQProgOptions.cxx, fairmq/run/runBenchmarkSampler.cxx, fairmq/run/runMerger.cxx, fairmq/run/runProxy.cxx, fairmq/run/runSink.cxx, fairmq/run/runSplitter.cxx, fairmq/run/startFairMQBenchmark.sh.in, fairmq/tools/runSimpleMQStateMachine.h
- Add a cmd option to control state change mechanism
- Fix the logger conflict issue (global filters).
=> Add a cmd option to control state change mechanism and fix logger

CMakeLists.txt, cmake/modules/FindGo.cmake, examples/advanced/GoTutorial/CMakeLists.txt, examples/advanced/GoTutorial/src/go-processor/README.md, examples/advanced/GoTutorial/src/go-sink/README.md
Add the go example done by Sebastien Binet (@sbinet) to the cmake (pull request #313)
=> cmake build the go executables 

examples/MQ/9-PixelDetector/README.md, examples/MQ/9-PixelDetector/run/scripts/controlDDS.sh.in
Added a simple windmill to controlDDS.sh , to indicate that it is running.
=> MQ/Example9 - updated markdown documentation;

base/sim/FairBaseParSet.cxx, base/sim/FairGenericStack.cxx, base/sim/FairMCApplication.cxx
Some variables where allocated and not freed on exit
(reported by Federica Sozzi)
=> clean memory on exit

base/event/FairRunInfo.cxx, base/sim/FairModule.cxx, base/source/FairFileSource.cxx, base/source/FairMixedSource.cxx, base/steer/FairRootManager.cxx, base/steer/FairRunAna.cxx, base/steer/FairRunOnline.cxx, examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSink.h, examples/simulation/Tutorial4/macros/Create_Tutorial4_Geometry.C, examples/simulation/Tutorial4/macros/plots.C, parbase/FairParRootFileIo.cxx, scripts/Read_Memory_File.C
This will allow to use any TFile derived class for which a plugin library handler has been registered with the plugin manager in ROOT
(This was requested by @ThomasRuf)
=> Use TFile::Open instead of new Tfile to handle input files

base/event/FairLink.h, trackbase/FairTrackPar.cxx, trackbase/FairTrackPar.h
Adding boost serialization support for FairTrackPar and FairLink and fixing some inconsistencies of FairTrackPar
=> boost serialization for FairTrackPar and FairLink

base/sim/FairMCApplication.cxx
- Use TVirtualMC::GetMC() instead of fMC.
=> Fix in FairMCApplication::ConstructOpGeometry()

examples/MQ/9-PixelDetector/run/scripts/startFairMQEx9_Static.sh.in, examples/MQ/9a-PixelDetector/run/CMakeLists.txt, examples/MQ/9a-PixelDetector/run/scripts/startFairMQEx9aFromBin_Static.sh.in, examples/MQ/9a-PixelDetector/run/scripts/startFairMQEx9aFromRoot_Static.sh.in
Modified the static scripts to wait for the filesink process to finish.
=> MQ/examples 9 and 9a.

CMakeLists.txt, cmake/modules/FindPythia8.cmake, examples/common/gconfig/DecayConfig.C, examples/common/gconfig/DecayConfigPythia8.C, examples/common/gconfig/g4Config.C, examples/simulation/Tutorial1/macros/CMakeLists.txt, examples/simulation/Tutorial1/macros/run_tutorial1_pythia6.C, examples/simulation/Tutorial1/macros/run_tutorial1_pythia8.C
Use correct function TVirtualMC::GetMC to acces the virtual MC.
Add test for pythia6 external decayer.
=> Fix deacy configuration macro.

LICENSE
See https://www.gnu.org/licenses/gpl-howto.html
=> LGPLv3 requires the GPLv3 text to be shipped too

base/sim/FairGenericStack.cxx, base/sim/FairGenericStack.h
=> Code clean-up in FairGenericStack 

examples/common/mcstack/CMakeLists.txt
=> install all headers

cmake/modules/FindFairRoot.cmake, fairmq/CMakeLists.txt
Some leftovers from the hectic work two days ago. I did my best now to verify AliceO2 is not breaking (I can successfully compile and run the FairMQ related test cases). But please verify again before merging. Thank you
=> CMake cleanup leftovers

.travis.yml, cmake/modules/GTestHelper.cmake, fairmq/FairMQChannel.cxx, fairmq/FairMQChannel.h, fairmq/FairMQDevice.cxx, fairmq/nanomsg/FairMQTransportFactoryNN.h, fairmq/shmem/FairMQTransportFactorySHM.h, fairmq/test/CMakeLists.txt, fairmq/test/helper/devices/TestPub.cxx, fairmq/test/helper/devices/TestSub.cxx, fairmq/test/protocols/_pub_sub.cxx, fairmq/test/protocols/config.json.in, fairmq/zeromq/FairMQTransportFactoryZMQ.h
Two devices can't share device id
=> Fix FairMQ.Protocols tests on OSX

.gitignore, fairmq/test/helper/devices/TestPub.cxx, fairmq/test/helper/devices/TestPull.cxx, fairmq/test/helper/devices/TestPush.cxx, fairmq/test/helper/devices/TestRep.cxx, fairmq/test/helper/devices/TestReq.cxx, fairmq/test/helper/devices/TestSub.cxx, fairmq/test/helper/devices/TestTransferTimeout.cxx, fairmq/test/helper/runTestDevice.cxx, fairmq/test/protocols/_pub_sub.cxx, fairmq/test/protocols/_push_pull.cxx, fairmq/test/protocols/_req_rep.cxx, fairmq/test/protocols/_transfer_timeout.cxx, fairmq/test/protocols/runner.cxx.in, fairmq/test/protocols/runner.h
=> Fix FairMQ travis tests

cmake/modules/Findnanomsg.cmake
=> Look for nanomsg on custom paths then system

fairmq/FairMQParts.h, fairmq/test/CMakeLists.txt, fairmq/test/parts/_iterator_interface.cxx, fairmq/test/parts/runner.cxx
=> expose STL iterator interface for FairMQParts

fairmq/options/FairMQSuboptParser.h
added @rbx and @MohammadAlTurany as reviewers and a label for testing github features
=> add missing include guard

CMakeLists.txt, fairmq/AUTHORS, fairmq/CONTRIBUTORS, fairmq/FairMQChannel.cxx, fairmq/FairMQChannel.h, fairmq/FairMQDevice.cxx, fairmq/FairMQDevice.h, fairmq/FairMQTransportFactory.cxx, fairmq/FairMQTransportFactory.h, fairmq/nanomsg/FairMQTransportFactoryNN.cxx, fairmq/nanomsg/FairMQTransportFactoryNN.h, fairmq/shmem/FairMQSocketSHM.cxx, fairmq/shmem/FairMQTransportFactorySHM.cxx, fairmq/shmem/FairMQTransportFactorySHM.h, fairmq/test/CMakeLists.txt, fairmq/test/parts/_iterator_interface.cxx, fairmq/test/protocols/_push_pull.cxx, fairmq/test/protocols/_push_pull_multipart.cxx, fairmq/zeromq/FairMQSocketZMQ.cxx, fairmq/zeromq/FairMQTransportFactoryZMQ.cxx, fairmq/zeromq/FairMQTransportFactoryZMQ.h
=> Inproc and ipc unit tests

examples/MQ/6-multiple-channels/FairMQExample6Sampler.cxx, fairmq/FairMQDevice.cxx, fairmq/FairMQDevice.h, fairmq/FairMQTransportFactory.h, fairmq/devices/FairMQMerger.cxx, fairmq/nanomsg/FairMQPollerNN.cxx, fairmq/nanomsg/FairMQPollerNN.h, fairmq/nanomsg/FairMQTransportFactoryNN.cxx, fairmq/nanomsg/FairMQTransportFactoryNN.h, fairmq/shmem/FairMQPollerSHM.cxx, fairmq/shmem/FairMQPollerSHM.h, fairmq/shmem/FairMQTransportFactorySHM.cxx, fairmq/shmem/FairMQTransportFactorySHM.h, fairmq/test/CMakeLists.txt, fairmq/test/helper/devices/TestPollIn.cxx, fairmq/test/helper/devices/TestPollOut.cxx, fairmq/test/helper/runTestDevice.cxx, fairmq/test/protocols/_poller.cxx, fairmq/test/protocols/config.json.in, fairmq/zeromq/FairMQPollerZMQ.cxx, fairmq/zeromq/FairMQPollerZMQ.h, fairmq/zeromq/FairMQTransportFactoryZMQ.cxx, fairmq/zeromq/FairMQTransportFactoryZMQ.h
- Add `NewPoller()` wrapper for convenient poller creation, and tests for it and poller in general.
- Add a getter for channels: `GetChannel("channelName", index)`.
=> Add NewPoller() wrapper

base/sim/FairRootManagerSim.cxx, base/sim/FairRootManagerSimMT.cxx, base/steer/FairRootManager.cxx, base/steer/FairRootManager.h, base/steer/FairRun.cxx
Make the ctor of FairRootManager private
=> Correct singleton implimentation for FairRootManager

fairmq/docs/Development.md, fairmq/shmem/FairMQShmDeviceCounter.h, fairmq/shmem/FairMQShmMonitor.cxx, fairmq/shmem/FairMQShmMonitor.h, fairmq/shmem/runFairMQShmMonitor.cxx
- extend FairMQShmMonitor options and functionality (self-destruction, cleanup-once, interactive mode, custom segment name and timeout value).
- document FairMQShmMonitor in development section.
=> Shm monitor update

fairmq/docs/Development.md, fairmq/docs/Transport.md
=> add channel, poller and testing docs

fairmq/runFairMQDevice.h
=> Catch any exception type in the main of runFairMQDevice.h

base/sim/FairMCApplication.cxx
The FairMCApplication::ConstructGeometry assumes that the geometry volumes
are fully instantiated after calling the ConstructGeometry function on each detector modules.
This might not be the case, for instance when users are using TVirtualMC::Gsvol interface with
negative parameters which get fixed only later (during the closing phase of the geometry).
In consequence, all lookup tables might be incomplete or inconsistent.
This commit provides the following:
* Issue a warning when ConstructGeometry was actually incomplete
* Checking if gGeoManager is available at beginning of function
* Fixing a size problem in a for-loop used for the index to module mapping
=> Add consistency check/warning in FairMCApplication::ConstructGeometry

cmake/modules_old/FindGEANT4.cmake, cmake/modules_old/FindGEANT4VMC.cmake, cmake/modules_old/FindGENERATORS.cmake
This pull request improves the compatibility of FairRoot with aliBuild and Fairship. This work will be used with an updated recipe for FairRoot that was also developed during my CERN Summer Student internship.
=> Improve Support for aliBuild

base/event/FairMultiLinkedData.cxx
A wrong set FairLink in the experiment code can cause a wrong static cast to FairMultiLinkedData_Interface. To solve this  problem a check via TObject::InheritsFrom was introduced.
=> Check for correct cast to FairMultiLinkedData_Interface

examples/MQ/9-PixelDetector/run/scripts/ex9-dds-topology.xml
Adapt the XML file to the new MQ plugin.
=> example9 adaptation to new plugin

base/steer/FairRootManager.cxx, base/steer/FairRootManager.h, base/steer/FairRun.cxx
=> solve issue #640

fairmq/shmem/FairMQMessageSHM.cxx
=> FairMQ: fix shm transport placement new alignment issue

.travis.yml
Use Mac OSX 10.12 for test.
Use FairSoft mar17 for test.
=> Update Mac OSX test.

base/steer/FairRunSim.cxx
Macro can be loaded from the config dir or VMCWORKDIR/
GEANT4VMC_MACRO_DIR. Function is not called if macro not found.
This silences an error message if the macro can not be loaded.
=> Making g3libs.C/g4libs.C configuration macros optional

fairmq/plugins/DDS/CMakeLists.txt, fairmq/tools/Network.h
Some small fixes to properly install DDS plugin and handle the case where there are multiple default routes in linux (happens on my notebook, when wired and wireless connected at the same time).
=> Install DDS plugin

base/sim/FairModule.cxx, base/sim/FairModule.h
Create an interface to pass an additional matrix for positioning of the module in the cave from the macro when importing geometry from the ROOT file.
=> FairModule additional matrix

eventdisplay/CMakeLists.txt, eventdisplay/EventDisplayLinkDef.h, eventdisplay/FairEventManager.cxx, eventdisplay/FairEventManager.h, eventdisplay/FairXMLNode.cxx, eventdisplay/FairXMLNode.h
Added support of XML files for configuration of track colors, detectors colors, transparency in event display.
Removed "decoration bars" from last tab.
=> Support of XML files in EventDisplay

CMakeLists.txt, base/sim/FairMCApplication.cxx, base/sim/FairMCApplication.h, base/sim/FairModule.cxx, base/sim/FairModule.h, base/steer/FairRootManager.cxx, base/steer/FairRootManager.h
- Removed use of FairGenericRootManager, FairRootManagerSim and FairRootManagerSimMT
and merged locking for thread-unsafe code in FairRootManager
- Fixed filling of sensistive volume map (fVolMap) in FairMCApplication in MT mode
- Made static data in FairModule thread local
- Code clean-up in FairRootManager, FairMCApplication, FairModule
(Fixed indentions, removed tabulations)
=> Update for MT simulation

parbase/FairParAsciiFileIo.cxx
a small change in parbase/FairParAsciiFileIo.cxx
=> expand file path in case of some vars inside

base/steer/FairRunSim.cxx, base/steer/FairRunSim.h, examples/common/gconfig/g4Config.C, examples/simulation/Tutorial4/gconfig/g4Config.C, templates/project_template/gconfig/g4Config.C
this allows to select MT mode (for Geant4 only) from a user application macro.
=> Added FairRunSim::fIsMT data member and its getter/setter:

fairmq/shmem/FairMQSocketSHM.cxx
Transmit meta info of an shm multipart message in a single zmq message.
=> SHM: coalesce multipart messages

fairmq/CONTRIBUTORS
just noticed he is not yet in the list
=> FairMQ: Add new contributor

fairmq/plugins/DDS/DDS.cxx, fairtools/FairLogger.cxx, fairtools/FairLogger.h, logger/Logger.cxx, logger/Logger.h
Logger should ignore char* arguments that are nullptr.
=> Logger: handle nullptr.

fairmq/plugins/DDS/runDDSCommandUI.cxx
From DDS API perspective this is a breaking change, so the UI will no longer work with DDS version < 2.0.
The O2 DDS recipe is now updated to use DDS 2.0.
=> DDS command UI: update to 2.0 (include session arg)

fairmq/FairMQDevice.h
=> include FairMQProgOptions.h in FairMQDevice.h

fairmq/CMakeLists.txt
@ihrivnac Hi, I believe this should fix the issue you reported. It was an oversight in my last PR that got merged couple of days ago.
=> FairMQ: Fix regression bug introduced with PR#728

base/CMakeLists.txt, base/FairLinkDef.h, base/event/FairMultiLinkedData_Interface.h, base/event/FairPrintFairLinks.cxx, base/event/FairPrintFairLinks.h
This task prints all FairLinks belonging to a given set of branches into LOG(INFO).
Closes Issue #753
=> New task FairPrintFairLinks which prints all FairLinks of given branches

base/CMakeLists.txt, base/FairLinkDef.h, base/field/FairPropagator.cxx, base/field/FairPropagator.h, base/field/FairRKPropagator.cxx, base/field/FairRKPropagator.h
=> Added base abstract class for track propagation algorithms.

base/field/FairPropagator.cxx, base/field/FairPropagator.h, base/field/FairRKPropagator.cxx, geane/FairGeanePro.cxx, geane/FairGeanePro.h
- Inherit FairGeanePro from FairPropagator.
- Additional functions in FairPropagator interface.
=> changes to FairPropagator

base/sink/FairRootFileSink.h, base/steer/FairRootManager.cxx, base/steer/FairRootManager.h
Port fix from dev to v18.0 patches branch.
=> Reintroduce removed interface as deprecated

base/sim/FairDetector.cxx, base/sink/FairRootFileSink.cxx, base/source/FairFileSource.cxx, base/source/FairMixedSource.cxx, base/steer/FairRootManager.cxx, base/steer/FairRootManager.h
=> Read output folder name from VMCWORKDIR/config/rootmanager.dat

base/steer/FairRootManager.cxx, base/steer/FairRun.cxx
=> added include assert

base/steer/FairRun.cxx, base/steer/FairRun.h
Added option String to FairRun. Experiments should handle parsing by themselves.
Iterative retrieving of task names for task list.
=> Option String & ListOftTasks

base/MQ/tasks/FairMQSamplerTask.cxx, base/MQ/tasks/FairMQSamplerTask.h, base/event/FairMultiLinkedData.cxx, base/event/FairMultiLinkedData.h, base/sim/FairMCApplication.cxx, base/source/FairFileSource.cxx, base/source/FairMixedSource.cxx, base/steer/FairRingSorter.cxx, base/steer/FairRootManager.cxx, datamatch/FairMCEntry.cxx, datamatch/FairMCMatch.cxx, datamatch/FairMCMatch.h, datamatch/FairMCStage.cxx, datamatch/FairMCStage.h, examples/MQ/pixelDetector/src/PixelDigiSource.cxx, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.h, generators/FairShieldGenerator.cxx, test/fairtools/_TestFairTools.cxx, test/testlib/FairTestOutputHandler.cxx, test/testlib/FairTestOutputHandler.h
- Fix pass by const reference issues.
- Use range-based for loops (fixes "Prefer prefix ++/-- operators for non-primitive types." issues).
---
Checklist:
=> Fix issues detected by Codacy

examples/simulation/Tutorial1/README.md, examples/simulation/Tutorial1/macros/run_tutorial1.C
An example of how to set a random seed for both Geant3 and Geant4.
Implemented in examples/simulation/Tutorial1
---
Checklist:
=> Add example of setting the random seed.

doxygen/fairDoxy.conf
---
Checklist:
* [x ] Rebased against `dev` branch
* [x ] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x ] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)
=> Fix Doxygen project name

examples/simulation/Tutorial1/macros/run_tutorial1_binary.C, examples/simulation/Tutorial1/src/CMakeLists.txt, examples/simulation/Tutorial1/src/FairSimConfig.cxx, examples/simulation/Tutorial1/src/FairSimConfig.h, examples/simulation/Tutorial1/src/Tutorial1LinkDef.h, examples/simulation/Tutorial1/src/runTutorial1.cxx
Compile simulation macro of Tutorial1 into executable with command-line options.
---
Checklist:
=> Add example of simulation executable with options.

examples/MQ/histogramServer/fairmq-start-ex-histo.sh.in
=> Fix path to executables in histogram server example

base/steer/FairAnaSelector.cxx, base/steer/FairAnaSelector.h, base/steer/FairRunAnaProof.cxx, examples/advanced/Tutorial3/README.md, examples/advanced/Tutorial3/macro/CMakeLists.txt, examples/advanced/Tutorial3/macro/run_DiRePr.C
Updated proof example in tutorial3 to make it running again.
Created proof test.
---
Checklist:
=> proof and tutorial3

examples/simulation/Tutorial1/src/FairSimConfig.cxx
- In case an exception is thrown (typically unrecognised option), print help message and safely exit.
---
Checklist:
=> Implement catching of exception in program options of Tutorial1.

doxygen/fairDoxy.conf
---
Checklist:
* [ x] Rebased against `dev` branch
=> Switch on doxygen search functionality

Jenkinsfile, examples/simulation/Tutorial1/macros/run_tutorial1.C, examples/simulation/Tutorial2/macros/run_tutorial2.C, examples/simulation/rutherford/macros/run_rutherford.C
run G4 in MT mode if available
=> run G4 in MT mode if available

Jenkinsfile
add new jenkins client with MacOS 10.14 for testing of Mrs 
---
Checklist:
=> add new jenkins client for testing

Jenkinsfile, cmake/modules_old/FindGEANT4DATA.cmake, cmake/scripts/config.sh.in
In the new G4.10.5 the data files in  G4NEUTRONXS are replaced by G4PARTICLEXS. 
---
Checklist:
=> Add new env variable that is by G4.10.5

eventdisplay/EventDisplayLinkDef.h, eventdisplay/FairEventManager.cxx, eventdisplay/FairXMLNode.cxx, eventdisplay/FairXMLNode.h
Simplification XML interface.
Removed unused fields. Class for parsing XML files. Better management of memory.
=> Simplifycation of XML support in event dipslay.

examples/simulation/Tutorial4/macros/Create_Tutorial4_Geometry.C
Leftover errors from Root 5 times !!
=> correct typos in Tut4

base/sim/FairModule.h, examples/MQ/pixelDetector/src/Pixel.cxx, examples/advanced/Tutorial3/simulation/FairTestDetector.cxx, examples/common/passive/FairMagnet.cxx, examples/common/passive/FairTarget.cxx, examples/simulation/Tutorial1/src/FairTutorialDet1.cxx, examples/simulation/Tutorial1/src/FairTutorialDet1.h, examples/simulation/Tutorial2/src/FairTutorialDet2.cxx, examples/simulation/Tutorial2/src/FairTutorialDet2.h, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.h, examples/simulation/rutherford/src/FairRutherford.cxx, examples/simulation/rutherford/src/FairRutherford.h
- Call templated function FairModule::ConstructASCIIGeometry from detector classes.
- Avoid copying the implementation.
=> Implement ASCII geometry creation using templated function.

base/steer/FairRunOnline.cxx
- Fix the error, which happens if sink is initialized after source.
=> Change init order of sink and source.

alignment/FairAlignmentHandler.cxx, examples/simulation/Tutorial4/macros/run_reco.C, examples/simulation/Tutorial4/macros/run_tutorial4.C
In the new alignment package, create a TGeoHMatrix out of TGeoMatrix before multiplying as the TGeoMatrix does not have the * operator since root 6.14
This solve the issue #875
=> Solve issue #875

Jenkinsfile
Add new test configuration with new FairSoft RC
=> Add new test

base/sim/FairMCApplication.cxx, base/sim/FairMCApplication.h, base/sim/FairModule.cxx
kUnknown in FairMCApplication.h is conflicting with the same constant in R3BRoot
=> Change kUnknown to kUnknownState in FairMCApplication

COPYRIGHT
=> Add copyright file

eventdisplay/FairEventManager.cxx, eventdisplay/FairEventManager.h, eventdisplay/FairEventManagerEditor.cxx
Fix crashed FairEventManagerEditor when closed.
Added option of setting camera postion for projections.
---
Checklist:
=> Event display fix

base/sim/FairGenericStack.cxx, base/sim/FairGenericStack.h, base/sim/FairMCApplication.cxx, base/sim/fastsim/FairFastSimModel.cxx, base/steer/FairTrajFilter.cxx, base/steer/FairTrajFilter.h, examples/common/mcstack/FairStack.cxx, examples/common/mcstack/FairStack.h, examples/simulation/Tutorial1/src/FairFastSimExample.cxx
FastSimulation
Added possibility to create secondaries in the FastSim medium.
---
Checklist:
=> FastSim secondaries

CMakeLists.txt, base/MQ/devices/BaseMQFileSink.h, base/MQ/devices/FairMQLmdSampler.h, base/MQ/devices/FairMQSampler.h, base/MQ/devices/FairMQUnpacker.h, examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx, examples/MQ/serialization/1-simple/Ex1Processor.h, examples/MQ/serialization/1-simple/Ex1Sampler.h, examples/MQ/serialization/1-simple/Ex1Sink.h, examples/MQ/serialization/2-multipart/Ex2Processor.h, examples/MQ/serialization/2-multipart/Ex2Sampler.h, examples/MQ/serialization/2-multipart/Ex2Sink.h, fairtools/MCStepLogger/MCStepLoggerImpl.cxx
Replaced CheckCurrentState by !NewStatePending.
---
Checklist:
=> MQ warnings fix

examples/simulation/rutherford/macros/run_rutherford.C, generators/CMakeLists.txt, generators/FairBaseMCGenerator.cxx, generators/FairBaseMCGenerator.h, generators/FairBoxGenerator.cxx, generators/FairBoxGenerator.h, generators/FairIonGenerator.cxx, generators/FairIonGenerator.h, generators/FairParticleGenerator.cxx, generators/FairParticleGenerator.h, generators/FairYPtGenerator.cxx, generators/FairYPtGenerator.h, generators/GenLinkDef.h
New generator that generate particles by using histogram with Y-Pt distribution.
---
Checklist:
=> Added new generator.

base/sim/FairDetector.h, doxygen/doxyfile.in
Improve class documentation of simulation detector class (#913) and update the Doxygen configuration ( #904)
=> Improve docs

base/event/FairHit.cxx, base/event/FairHit.h, examples/MQ/pixelDetector/src/PixelHit.cxx, examples/MQ/pixelDetector/src/PixelHit.h, examples/MQ/serialization/data/MyHit.cxx, examples/MQ/serialization/data/MyHit.h, examples/advanced/Tutorial3/data/FairTestDetectorHit.cxx, examples/advanced/Tutorial3/data/FairTestDetectorHit.h, examples/simulation/Tutorial4/src/data/FairTutorialDet4Hit.cxx, examples/simulation/Tutorial4/src/data/FairTutorialDet4Hit.h, geane/FairGeanePro.cxx, geane/FairGeanePro.h
Instead of reference.
Adresses issue #891 
---
Checklist:
[*] Rebased against `dev` branch
[*] My name is in the resp. CONTRIBUTORS/AUTHORS file
[*] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)
=> Use const ref TVector3

Dart.sh, base/sim/FairModule.cxx, examples/MQ/pixelDetector/src/PixelGeo.cxx, examples/advanced/Tutorial3/simulation/FairTestDetectorGeo.cxx, examples/advanced/propagator/src/FairTutPropGeo.cxx, examples/simulation/Tutorial1/src/FairTutorialDet1Geo.cxx, examples/simulation/Tutorial2/src/FairTutorialDet2Geo.cxx, examples/simulation/Tutorial4/src/mc/FairTutorialDet4Geo.cxx, examples/simulation/rutherford/src/FairRutherfordGeo.cxx, templates/NewDetector_root_containers/NewDetectorGeo.cxx, templates/NewDetector_stl_containers/NewDetectorGeo.cxx, templates/NewDetector_stl_containers/NewDetectorPoint.cxx, templates/project_root_containers/MyProjGenerators/Pythia8Generator.cxx, templates/project_root_containers/NewDetector/NewDetectorGeo.cxx, templates/project_stl_containers/MyProjGenerators/Pythia8Generator.cxx, templates/project_stl_containers/NewDetector/NewDetectorGeo.cxx, templates/project_stl_containers/NewDetector/NewDetectorPoint.cxx
* [ x] Rebased against `dev` branch
=> Fix codacy issues

base/event/FairPrintFairLinks.cxx, base/event/FairRunInfo.cxx, base/sim/FairMCApplication.cxx, datamatch/FairMCMatch.cxx, fairtools/FairMonitor.cxx
* [x ] Rebased against `dev` branch
=> Fix codacy issue iterator

Jenkinsfile, base/sim/FairModule.cxx, base/sim/FairModule.h, geane/FairGeanePro.cxx, geane/FairGeanePro.h
Replace the warnings introduced to FairModule and FairGeanePro with compiler warnings.
Resolves issue #965.
---
Checklist:
=> Remove annoying warnings

fairtools/FairMonitor.cxx
Quick fix for issue #966.
---
Checklist:
[ * ] Rebased against `dev` branch
[ * ] My name is in the resp. CONTRIBUTORS/AUTHORS file
[ * ] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)
=> Apply protection against missing fCanvas

base/event/FairEventBuilderManager.cxx, base/sim/fastsim/FairFastSimModel.cxx, base/steer/FairRunSim.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQChunkMerger.cxx, examples/advanced/propagator/src/FairTutPropTr.cxx, generators/FairBaseMCGenerator.cxx, trackbase/FairPropagator.h, trackbase/FairRKPropagator.cxx, trackbase/FairRKPropagator.h
=> suppress  more  warnings

base/steer/FairRootManager.cxx, base/steer/FairRunAna.cxx, base/steer/FairRunSim.cxx
=> Remove cout 

examples/MQ/pixelDetector/run/CMakeLists.txt, examples/MQ/pixelDetector/run/scripts/pixel-dds-simulation_old.xml, examples/MQ/pixelDetector/run/scripts/test-pixelSim.sh.in, examples/MQ/pixelDetector/run/scripts/test-pixelSim_old.sh.in, examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx, examples/MQ/pixelDetector/src/devices/FairMQSimDevice.h, examples/MQ/pixelSimSplit/run/CMakeLists.txt, examples/MQ/pixelSimSplit/run/scripts/splitMC-topology_old.xml, examples/MQ/pixelSimSplit/run/scripts/test-splitMC_old.sh.in, examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.h
Checklist:
[ x ] Rebased against `dev` branch
[ x ] My name is in the resp. CONTRIBUTORS/AUTHORS file
[ x ] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)
=> Reinstate the DDS-based pixelSimSplit test

base/sim/FairMCApplication.cxx
Do not call PreTrack() twice
---
Checklist:
=> Fix in FairMCApplication:

examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx
=> Fix a convertion from TString to string in Tutorial4

CMakeLists.txt, templates/project_root_containers/CMakeLists.txt, templates/project_stl_containers/CMakeLists.txt
1. Synchronize Boost finding in the templates with the main CMakeLists.txt.
2. Make extensive use of ADD_REQUIREMENTS_OF there.
3. Update ADD_REQUIREMENTS_OF in the main CMakeLists.txt.
---
Checklist:
=> Fix find_package(Boost)

FairRoot_build_test.cmake
If the build fails, there is no need to run the tests, really. So don't run them.
---
Checklist:
=> ci: Fail Early After Build Failure

fairtools/FairLogger.cxx
=> fairtools: Create stacktrace file only if 'Root.Stacktrace: yes'

base/steer/FairRootManager.cxx, base/steer/FairRootManager.h
=> base: Remove 'requested branch name' instrumentation

base/steer/FairRootManager.cxx, base/steer/FairRun.cxx, examples/MQ/pixelSimSplit/run/runMQGen.cxx, examples/MQ/pixelSimSplit/run/runMQTrans.cxx, examples/advanced/propagator/src/FairEveRecoTracksExample.cxx, examples/common/eventdisplay/FairEveMCTracks.cxx, examples/common/mcstack/FairStack.cxx, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx, fairtools/FairMonitor.cxx, parmq/ParameterMQServer.cxx
Upper case severities are deprecated in FairLogger 1.10.
So switch all severities over to lower case.
---
Checklist:
=> Use Lower Case FairLogger Severities

parbase/FairParRootFileIo.cxx
`TFile::Open()` returns a `TFile*` and expects the caller to `delete` the object after using it.
Use `std::unique_ptr` to handle this.
---
Checklist:
=> parbase: Do not Leak TFile Objects

alignment/AlignmentLinkDef.h, alignment/CMakeLists.txt, base/steer/FairRunAna.cxx, cmake/modules/FindROOT.cmake
Add missing streamer which allows to read/write the data format required by the FairAlignmentHandler from/to file.
Fix linking problem on macosx12.
---
Checklist:
* [ x] Rebased against `apr21_patches` branch
=> V18.6 patches

alignment/AlignmentLinkDef.h, alignment/CMakeLists.txt, base/steer/FairRunAna.cxx
Implement the changes to the alignment code which will be added with #1124 in the v18.6_patches branch.
The additional commit to fix a linking problem on macosx 12 isn't needed for the dev branch.
---
Checklist:
* [ x] Rebased against `dev` branch
=> Fix alignment

CHANGELOG.md, base/steer/FairRootManager.cxx, base/steer/FairRootManager.h
See-Also: 1da8249a8fbf07380bb7b2f5017c809a61cf2fe9
---
Checklist:
=> Drop deprecated FairRootManager::GetOut{File,Tree}

examples/advanced/propagator/macros/runMC.C, examples/common/geometry/tutProp2.geo
Minor fix of geometry names.
---
Checklist:
[X] Rebased against `dev` branch
[X] My name is in the resp. CONTRIBUTORS/AUTHORS file
[X] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)
=> Fix the propagator 2 detector

base/steer/FairRootManager.cxx, base/steer/FairRootManager.h
Reworked the setting of the tree and folder names.
Added the possibility to set these names in the macro.
These setters have to be called before calling run->Init().
=> [backport 18.6] Add SetTreeName and SetFolderName setters

base/steer/FairRootManager.cxx, base/steer/FairRootManager.h
Reworked the setting of the tree and folder names.
Added the possibility to set these names in the macro.
These setters have to be called before calling run->Init().
=> [backport 18.4] Add SetTreeName and SetFolderName setters

examples/simulation/Tutorial2/macros/run_background.C, examples/simulation/Tutorial2/macros/run_signal.C, examples/simulation/Tutorial2/macros/run_tutorial2.C
See: #1148
See: #1149
---
Checklist:
=> Switch Tutorial2 from Geant3 to Geant4

cmake/modules/FindROOT.cmake
This is needed for FairRootGroup/FairSoft#463. (Will also cherry-pick this to `v18.4_patches` once merged)
=> Support Root 6.26

Jenkinsfile, base/steer/FairRadLenManager.cxx, examples/MQ/pixelAlternative/src/devices/FairMQPixAltFileSinkBin.cxx, examples/MQ/pixelAlternative/src/devices/FairMQPixAltSamplerBin.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQChunkMerger.cxx, examples/common/passive/FairGeoPassivePar.cxx, examples/common/passive/FairPassiveContFact.cxx, parbase/FairParIo.cxx, templates/project_root_containers/MyProjGenerators/Pythia8Generator.cxx, templates/project_root_containers/MyProjGenerators/Pythia8Generator.h, templates/project_root_containers/passive/MyPassiveContFact.cxx, templates/project_stl_containers/MyProjGenerators/Pythia8Generator.cxx, templates/project_stl_containers/MyProjGenerators/Pythia8Generator.h, templates/project_stl_containers/passive/MyPassiveContFact.cxx, trackbase/FairGeaneUtil.cxx, trackbase/FairTrackPar.cxx
Those "using namespace" can just be removed.
---
Checklist:
=> Remove Unneeded "using namespace"

.clang-tidy, base/MQ/tasks/FairMQSamplerTask.cxx, base/event/FairMesh.cxx, base/steer/FairRadMapManager.cxx, base/steer/FairTrajFilter.cxx, examples/MQ/parameters/FairMQExParamsClient.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelMerger.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelSampler.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelSamplerBin.cxx, examples/MQ/pixelDetector/src/devices/FairMQRunDevice.cxx, examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQPrimaryGeneratorDevice.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx, examples/MQ/serialization/data_generator/runGenerateData.cxx, examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkFlatBuffers.tpl, examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskFlatBuffers.tpl, examples/advanced/Tutorial3/MQ/samplerTask/FairTestDetectorDigiLoaderFlatBuffers.tpl, examples/common/passive/FairGeoCave.cxx, examples/simulation/Tutorial1/macros/run_tutorial1_binary.C, examples/simulation/Tutorial1/src/FairSimConfig.cxx, examples/simulation/rutherford/src/FairRutherfordPoint.cxx, fairtools/MCConfigurator/FairYamlVMCConfig.cxx, fairtools/MCConfigurator/FairYamlVMCConfig.h, parmq/ParameterMQServer.cxx, templates/project_root_containers/passive/MyGeoCave.cxx, templates/project_stl_containers/passive/MyGeoCave.cxx
"using namespace foo" isn't really good.  It will import
all names from that nemespace, including any future ones
that might conflict with local names.
So avoid this construct.
---
Checklist:
=> Do not Use "using namespace"

Jenkinsfile, base/event/FairMultiLinkedData_Interface.cxx, eventdisplay/FairXMLNode.cxx, eventdisplay/tracks/FairEveGeoTracksEditor.cxx, examples/advanced/propagator/src/FairEveRecoTracksExampleEditor.cxx, examples/common/eventdisplay/FairEveMCTracksEditor.cxx
Should calm down the modernize-make-unique warnings.
---
Checklist:
=> Use `std::make_unique` in More Places

CMakeLists.txt, Jenkinsfile
* C++ 17 is quite standard by now
* FairSoft apr21 and apr22 are already at C++17
---
Checklist:
=> Switch to C++17

eventdisplay/FairEventManager.cxx
This should fix the issue 
---
Checklist:
=> Fix segfault when closing event display.

base/MQ/policies/Serialization/RootSerializer.h, examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.h, examples/MQ/pixelSimSplit/run/CMakeLists.txt, examples/MQ/pixelSimSplit/run/scripts/test-splitMQ.sh.in, examples/MQ/pixelSimSplit/src/devices/FairMQChunkMerger.cxx
Removed the DDS requirement for ex_MQ_pixel_split test.
Fix bug, now properly storing data.
Fix issue 1169.
---
Checklist:
[ x ] Rebased against `dev` branch
[ x ] My name is in the resp. CONTRIBUTORS/AUTHORS file
[ x ] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)
=> Changes to pixelSimSplit

examples/simulation/Tutorial4/macros/eventDisplay.C, examples/simulation/Tutorial4/macros/run_tutorial4.C
* Create output directory
* Use output directory in eventdisplay
---
Checklist:
=> Tutorial4: Small Fixes

base/source/FairFileSource.cxx, base/source/FairFileSource.h, base/source/FairFileSourceBase.h, base/source/FairMixedSource.cxx, base/source/FairMixedSource.h
* Remove unused member variable
* Move Simple Common Code into base class
* Simple cleanup
---
Checklist:
=> Fair{File,Mixed}Source{,Base}: Simple Cleanups

base/sim/FairBaseContFact.h, base/sim/FairBaseParSet.h, base/sim/FairGeaneApplication.h, base/sim/FairGeoParSet.h, base/sim/FairModule.h, base/sim/FairParticle.h, base/sim/FairVolume.cxx, base/sim/FairVolume.h, base/sim/fastsim/FairFastSimDetector.h, base/steer/FairAnaSelector.h, base/steer/FairRingSorterTask.h, base/steer/FairRootManager.h, base/steer/FairTSBufferFunctional.h, base/steer/FairWriteoutBuffer.h
* FairVoume: Major cleanup
* Rest: override
---
Checklist:
=> base/{sim,steer}: override, const, cleanup

examples/simulation/Tutorial1/src/FairTutorialDet1.cxx, examples/simulation/Tutorial1/src/FairTutorialDet1.h
Follow up from #1196 
---
Checklist:
=> FairTutorialDet1: Simple Cleanups

examples/simulation/Tutorial4/macros/CMakeLists.txt, examples/simulation/Tutorial4/macros/plots.C
Bug fixing.
Addresses issue #1209.
---
Checklist:
=> Fix the Tutorial4 plots macro

FairRoot_build_test.cmake, FairRoot_doxygen_test.cmake, FairRoot_format_test.cmake, Jenkinsfile, cmake/modules/FindClangFormat.cmake, cmake/private/Testlib.cmake, doxygen/doxyfile.in
Let's try "Warnings Next Generation" on Doxygen warnings as well.
Also upgrade clang-format and fix some Doxygen settings.
---
Checklist:
=> ci: Apply Warning Stats on Doxygen

FairRoot_build_test.cmake, FairRoot_doxygen_test.cmake, FairRoot_format_test.cmake, Jenkinsfile, cmake/README.md, cmake/private/Testlib.cmake
1. On Each PR and branch build, run doxygen and publish the result on an internal webserver.
2. Document `fairroot_check_root_cxxstd_compatibility` in the CMake docs.
* The new CMake docs can be seen here: http://lxci001.gsi.de/ci/tmp/jenkins-FairRootGroup-FairRoot-PR-1216-3/d9/dcc/cmake.html#autotoc_md15
---
Checklist:
=> Start CMake docs ; Publish Doxygen Internally

CHANGELOG.md, base/field/FairFieldFactory.h, base/sim/FairGeaneApplication.h, base/sim/FairModule.h, base/steer/FairRadGridManager.h, base/steer/FairRadLenManager.h, base/steer/FairRadMapManager.h, base/steer/FairRootManager.h, base/steer/FairRunAnaProof.h, base/steer/FairTask.h, geane/FairGeanePro.h, geobase/FairGeoVector.h
* forward port deprecation changes from 18.8
* Add the 18.8 ChangeLog entry to the main ChangeLog
---
Checklist:
=> forward port docs from 18.8

examples/advanced/propagator/macros/CMakeLists.txt, examples/simulation/Tutorial2/macros/CMakeLists.txt, examples/simulation/Tutorial2/macros/create_digis_mixed.C, examples/simulation/Tutorial4/macros/CMakeLists.txt
Added fixtures to simulation Tutorial2 and Tutorial4, as well as to propagator.
Addresses issue #1080.
---
Checklist:
=> Add fixtures in some examples

parbase/FairRuntimeDb.cxx, parbase/FairRuntimeDb.h
See: https://fairroot.gsi.de/index.html%3Fq=node%252F53.html
---
Checklist:
=> docs(FairRuntimeDb): Add some Docs from fairroot.gsi.de

parbase/FairContFact.h, parbase/FairDetParRootFileIo.cxx, parbase/FairDetParRootFileIo.h, parbase/FairParIo.h, parbase/FairRtdbRun.cxx, parbase/FairRtdbRun.h, parbase/FairRuntimeDb.cxx, parbase/FairRuntimeDb.h
=> parbase: Use more const, drop const_cast

CHANGELOG.md, base/sim/FairModule.h, examples/MQ/pixelDetector/src/Pixel.cxx, examples/advanced/Tutorial3/simulation/FairTestDetector.cxx, examples/advanced/propagator/src/FairTutPropDet.cxx, examples/common/passive/FairMagnet.cxx, examples/common/passive/FairTarget.cxx, examples/simulation/Tutorial1/src/FairTutorialDet1.cxx, examples/simulation/Tutorial1/src/FairTutorialDet1.h, examples/simulation/Tutorial2/src/FairTutorialDet2.cxx, examples/simulation/Tutorial2/src/FairTutorialDet2.h, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx, examples/simulation/Tutorial4/src/mc/FairTutorialDet4.h, examples/simulation/rutherford/src/FairRutherford.cxx, examples/simulation/rutherford/src/FairRutherford.h
Proposal to fix #1145
~~Had to use different function name, because the existing helper's default arguments would have overlapped with my proposed "overload".~~
edit: The original approach grew into hundreds of lines of code changes, so I aborted it (due to lack of test coverage) and went now with the minimal fix I can think of.
=> Attempt at fixing the `ConstructASCIIGeometry` helper

Jenkinsfile
=> Add nov22 CI builds

examples/MQ/histogramServer/FairMQExHistoDevice.cxx, examples/MQ/pixelDetector/src/devices/FairMQRunDevice.cxx, examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx, examples/advanced/propagator/macros/runProp.C, examples/advanced/propagator/macros/runPull.C, examples/advanced/propagator/src/FairTutPropDet.cxx, examples/advanced/propagator/src/FairTutPropHitProducer.cxx, examples/advanced/propagator/src/FairTutPropTrackFinder.cxx, fairtools/MCConfigurator/FairYamlVMCConfig.cxx, parmq/ParameterMQServer.cxx
Changed the macros in the propagator example,
as well as varius calls to .data() throughout the code.
Addresses issue #1296.
---
Checklist:
=> Replace string.data() with string.c_str()

README.md
Addresses issue #1276.
---
Checklist:
=> Update main README.md file

alignment/FairAlignmentHandler.cxx, alignment/FairAlignmentHandler.h
* Apply some clang-tidy cleanups
* Use TRangeDynCast in RecomputePhysicalAssmbBbox
@PALoizeau as you authored #1244, could you take a look at this?
=> Cleanup FairAlignmentHandler

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Initial work done by @dennisklein in #1277.
(Took his commit directly, just rebased.)
Added the notes from the discussion in the original PR.
Rendered: https://github.com/ChristianTackeGSI/FairRoot/blob/docs-contributing/CONTRIBUTING.md
---
Checklist:
=> Add `CONTRIBUTING.md`

examples/MQ/serialization/1-simple/Ex1Processor.h
fix part of #1286: The result of ROOT's deserializer should be checked.
=> fix(Ex1Processor): Handle nullptr, cleanup

base/sim/FairMCApplication.cxx, base/sim/FairMCApplication.h
* Use `unique_ptr` for `fStack`
* Cleanup sensitive volume Setup
* Drop `fModIter`
---
Checklist:
=> FMCA: unique_ptr(fStack), less member variables

AUTHORS
cc: @MohammadAlTurany, @dennisklein 
---
Checklist:
=> Add ORCiDs to AUTHORS

CHANGELOG.md, base/sim/FairMCApplication.cxx, base/sim/FairMCApplication.h, base/sink/FairRootFileSink.cxx, base/steer/FairRunSim.cxx, base/steer/FairRunSim.h, examples/simulation/Tutorial1/macros/CMakeLists.txt, examples/simulation/Tutorial1/macros/run_tutorial1.C
Added test for G4MT simulation.
Fixed running G4MT simulation.
This PR replaces PR #1245, which will be deleted.
---
Checklist:
=> Fix Geant4 MT simulation

examples/MQ/serialization/processor.cxx, examples/MQ/serialization/sink.cxx
To assist debugging, check the number of received messages.
This might help in debugging #1295
---
Checklist:
=> Serialization Examples: Diagnose Amount of Messages

fairroot/parbase/FairContFact.cxx, fairroot/parbase/FairDetParAsciiFileIo.cxx, fairroot/parbase/FairDetParIo.cxx, fairroot/parbase/FairDetParRootFileIo.cxx, fairroot/parbase/FairGenericParAsciiFileIo.cxx, fairroot/parbase/FairGenericParRootFileIo.cxx, fairroot/parbase/FairParAsciiFileIo.cxx, fairroot/parbase/FairParGenericSet.cxx, fairroot/parbase/FairParIo.cxx, fairroot/parbase/FairParRootFileIo.cxx, fairroot/parbase/FairParSet.cxx, fairroot/parbase/FairParamList.cxx, fairroot/parbase/FairRtdbRun.cxx, fairroot/parbase/FairRuntimeDb.cxx, fairroot/parbase/FairRuntimeDb.h
=> chore(parbase): Drop ClassImp

fairroot/base/steer/FairRunAnaProof.cxx
Reworked according to FairRunAna.
Addresses point 1 in issue #1346.
---
Checklist:
=> Remove GetObject from FairRunAnaProof

README.md
Rendered: https://github.com/FairRootGroup/FairRoot/tree/add-fair-software-compliance-badge#readme
Let's have a PR for this branch, so that we don't forget about it!
---
Checklist:
=> Add fair software compliance badge

.github/workflows/fair-software.yml, README.md
Rendered: https://github.com/FairRootGroup/FairRoot/tree/fair-software-compliance-badge#readme
By adding most of the badge related commits to our `master` branch, we acquired two more points. So updated the badge!
Also only run the github action ci workflow only if we change the README.md. Safe some energy and etc.
---
Checklist:
=> Update fair-software.eu badge

codemeta.json, meta_update.py
=> docs: Use `meta_update` to update codemeta.json

fairroot/alignment/FairAlignmentHandler.cxx
**Related to:**
- cf discussion in https://github.com/root-project/root/issues/12242
- Improvement of PR #1244
- see also Issue #1243
- Solves new sub-case of Cbmroot issue https://redmine.cbm.gsi.de/issues/2620 (behind CBM login due to GSI policy)
**Summary:**
Replace original fix with more generic solution also catching edge case where only Nodes inside assembly are aligned but not assembly itself.
**Problem description** 
(valid for original patch in Fairroot v18.8.0 and v18.8.1):
- previous re-computation patch is only applied to Assemblies which are/have a PhysicalNode (first check if PhysicalNode, then if Assembly)
- by default, Assemblies do not have/are not PhysicalNodes (not expert on Geometries myself, so maybe bad description)
- the alignment procedure forces a PhysicalNode …
=> GeoAssembly bounding box after alignment: use ROOT expert patch

codemeta.json
Added required fields:
- maintainer
- readme
Added recommended fields:
- codeRepository
- identifier
- issueTracker
---
Checklist:
=> Add some missing fields to codemeta

fairroot/online/source/FairLmdSource.cxx, fairroot/online/source/FairLmdSource.h, fairroot/online/source/FairMbsSource.cxx, fairroot/online/source/FairMbsSource.h, fairroot/online/source/FairMbsStreamSource.cxx, fairroot/online/source/FairMbsStreamSource.h, fairroot/online/source/FairOnlineSource.cxx, fairroot/online/source/FairOnlineSource.h, fairroot/online/source/FairRemoteSource.cxx, fairroot/online/source/FairRemoteSource.h, fairroot/online/source/FairUnpack.cxx, fairroot/online/source/FairUnpack.h, fairroot/online/source/MRevBuffer.cxx, fairroot/online/source/MRevBuffer.h, fairroot/online/steer/FairRunOnline.cxx, fairroot/online/steer/FairRunOnline.h
=> chore(online): Drop ClassImp, override

doxygen/singleton.dox, fairroot/base/field/FairFieldFactory.h, fairroot/base/sim/FairGeaneApplication.h, fairroot/base/sim/FairMCApplication.h, fairroot/base/steer/FairLinkManager.h, fairroot/base/steer/FairRadGridManager.h, fairroot/base/steer/FairRadLenManager.h, fairroot/base/steer/FairRadMapManager.h, fairroot/base/steer/FairRun.h, fairroot/base/steer/FairRunAna.h, fairroot/base/steer/FairRunAnaProof.h, fairroot/base/steer/FairRunSim.h, fairroot/base/steer/FairTrajFilter.h, fairroot/eventdisplay/FairEventManager.h, fairroot/online/steer/FairRunOnline.h
Start to document the "singleton"-like pattern of FairRoot as requested https://github.com/FairRootGroup/FairRoot/pull/1394#discussion_r1170089009
Rendered: http://lxci001.gsi.de/ci/tmp/jenkins-FairRootGroup-FairRoot-PR-1395-6/de/df4/group__fairroot__singleton.html
---
Checklist:
=> docs: Document the "singleton" like pattern

fairroot/parbase/FairParAsciiFileIo.cxx, fairroot/parbase/FairParAsciiFileIo.h, fairroot/parbase/FairParIo.cxx, fairroot/parbase/FairParIo.h, fairroot/parbase/FairParRootFileIo.cxx
* chore(parbase): Refactor print/close
* chore: Use value semantics in FairParAsciiFileIo
---
Checklist:
=> chore(parbase): Refactor FairPar*Io

fairroot/base/steer/FairRun.cxx, fairroot/base/steer/FairRun.h, fairroot/base/steer/FairRunAna.cxx, fairroot/base/steer/FairRunAnaProof.cxx
I learned about the [Facade pattern](https://en.wikipedia.org/wiki/Facade_pattern) from @dennisklein and he also suggested to improve the documentation about this.
For the current cases:
From the page:
> * improve the readability and usability of a software library by masking interaction with more complex components behind a single (and often simplified) API
simplified: Yes
Trying to improve the readability (of the callers): Yes
> * provide a context-specific interface to more generic functionality (complete with context-specific input validation)
Yes!
Well, not everything is validated. But see the `\todo`.
> * serve as a launching point for a broader refactor
Maybe.
Note: The Facade pattern talks about objects, while this here is more applied to member functions.
---
Checklist:
=> Improve Documentation for internal facades

Jenkinsfile
Look at the graph "Commit Statistics Trend" at the top: https://alfa-ci.gsi.de/job/FairRootGroup/job/FairRoot/job/PR-1425/
And the "Commit Diff Statistics" at https://alfa-ci.gsi.de/job/FairRootGroup/job/FairRoot/job/PR-1425/2/
---
Checklist:
=> ci: Aquire some git Stats

eventdisplay/tracks/FairEveGeoTracks.cxx, examples/advanced/propagator/src/FairEveRecoTracksExample.cxx, examples/common/eventdisplay/FairEveMCTracks.cxx
This is a backport of a fix inside of #1392.
---
Checklist:
=> [backport] fix(eventdisplay): Fix wrong init order.

CMakeLists.txt, Jenkinsfile, examples/advanced/Tutorial3/CMakeLists.txt, test/ci/slurm-submit.sh
=> [backport 18.8] CI Matrix; Protobuf/Abseil fix

.github/workflows/codemeta_validate.yaml
Use the eOSSR tooling to validate our codemeta.json file
See the [Checks tab](https://github.com/FairRootGroup/FairRoot/pull/1437/checks)
---
Checklist:
=> ci: Check codemeta.json

.clang-format, fairroot/tools/CMakeLists.txt, fairroot/tools/FairMemory.h
See the doxygen comments for some details.
Will be needed in #1416, #1430.
---
Checklist:
=> feature: Introduce `maybe_owning_ptr`

.github/workflows/codemeta_validate.yaml, CMakeLists.txt, FairRoot_build_test.cmake, cmake/private/FairRootCodemeta.cmake, codemeta.json, meta_update.py
Waiting for
I would like to have all our codemeta stuff in the next 18.8.x release!
---
Checklist:
=> [backport 18.8] Backport all codemeta things

fairroot/CMakeLists.txt, fairroot/tools/CMakeLists.txt, fairroot/tools/FairMemory.h, fairroot/tools/tests/CMakeLists.txt, fairroot/tools/tests/maybe_owning.cxx
=> test: Add maybe_owning test

CMakeLists.txt, alignment/FairAlignmentHandler.cxx, alignment/FairAlignmentHandler.h, base/steer/FairRunSim.cxx, examples/simulation/Tutorial2/macros/CMakeLists.txt, examples/simulation/Tutorial2/macros/compare_seed_value.C, examples/simulation/Tutorial2/macros/create_digis.C, examples/simulation/Tutorial2/macros/create_digis_mixed.C, examples/simulation/Tutorial2/macros/read_digis.C, examples/simulation/Tutorial2/macros/run_background.C, examples/simulation/Tutorial2/macros/run_signal.C, examples/simulation/Tutorial2/macros/run_tutorial2.C, fairtools/MCConfigurator/CMakeLists.txt, templates/project_root_containers/MyProjGenerators/Pythia8Generator.h, templates/project_stl_containers/MyProjGenerators/Pythia8Generator.h
Backport the following PRs from the dev branch 
- #1389 
- #1412
- #1447
---
Checklist:
=> [backport 18.8] #1389, #1412, #1447

CMakeLists.txt, alignment/FairAlignmentHandler.cxx, alignment/FairAlignmentHandler.h, fairtools/MCConfigurator/CMakeLists.txt
- #1244
- #1389 
- #1447
---
Checklist:
=> [backport 18.6] #1244, #1389, #1447

.github/workflows/codemeta_validate.yaml
=> chore: upgrade checkout step to v4

.zenodo.json
As suggested by Dennis.
---
Checklist:
=> Add config for zenodo.org import

.zenodo.json
Add config for zenodo.org import
---
Checklist:
=> [backport 18.8] Zenodo json

examples/MQ/parameters/FairMQExParamsContFact.h, examples/advanced/Tutorial3/simulation/FairTestDetectorContFact.h, examples/advanced/propagator/src/FairTutPropContFact.cxx, examples/advanced/propagator/src/FairTutPropContFact.h, examples/common/passive/FairPassiveContFact.h, examples/simulation/Tutorial1/src/FairTutorialDet1ContFact.h, examples/simulation/Tutorial2/src/FairTutorialDet2ContFact.h, examples/simulation/Tutorial4/src/param/FairTutorialDet4ContFact.h, examples/simulation/rutherford/src/FairRutherfordContFact.h, templates/NewDetector_root_containers/NewDetectorContFact.h, templates/NewDetector_stl_containers/NewDetectorContFact.h, templates/project_root_containers/NewDetector/NewDetectorContFact.h, templates/project_root_containers/passive/MyPassiveContFact.cxx, templates/project_root_containers/passive/MyPassiveContFact.h, templates/project_stl_containers/NewDetector/NewDetectorContFact.h, templates/project_stl_containers/passive/MyPassiveContFact.cxx, templates/project_stl_containers/passive/MyPassiveContFact.h
and add some override, while in those files.
(follow up from #1457)
---
Checklist:
=> chore: Drop Fair{ParSet,Container} forward decls

CHANGELOG.md
Add hyperlinks, streamline and shorten phrases, fix errors.
=> docs: Improve CHANGELOG

CHANGELOG.md
:warning: Don't press the merge button! Use the CLI to perform a fast forward push (or let @dennisklein or me perform it after approving)
I think the the current changes in `v19.0_patches` should also be part of the `dev` branch?
If you think this is a good idea, please approve.
=> incorporate 19.0 changes in dev

Jenkinsfile
=> ci: Update

FairRoot_doxygen_test.cmake, Jenkinsfile, cmake/private/Testlib.cmake, examples/MQ/histogramServer/FairMQExHistoDevice.cxx, examples/MQ/pixelAlternative/src/devices/FairMQPixAltTaskProcessorBin.h, examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelMerger.cxx, examples/MQ/pixelDetector/src/devices/FairMQPixelTaskProcessor.h, examples/MQ/pixelDetector/src/devices/FairMQRunDevice.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQChunkMerger.cxx, examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx, examples/MQ/serialization/processor.cxx, examples/advanced/Tutorial3/MQ/data/PayloadDigi.fbs, examples/advanced/Tutorial3/MQ/data/PayloadHit.fbs, examples/advanced/Tutorial3/MQ/fileSink/FileSinkFlatBuffers.h, examples/advanced/Tutorial3/MQ/processorTask/MQRecoTaskFlatBuffers.h, examples/advanced/Tutorial3/MQ/samplerTask/DigiLoaderFlatBuffers.h, fairroot/basemq/devices/FairMQLmdSampler.h, fairroot/basemq/devices/FairMQUnpacker.h, fairroot/fairmq/FairMQ.h
=> Fix various warnings

FairRoot_build_test.cmake, Jenkinsfile
Followup on #1521 as I cannot push there
=> ci: Do not check Geant3 on macos

CMakeLists.txt, tests/examples/CMakeLists.txt, tests/examples/MQ/pixelDetector/CMakeLists.txt, tests/examples/MQ/pixelDetector/test_PixelGeo.cxx, tests/examples/advanced/Tutorial3/CMakeLists.txt, tests/examples/advanced/Tutorial3/test_FairTestDetectorGeo.cxx, tests/examples/advanced/propagator/CMakeLists.txt, tests/examples/advanced/propagator/test_FairTutPropGeo.cxx, tests/examples/simulation/Tutorial1/CMakeLists.txt, tests/examples/simulation/Tutorial1/test_FairTutorialDet1Geo.cxx, tests/examples/simulation/Tutorial2/CMakeLists.txt, tests/examples/simulation/Tutorial2/test_FairTutorialDet2Geo.cxx, tests/examples/simulation/Tutorial4/CMakeLists.txt, tests/examples/simulation/Tutorial4/test_FairTutorialDet4Geo.cxx, tests/geobase/CMakeLists.txt, tests/geobase/checks_FairGeoSet.h
Add unit tests for classes derived from FairGeoSet. This is the first step to restructure these classes.  
Checklist:
=> Add unit tests

examples/common/passive/FairCave.cxx, fairroot/base/sim/FairModule.h, fairroot/geobase/FairGeoLoader.h, templates/project_root_containers/passive/MyCave.cxx, templates/project_stl_containers/passive/MyCave.cxx
... and use it around
@fuhlig1: you looked a lot at GeoSets lately. Can you have a look at this? Especially it's only used in ASCII related contexts, so maybe it should be called `PrepareASCIIGeoSet`?
Also I am not really sure on how to write tests for this.
---
Checklist:
=> refactor(Base): Introduce FairGeoLoader::LoadAndCreate

examples/MQ/pixelDetector/src/devices/FairMQPixelSampler.h, examples/MQ/pixelDetector/src/devices/FairMQPixelSamplerBin.h, examples/MQ/pixelSimSplit/src/devices/FairMQPrimaryGeneratorDevice.h, examples/advanced/Tutorial3/MQ/processor.cxx, examples/advanced/Tutorial3/MQ/sampler.cxx, fairroot/basemq/devices/FairMQLmdSampler.h, fairroot/basemq/devices/FairMQUnpacker.h, fairroot/parmq/ParameterMQServer.h
=> chore: Use override in FairMQ device derived classes

examples/MQ/pixelAlternative/src/PixelAltDigiWriteToRootVector.cxx, examples/MQ/pixelAlternative/src/PixelAltDigiWriteToRootVector.h, examples/MQ/pixelDetector/src/PixelDigiWriteToFile.cxx, examples/MQ/pixelDetector/src/PixelDigiWriteToFile.h, examples/advanced/Tutorial3/MQ/processorTask/MQRecoTask.h, examples/simulation/Tutorial2/src/FairTutorialDet2Digitizer.cxx, fairroot/base/event/FairEventBuilderManager.cxx, fairroot/base/sim/FairMCApplication.cxx
* refactor(examples): Drop empty Reset methods
* refactor: Remove unneeded FairRootManager references
---
Checklist:
=> refactor: Drop unneeded FRM references and empty methods

tests/geobase/tests_FairGeoSet.cxx, tests/geobase/tests_FairGeoShapes.cxx
And simplify string initialization
---
Checklist:
=> refactor(tests/geobase): Use valued variables 

CMakeLists.txt
Fix CMake error reported @ https://github.com/FairRootGroup/FairRoot/pull/1586#issuecomment-2293737064
=> build: Adopt all CMake policies up to 3.30

.github/workflows/stale.yml
Also let the bot post a message about what it is doing.
=> feat(workflow): Add stale comment messages
