base/sim/FairMCApplication.cxx
base/sim/FairMCApplication.h
base/sim/FairVolume.cxx
base/sim/FairVolume.h

Replace TRefArray and its iterators for detectors in simulation with std::list to git rid of the dynamic_cast.
This improve the performance by 3-4% when running Tutorial3.

Replace TRefArray and its iterators with std::list

---

base/source/FairFileSource.cxx
base/source/FairFileSource.h
base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

Problem:
the BranchList contains only the branch names of the branches registered in this run (e.g. all digi branches) but not any longer the branch names of the input file (e.g. sim branches). This causes massive problems with the usage of FairLinks because the method FairRootManager::GetBranchId(BranchName) returns in most cases -1 which breaks the links.
Solution:
The branchlist is now removed from the FairFileSource and exist only in the IO manager. The FileSource add its branches to the same list in the IO manager.
This problem was introduced as we separated the file source functionality from the IO Manager

Issue#124 

---

base/event/FairMultiLinkedData.cxx
base/event/FairMultiLinkedData.h
base/event/FairMultiLinkedData_Interface.cxx
base/event/FairMultiLinkedData_Interface.h
base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

Storage of FairLinks is now handled via a simple FairMultiLinkedData*. Root takes care to store the pointer if it is filled.
The usage of TRef did not work.

Change of FairLinks to run with Pointers

---

CMakeLists.txt

Set cmake-policy to new for clang compiler and rpath on MAC OS

---

base/source/FairLmdSource.cxx
base/source/FairLmdSource.h
base/source/FairMbsSource.h
base/source/swaplw.c
base/steer/FairRunOnline.cxx

Adopt to new version of ROOT Java Script
introduced parameter in virtual function ReadEvent
bugfix: cast from pointer to integer of different type
ignore return value of event-header unpacker
set RunID in the event header
proper number of double-words in a sub-event

Fixes to source / online classes

---

base/MQ/devices/FairMQSampler.tpl
fairmq/FairMQDevice.cxx
fairmq/nanomsg/FairMQSocketNN.cxx
fairmq/zeromq/FairMQContextZMQ.cxx
fairmq/zeromq/FairMQSocketZMQ.cxx

FairMQSampler: Modified: comment out an unused loop.
FairMQ: Modified: increase maximum number of ZeroMQ sockets (from default 1024).
FairMQ: Modified: reduce amount of output when finding port from a range.
FairMQ: Modified: stop the Device when socket creation fails and output an error.

Increase maximum number of zeromq sockets and improve output on errors.

---

eventdisplay/FairBoxSetDraw.cxx

Fixing a bug in FairBoxSetDraw which prevented the possibility to set the size of the boxes

Change of box size in FairBoxSetDraw

---

fairmq/CMakeLists.txt
fairmq/FairMQDevice.cxx
fairmq/FairMQStateMachine.cxx
fairmq/FairMQStateMachine.h

- add helper method `bool WaitForEndOfStateForMs(state, durationInMs)`:
waits for the end of `state` for `durationInMs` milliseconds,
returns `true` if the state ended and `false` if it didn't.
- A little cleanup of the state machine code.

FairMQStateMachine: add helper method to wait for the end of a state with a timeout

---

README.md
example/Tutorial7/CMakeLists.txt
example/Tutorial7/run/FairTestDetector/runSamplerBinT7b.cxx
example/Tutorial7/run/FairTestDetector/runSamplerBoostT7b.cxx
example/Tutorial7/run/runSamplerBinT7.cxx
example/Tutorial7/run/runSamplerBoostT7.cxx
example/Tutorial7/run/runSamplerRootT7.cxx

- remove manual Ttree loading in executable needed by Ubuntu v>11.0 and handle the issue in CMakeLists of tutorial 7
- correct a typo in Readme.md of the FairRoot installation

Correct a typo and handle an issue in tutorial7 specific to Ubuntu

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h
base/steer/FairTSBufferFunctional.cxx
base/steer/FairTSBufferFunctional.h

Modified FairTSBufferFunctional and FairRootManager to terminate the time based readout of data by setting a "Terminate" flag in the FairTSBufferFunctional

Added possibility to terminate timebased run

---

cmake/modules/ROOTMacros.cmake
example/Tutorial1/macros/CMakeLists.txt
example/Tutorial2/macros/CMakeLists.txt
example/Tutorial3/macro/CMakeLists.txt
example/Tutorial4/macros/CMakeLists.txt
example/Tutorial6/macros/CMakeLists.txt
example/rutherford/macros/CMakeLists.txt

Hello,
I try to install FairRoot on fc22, gcc-5.1.1, FairSoft(mar15p2) and I didn't succeed to install the standard version ("master" version), as it comes from FairRoot repository (git clone https://github.com/FairRootGroup/FairRoot.git). It crashes with the following error:
-------------------------------------------------------------------------------------------------------------------------------
In file included from  Path_to_FairRoot/source/example/Tutorial3/data/FairTestDetectorDigi.h:25:0,
from Path_to_FairRoot/source/example/Tutorial3/data/FairTestDetectorPayload.h:19,
from Path_to_FairRoot/build/example/Tutorial3/G__FairTestDetectorDict.h:41,
from Path_to_FairRoot/build/example/Tutorial3/G__FairTestDetectorDict.cxx:17:
/usr/include/c++/5.1.1/sstream:335:7: error: ‘struct …

request for ROOTMacros.cmake update - after unsuccessfully install of "master" version

---

fairmq/logger/CMakeLists.txt
fairmq/logger/fairroot_null_deleter.h
fairmq/logger/logger_oldboost_version.cxx

add an other fairmq logger implementation in case boost version < 1.56 for backward compability

Fix backward compability issue in the fairmq logger

---

base/event/FairMultiLinkedData_Interface.cxx

Add additional check if FairRootManager is present before a new FairMultiLinkedData object is created

Fix crash if interface is called without FairRootManager

---

cmake/modules/FindFairRoot.cmake

If REQUIRED is not set we must not throw a fatal error.

 Use the "required" flag in FindFairRoot.cmake

---

base/steer/FairTask.cxx
base/steer/FairTask.h

Add a map and two functions which allow to define from the macro if a branch with a given name should be written to the output file.
In classes derived from FairTask the functions can be used to decide if the branch should be persistent or not and be registered accordingly.
Implements redmine feature request #107.

Add functionality which allows to swich persistency from the macro.

---

base/steer/FairRootManager.h
base/steer/FairRunOnline.h

Reimplement GetSource in FairRunOnline. This function is needed by the CBM experiment and was probably removed when moving the source from FairRunOnline to FairRootManager.

Reimplement missing function.

---

fairmq/FairMQChannel.cxx
fairmq/FairMQChannel.h
fairmq/test/runTransferTimeoutTest.cxx

This will fix the occasional fail of the tests, caused by the reconnections necessary when setting timeout values via zeromq. Now the timeouts can be set directly on the Send/receive calls of FairMQChannel.

Simplify handling of send/receive timeouts

---

base/event/FairEventBuilder.h
base/event/FairLink.cxx
base/event/FairLink.h
base/event/FairMultiLinkedData.cxx
base/event/FairMultiLinkedData.h
base/event/FairMultiLinkedData_Interface.cxx
base/event/FairMultiLinkedData_Interface.h
base/event/FairTimeStamp.cxx
base/event/FairTimeStamp.h
base/sim/FairModule.cxx
base/source/FairMbsStreamSource.cxx
base/source/FairMbsStreamSource.h
base/source/FairMixedSource.cxx
base/source/FairRemoteSource.cxx
base/source/FairRemoteSource.h
base/steer/FairAnaSelector.h
base/steer/FairRunAnaProof.cxx
datamatch/FairMCEntry.h
datamatch/FairMCMatch.cxx
datamatch/FairMCMatch.h
datamatch/FairMCMatchLoaderTask.cxx
datamatch/FairMCObject.h
datamatch/FairMCResult.h
datamatch/FairMCStage.cxx
datamatch/FairMCStage.h

Rename Print() function in FairLinks, FairTimeStamp, FairMultilinkedData_Interface and FairMultilinkedData .

Fix warnings in base and datamatch directories.

---

FairBase_test.cmake
cmake/modules/CheckCompiler.cmake
cmake/modules/ROOTMacros.cmake
cmake/scripts/generate_dictionary_root.sh.in

Switch on Wall and Wextra compiler warnings when running build type 'Nightly' or 'Profile' on Mac OSX.
Allow to switch on ctest_launchers for compilation. In this case the output of each compilation unit is send as one packet
to the cdash server even if one uses a parallel build. The cdash server then show all data together and not mixed in one
long list.
Don't run rootcint directly when generating the dictionary. Instead create a shell script when running cmake which is
executed to generate the dictionary. This two step procedure is needed because with cteat_launchers the needed environment
variables are not present when generating the dictionary but only when running cmake.
Switch to alternative CDash server (lxwww53) when building with ctest_launchers.
When the environment varibale …

Change compiler flags. Allow to use ctest launchers.

---

fairmq/devices/FairMQBenchmarkSampler.cxx
fairmq/devices/FairMQBenchmarkSampler.h
fairmq/devices/FairMQSink.cxx
fairmq/devices/FairMQSink.h
fairmq/run/runBenchmarkSampler.cxx
fairmq/run/runSink.cxx
fairmq/run/startBenchmark.sh.in

- Allow to limit the number of messages to for the FairMQBenchmarkSampler and FairMQSink with `--num-msgs` cmd option
- Add a timer to the FairMQBenchmarkSampler and FairMQSink to measure the duration of the sending/receiving process.

Allow to limit number of messages for the Benchmark sampler and sink

---

base/source/FairFileSource.cxx

Bug in event time: Add a check for the event time so that it will not be set twice for the same entry
https://fairroot-redmine.gsi.de/issues/65

Redmine issue #65

---

base/sim/FairMCApplication.cxx
base/sim/FairMCApplication.h

Add a call to InitParContainers of the modules. This is needed to read parameters to modify the ideal geometry.
Also call the ModifyGeometry function of the modules. In the module specific implementation of the function the
modifications to the ideal geometry can be defined. It is possible to use parameters from a parameter container.
At the end of the simulation the geometry is reverted back to the ideal geometry which is then saved in the
parameter file.

Implement the possibility to modify the ideal geometry for simulation.

---

fairmq/FairMQChannel.cxx
fairmq/FairMQDevice.cxx
fairmq/FairMQTransportFactory.h
fairmq/nanomsg/FairMQSocketNN.cxx
fairmq/nanomsg/FairMQSocketNN.h
fairmq/nanomsg/FairMQTransportFactoryNN.cxx
fairmq/nanomsg/FairMQTransportFactoryNN.h
fairmq/test/req-rep/FairMQTestRep.cxx
fairmq/test/req-rep/FairMQTestReq.cxx
fairmq/test/req-rep/runTestRep.cxx
fairmq/test/req-rep/runTestReq.cxx
fairmq/test/test-fairmq-req-rep.sh.in
fairmq/zeromq/FairMQSocketZMQ.cxx
fairmq/zeromq/FairMQSocketZMQ.h
fairmq/zeromq/FairMQTransportFactoryZMQ.cxx
fairmq/zeromq/FairMQTransportFactoryZMQ.h

For request sockets in ZeroMQ the socket identity must be unique, otherwise multiple clients will be rejected.
Update the tests to check this use case.

Bugfix: Include device ID in the zeromq socket identity.

---

examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkMsgpack.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskBin.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskFlatBuffers.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskMsgpack.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskProtobuf.tpl
examples/advanced/Tutorial3/MQ/samplerTask/FairTestDetectorDigiLoaderBin.tpl
examples/advanced/Tutorial3/MQ/samplerTask/FairTestDetectorDigiLoaderMsgpack.tpl
examples/advanced/Tutorial3/MQ/samplerTask/FairTestDetectorDigiLoaderProtobuf.tpl

Some serialization methods skipped unused class member, which produced slightly unfair comparison.
Now fixed.

Update Tutorial 3 to include unused members in the transfer

---

examples/advanced/GoTutorial/README.md
examples/advanced/GoTutorial/go-processor/README.md
examples/advanced/GoTutorial/go-processor/main.go
examples/advanced/GoTutorial/go-sink/README.md
examples/advanced/GoTutorial/go-sink/main.go
examples/advanced/README.md

This CL adds basic examples showing how one can write devices in Go
and integrate them into an already existing topology of C++ devices.
Fixes #310.

examples/advanced: add Go-based examples

---

examples/MQ/9-PixelDetector/src/Pixel.cxx
examples/simulation/Tutorial1/src/FairTutorialDet1.cxx
examples/simulation/Tutorial2/src/FairTutorialDet2.cxx
examples/simulation/rutherford/src/FairRutherford.cxx

By accident the call was removed with one of the last commits which results in a situation where no MCPoints are created for affected detectors.

Call FairDetector::Initialize() again in derrived classes.

---

examples/MQ/9-PixelDetector/macros/run_tracks.C
examples/MQ/9-PixelDetector/run/scripts/startFairMQEx9New.sh.in
examples/MQ/9-PixelDetector/run/scripts/startFairMQEx9_2Levels.sh.in
examples/MQ/9-PixelDetector/run/scripts/startFairMQEx9_3Levels.sh.in

Using the same scheme when setting output class and branch names in MQ shell scripts.
Added another macro to reconstruct tracks from hits.

Some fixes in the MQ/9-PixelDetector

---

CMakeLists.txt
base/MQ/CMakeLists.txt
examples/MQ/9-PixelDetector/src/CMakeLists.txt
examples/MQ/GenericDevices/CMakeLists.txt
examples/MQ/LmdSampler/CMakeLists.txt
examples/advanced/Tutorial3/CMakeLists.txt
fairmq/CMakeLists.txt
fairmq/logger/CMakeLists.txt
parmq/CMakeLists.txt

Use the vairables filled by FindBoost instead explicit names in the CMakefile.txt(s)

Use Variables for Boost libraries instead of explicit names

---

examples/MQ/serialization/src/1-simple/devices/GenExPart1Processor.h
examples/MQ/serialization/src/1-simple/devices/GenExPart1Sampler.h
examples/MQ/serialization/src/1-simple/devices/GenExPart1Sink.h
examples/MQ/serialization/src/2-multi-part/devices/Ex2Processor.h
examples/MQ/serialization/src/2-multi-part/devices/Ex2Sampler.h
examples/MQ/serialization/src/2-multi-part/devices/Ex2Sink.h
examples/MQ/serialization/src/2-multi-part/devices/SerializerExample2.h
fairmq/FairMQChannel.h
fairmq/FairMQDevice.h
fairmq/FairMQParts.h
fairmq/FairMQSocket.h
fairmq/nanomsg/FairMQSocketNN.cxx
fairmq/nanomsg/FairMQSocketNN.h
fairmq/zeromq/FairMQSocketZMQ.cxx
fairmq/zeromq/FairMQSocketZMQ.h

- Update FairMQParts with doxygen comments and non-blocking send.
- Fix dereference before null check in serialization example (fTree in sinks destructors) and formatting.

Update FairMQParts with doxygen comments and non-blocking send

---

fairtools/FairLogger.cxx
fairtools/FairLogger.h

Add explicit return value to function IsLogNeeded when log level is FATAL.
Add new function GetFATALOutputStream which is used for FATAL log messages.
Extent LOG macro to use the new function when the log level is FATAL.
Mark the new function as Coverity kill function which signals Coverity that
the function will terminate the execution.

Solve coverity issues with LOG(FATAL) macro.

---

base/sim/FairMCApplication.cxx
base/source/FairFileSource.cxx
base/source/FairMixedSource.cxx
base/steer/FairRootManager.cxx
base/steer/FairRootManager.h
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
base/steer/FairRunOnline.cxx

Read name of the output tree from VMCWORKDIR/gconfig/rootmanager.dat. Default name is cbmsim.

Possibility to set output tree name.

---

README.md
base/steer/FairRootManager.cxx

Fix coverity issue 98828. Look for rootmanager.dat inside VMCWORKDIR/config. Add instructions on how to change treename to main README.

Coverity issue and treename in README.

---

fairmq/options/FairMQParser.cxx
fairmq/options/FairMQProgOptions.cxx

Previous fix did not work if the logger was not used before configuration, because it is initialized on first use. This makes sure this doesn't happen.

Logger fix

---

examples/MQ/9-PixelDetector/README.md
examples/MQ/9-PixelDetector/run/CMakeLists.txt
examples/MQ/9-PixelDetector/run/ddsEx9FileSink.cxx
examples/MQ/9-PixelDetector/run/ddsEx9Sampler.cxx
examples/MQ/9-PixelDetector/run/ddsEx9TaskProcessor.cxx
examples/MQ/9-PixelDetector/run/ddsParameterMQServer.cxx
examples/MQ/9-PixelDetector/run/options/ex9-dds.json
examples/MQ/9-PixelDetector/run/scripts/ex9-dds-topology.xml
examples/MQ/9-PixelDetector/src/devices/FairMQEx9FileSink.cxx
examples/MQ/9-PixelDetector/src/devices/FairMQEx9FileSink.h
examples/MQ/9-PixelDetector/src/devices/FairMQEx9Sampler.cxx
examples/MQ/9-PixelDetector/src/devices/FairMQEx9Sampler.h
examples/MQ/9-PixelDetector/src/devices/FairMQEx9TaskProcessor.h
examples/MQ/9-PixelDetector/src/devices/FairMQEx9TaskProcessor.tpl
parmq/ParameterMQServer.cxx
parmq/ParameterMQServer.h

- ddsEx9Sampler.cxx, ddsEx9TaskProcessor.cxx, ddsEx9FileSink.cxx, ddsParameterMQServer.cxx - executables sources;
- FairMQEx9Sampler, FairMQEx9TaskProcessor, FairMQEx9FileSink, ParameterMQServer - added channel names setters;
- ex9-dds.json - config for the example to run on DDS;
- ex9-dds-topology.xml - topology (sampler-3processors-sink+parameterServer) to run on the DDS;
- updated the README file.

MQ/Example9 - added topology and executables to run in DDS.

---

base/source/FairFileSource.h
base/source/FairMbsStreamSource.cxx
base/source/FairMbsStreamSource.h
base/source/FairMixedSource.h
base/source/FairOnlineSource.cxx
base/source/FairOnlineSource.h
base/source/FairRemoteSource.cxx
base/source/FairRemoteSource.h
base/source/FairSource.cxx
base/source/FairSource.h
base/source/FairUnpack.h
base/steer/FairRun.cxx
base/steer/FairRun.h
base/steer/FairRunAna.cxx
base/steer/FairRunAna.h
base/steer/FairRunOnline.cxx
base/steer/FairRunOnline.h
cmake/modules/CheckCompiler.cmake

Add possibility to skip writing an event to tree.
Move SetParContainers for unpackers to base FairSource class. Avoid dynamic cast in FairRunOnline.
Set the run ID using source.
Fix linking error with Xcode 7.3.
Add ReInit to the Unpacker class. Call ReInitUnpackers from FairRunOnline.

Changes in FairRunOnline needed by CBM.

---

examples/MQ/9-PixelDetector/src/devices/FairMQEx9FileSink.cxx
fairmq/FairMQDevice.cxx
fairmq/FairMQStateMachine.h
fairmq/devices/FairMQBenchmarkSampler.h
fairmq/devices/FairMQMerger.cxx
fairmq/devices/FairMQMerger.h
fairmq/devices/FairMQProxy.cxx
fairmq/devices/FairMQProxy.h
fairmq/devices/FairMQSplitter.cxx
fairmq/devices/FairMQSplitter.h
fairmq/run/runMerger.cxx
fairmq/run/runProxy.cxx
fairmq/run/runSplitter.cxx
fairmq/tools/runSimpleMQStateMachine.h

- Gracefully end the device also in the termination case with all the necessary state transitions (instead of abort).
- Handle both single and multi part payloads in splitter/merger/proxy (only affects nanomsg).
- example 9: close the file in the destructor instead of in the Run(). This will now always work because of the first change.

Proper cleanup on termination and let splitter/merger/proxy handle both single and multipart payloads.

---

fairmq/test/pub-sub/runTestPub.cxx
fairmq/test/pub-sub/runTestSub.cxx
fairmq/test/push-pull/runTestPull.cxx
fairmq/test/push-pull/runTestPush.cxx
fairmq/test/req-rep/runTestRep.cxx
fairmq/test/req-rep/runTestReq.cxx
fairmq/test/runTransferTimeoutTest.cxx

Use different ports for ZeroMQ/nanomsg tests (The recently introduced FairMQ/nanomsg tests used same ports as the ZeroMQ test, which leads to test failures when both are running in parallel).

Use different ports in tests to prevent parallel run fail

---

.travis.yml

brew update the gcc version from 5.3 to 6.1. This conflicts with our fairsoft package which was compiled using gcc 5.3.
Install gcc 5.3 for Travis tests.

Update Travis configuration.

---

fairmq/test/pub-sub/runTestPub.cxx
fairmq/test/pub-sub/runTestSub.cxx
fairmq/test/push-pull/runTestPull.cxx
fairmq/test/push-pull/runTestPush.cxx
fairmq/test/req-rep/runTestRep.cxx
fairmq/test/req-rep/runTestReq.cxx
fairmq/test/runTransferTimeoutTest.cxx

Recent update of the FairMQ tests to include nanomsg transport has introduced a silly bug which caused tests to fail when they were running at the same time. This corrects it.

Fix parallel running FairMQ tests failure

---

cmake/modules/FindGo.cmake
examples/advanced/GoTutorial/CMakeLists.txt

Go examples are build when calling cmake but the install will copy the binary to the install_dir/bin correctly now, this solves the issue #393 by reported by @ktf

solve issue #393 with installation of go examples

---

cmake/modules/FindFairRoot.cmake

This should be the last of the longstanding issue due to boost having
different "-mt" extension policy on different systems.

Avoid hardcoded boost library names

---

test/fairtools/_GTestFairTools.cxx
test/mock/CMakeLists.txt
test/mock/FairMockMCApplication.cxx
test/mock/FairMockVirtualMC.h
test/testlib/CMakeLists.txt

Use new output capture class in FairLogger tests to overcome linking problem
when using old fairsoft versions.
Add return statements to all functions of mock class.
Cleanup destructor of mock class.
Correct build system to work with ROOT6.

Fix unit tests.

---

base/sim/FairBaseParSet.cxx

fpriGen and fDetList are deleted in FairRunSim where they are created. Only the container list should be deleted in the dtor of FairBaseParSet

Clean the dtor of FairBaseParSet, and solve the problem of double delete

---

fairtools/FairLogger.cxx
fairtools/FairLogger.h

Properly handle c++ stream manipulators for file output.
In case of FATAL error use exit intead of abort.
Clean the code.

Changes in FairLogger.

---

.travis.yml

Travis changed the default osx image from 10.9 to 10.11 which breaks our compilations.
All out FairSoft software stack was build for OSX 10.9.

Use correct osx image.

---

examples/MQ/8-multipart/ex8-multipart.json
fairmq/FairMQChannel.cxx
fairmq/FairMQChannel.h
fairmq/FairMQDevice.cxx
fairmq/FairMQDevice.h
fairmq/FairMQSocket.cxx
fairmq/FairMQSocket.h

Hi, this contains the feature we discussed about - attaching many endpoints to a socket, specified with a list of addresses, optionally with specifiers to overrid default bind/connect method. See the commit for more documentation.

Multiple endpoints per socket

---

fairmq/FairMQStateMachine.cxx
fairmq/FairMQStateMachine.h

- Fix regression from last commit (preventing static run from proper shutdown).
- Guard state changes (for the internal transitions) (msm::process_event is not thread safe).
- Remove unused transition from RUNNING to EXITING.

State machine update

---

base/event/FairMultiLinkedData_Interface.cxx

Propagate reference toCopy from FairMultiLinkedData_Interface copy constructor to TObject

Fix copy constructor of FairMultiLinkedData_Interface

---

base/steer/FairRunAna.cxx
base/steer/FairRunOnline.cxx

- Clear volumes and shapes before deleting gGeoManager. "delete run;" has to be called at the end of macro.

Fix crash when calling TGeoManager destructor in FairRunAna and FairRunOnline

---

fairmq/FairMQDevice.cxx

Avoid setting channel values for kernel buffer sizes on the socket if they are default to avoid conflict with changed zmq defaults (0 -> -1, somewhere between version 4.1.3 and 4.2.1).

Fix compatibility with ZeroMQ 4.2.1

---

fairmq/test/pub-sub/runTestPub.cxx
fairmq/test/pub-sub/runTestSub.cxx
fairmq/test/push-pull/runTestPull.cxx
fairmq/test/push-pull/runTestPush.cxx
fairmq/test/req-rep/runTestRep.cxx
fairmq/test/req-rep/runTestReq.cxx
fairmq/test/runTransferTimeoutTest.cxx

nanomsg does not implement the LINGER option that gives the socket some time to finish transfers during shutdown. Adjust nanomsg tests to provide this timeout manually.

Fix nanomsg tests

---

fairmq/FairMQDevice.h

So far devices inheriting from FairMQDevice needed to access the `fConfig` variable.
This is bad encapsulation and might be in conflict with coding conventions.
This simple getter is an evident improvement.

Better encapsulate Device config: Offer a getter method

---

generators/FairBoxGenerator.cxx
generators/FairBoxGenerator.h

For my/our (R3BRoot) use cases it is common to give the primary particle kinetic energy instead of the momentum.
Here is a possible solution using the particle mass to convert the given energy range to a momentum range during initialization. This way, ReadEvent can remain unchanged.

Added SetEkinRange to FairBoxGenerator

---

base/CMakeLists.txt
base/sim/FairGenericRootManager.cxx
base/sim/FairGenericRootManager.h
base/sim/FairGenericStack.cxx
base/sim/FairMCApplication.cxx
base/sim/FairMCApplication.h
base/sim/FairRootManagerSim.cxx
base/sim/FairRootManagerSim.h
base/sim/FairRootManagerSimMT.cxx
base/sim/FairRootManagerSimMT.h
base/steer/FairRootManager.cxx
base/steer/FairRun.cxx
base/steer/FairRun.h
base/steer/FairRunAnaProof.cxx
base/steer/FairRunSim.cxx

- Added new RootManager classes which allow to use ROOT IO with
Geant4 multi-threading, according to the implementation in geant4_vmc/mtroot:
FairRootGenericManager, FairRootManagerSim, FairRootManagerSimMT
which use the FairRootManager methods implementation
- Updated the following classes for multi-threading:
FairGenericStack, FairMCApplication
- Not yet migrated data:
FairMCApplication::fRunInfo
FairMCApplication::fFairTaskList, fRadGridMan - are these used in O2?
- Left problems - see "TO DO"

Migration of simulation code to multi-threading:

---

fairmq/CMakeLists.txt
fairmq/options/FairMQParser.cxx
fairmq/options/FairMQParser.h
fairmq/options/FairMQProgOptions.cxx
fairmq/options/FairMQSuboptParser.cxx
fairmq/options/FairMQSuboptParser.h

This allows to configure FairMQDevice channels via a simple command line syntax like
```
--channel-config name=output,type=push,method=bind
```
It's an alternative to `--mq-config` or `--config-json-string`
@rbx please have a look if that can be merged without creating any side effect.

Adding FairMQ channel property parser implementation for key-value subopt format

---

base/event/FairMultiLinkedData_Interface.cxx
base/event/FairMultiLinkedData_Interface.h
base/event/FairTimeStamp.cxx
base/event/FairTimeStamp.h

* this commit offers the compiler the chance to inline
and optimize construction for very important data objects
(FairTimeStamp, MultiLink_Interface)
* objects of this kind are potentially created billions of times and should be done
as fast as possible

Offer important data constructors inline

---

CMakeLists.txt

* compiling the examples takes very long
* this gives a user the possibility to switch this part off
* by default nothing changes and the cmake process is backward compatible

CMake option to build examples or not

---

cmake/modules/FindZeroMQ.cmake

The deprecation warnings made it into the `17.03` release. So, I guess, we can remove the deprecated behaviour now from `dev`. (AliceO2 has already adapted)

remove deprecated behaviour

---

base/event/FairLink.cxx
base/event/FairLink.h
datamatch/FairMCDataCrawler.cxx

* reduce memory footprint for FairLinks by removing
inheritance from TObject (which is not needed)
* remove virtual keyword from operators
* overall this will gain 24bytes per FairLink
* other smaller improvements: default destructor, inline trivial constructors

Make FairLink not inherit from TObject

---

base/event/FairLink.cxx
base/event/FairLink.h

Reducing the size of FairLink down to 15 byte.
This limits the number of file links down to 254 and for types to 65534.
At the moment I do not check if values larger than that are given due to performance concerns.

Reduce size of FairLink to 15 byte

---

base/sim/FairMCApplication.cxx

* This seemingly cosmetic change saves a lot of CPU
time because ROOT triggered a lot of internal TClass generation stuff
* It is also not needed since the dynamic cast does the same job

Avoid InheritsFrom function from ROOT

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

This is a cosmetic change, which avoids reference to cbm and enhances
code browsing because the names now refer to what they represent (folders).
Relates to issue #541 (but does not yet change anything for the user).

Improve naming of private FairRootManager variables

---

fairmq/test/CMakeLists.txt

Should fix `build/O2/o2-dev-fairroot` check in AliceO2Group/AliceO2#370.

add missing link dependency

---

examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSink.h
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTask.h
examples/advanced/Tutorial3/MQ/samplerTask/FairTestDetectorDigiLoader.h
fairmq/CMakeLists.txt
fairmq/FairMQDevice.cxx
fairmq/Tools.h
fairmq/tools/CppSTL.h
fairmq/tools/FairMQTools.h
fairmq/tools/Network.h
fairmq/tools/README.md

* Split header, add common header
* Transform to canonical namespace
* Deprecate old header
* Adapt to new Tools.h
---
These changes are a example on how to move declarations to new namespaces while staying backwards compatible with a deprecated header. It also shows how to introduce convenience headers with IWYU support.

Refactor FairMQTools

---

base/steer/FairTask.cxx
base/steer/FairTask.h
examples/MQ/9-PixelDetector/src/devices/FairMQEx9TaskProcessor.tpl
examples/MQ/9-PixelDetector/src/devices/FairMQEx9TaskProcessorBin.tpl
examples/MQ/9a-PixelDetector/src/devices/FairMQEx9aTaskProcessorBin.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTask.h
examples/advanced/Tutorial3/reconstruction/FairTestDetectorRecoTask.cxx

It is set by default to kFALSE.
When running in FairMQ, it should be SetStreamProcesssing(kTRUE).
Modified:
examples/advanced/Tutorial3,
examples/MQ/9-PixelDetector,
examples/MQ/9a-PixelDetector
accordingly.

FairTask - added new member variable (fStreamProcessing).

---

fairmq/FairMQDevice.cxx
fairmq/FairMQDevice.h
fairmq/docs/Device.md
fairmq/options/FairMQProgOptions.cxx
fairmq/test/CMakeLists.txt
fairmq/test/device/TestReceiver.h
fairmq/test/device/TestSender.h
fairmq/test/device/_multiple_devices.cxx
fairmq/test/device/runner.cxx

- Create FairMQProgOptions within a device if it has been started without access to one.
- Test devices without supplied config & two in a process.

Always have access to FairMQProgOptions from device

---

fairmq/logger/logger.h

FairMQLogger: undefine DEBUG if it has been previously defined

---

base/sim/FairPrimaryGenerator.cxx
base/sim/FairPrimaryGenerator.h

- added TMCProcess. By default kPPrimary
- Propagate this parameter to the stack
Changes do not influence the existing generators.

Extend parameter list in FairPrimaryGenerator::AddTrack

---

fairmq/FairMQDevice.cxx

This avoids conflicts if some channels were created grammatically, while also using FairMQProgOptions/FairMQParser.

Merge channels from FairMQProgOptions to device, instead of replacing

---

base/sim/FairMCApplication.cxx

The FairMCApplication issued error messages about failing dynamic casts.
These were probably no real errors but occurances of FairModule instances in the list.
Modified the check accordingly.

Fix confusing message about "dynamic_cast fails"

---

cmake/modules/FindMsgpack.cmake

This commit enables the use of a MessagePack installation outside of $SIMPATH. This will be needed for aliBuild.

Add Support for externally specified MessagePack location

---

base/sim/FairMCApplication.cxx

Use the VMC volume id which corresponds to TGeoVolume::GetNumber
rather than the index in the TGeoVolume list to construct the mapping
of volumes to modules

Correct mapping of volume number to module id

---

base/sim/FairGenericRootManager.h
base/sim/FairRootManagerSim.cxx
base/sim/FairRootManagerSim.h
base/sim/FairRootManagerSimMT.cxx
base/sim/FairRootManagerSimMT.h

- Added Int_t GetBranchId(TString const &BrName) in FairGenericRootManager:
(needed in O2 TPC detector)

Added a function in FairGenericRootManager interface

---

CMakeLists.txt

This patch defaults `Boost_NO_SYSTEM_PATH` to `TRUE` only if it wasn't explicitly defined otherwise. This allows us in O2 to build FairRoot using system's boost (which is currently prevented by current FairRoot's dev).

Allow custom definition of Boost_NO_SYSTEM_PATHS

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

There where 2 identical "Register" functions which are now implemented in terms
of the same generic template function.

Factoring out of common code in FairRootManager

---

base/sim/FairMCApplication.cxx
base/source/FairFileSource.cxx
base/source/FairFileSource.h
base/source/FairSource.h
base/steer/FairRootManager.cxx
base/steer/FairRootManager.h
base/steer/FairRunAna.cxx
examples/simulation/Tutorial2/macros/create_digis.C
examples/simulation/Tutorial2/src/CMakeLists.txt
examples/simulation/Tutorial2/src/FairTutorialDet2.cxx
examples/simulation/Tutorial2/src/FairTutorialDet2.h
examples/simulation/Tutorial2/src/FairTutorialDet2CustomTask.cxx
examples/simulation/Tutorial2/src/FairTutorialDet2CustomTask.h
examples/simulation/Tutorial2/src/FairTutorialDet2Digitizer.cxx
examples/simulation/Tutorial2/src/FairTutorialDet2Digitizer.h
examples/simulation/Tutorial2/src/FairTutorialDet2Point.h
examples/simulation/Tutorial2/src/Tutorial2LinkDef.h

This commit provides a major extension to the FairRootManager, enabling
the user to register branches based on arbitrary types.
In particular, it is now possible to register stl containers as branch
entries, extending the current TObject* or TCollection* APIs.
Instant gratification:
```
// some source registering data
auto ioman = FairRootManager::Instance();
std::vector<CustomData>* data;
ioman->RegisterAny("mybranch", data, ...);
```
```
// some consumer task asking for the data
auto ioman = FairRootManager::Instance();
auto mydata = ioman->InitObjectAs<std::vector<CustomData> const*>("mybranch");
```
The example "simulation/Tutorial2" was extended accordingly showing use cases
with persistent and non-persistent branches.
The IO to ROOT trees works as before. It was checked that …

Ability to register/retrieve data of any type with IO manager

---

fairmq/EventManager.h
fairmq/StateMachine.h
fairmq/test/event_manager/_event_manager.cxx

In fact, this commit will workaround a bug with template alias compilation
from Clang 3.4 to Clang 3.8.

FairMQ: Support Apple Compiler 8.0

---

cmake/modules/FindProtobuf.cmake

* Enforce presence of `protoc` (the protobuf compiler) too
* Similar to #510 and #548

Look for protobuf on custom paths then system

---

cmake/modules/FindProtobuf.cmake

Fixes a problem where undefined variables resulted in replacing search paths as
`${SIMPATH}/lib` to `/lib`, leading to unintended behaviours. This patch also
uses _either_ `${SIMPATH}` or `${ProtoBuf_DIR}` as hint, and only if they are
found as directories, in order to avoid cross-picking protobuf components. If
none is set, everything will be obtained from system paths, consistently, as
`HINTS` will be empty.

Add paths to HINTS in FindProtobuf only if defined

---

examples/advanced/MbsTutorial/CMakeLists.txt
examples/advanced/MbsTutorial/macros/CMakeLists.txt
examples/advanced/MbsTutorial/macros/unpack_mbs.C

1. Use the relative file name for the data file as the full path can get very long with Jenkins  
2. Install the mbs tutorial  (was not in the installation!)
3. copy the data file to the build directory

use relative path for data file and add the example to the installation

---

Dart.sh
FairBase_test.cmake
Jenkinsfile

In principle this is how it could look like. What do you think?
Note: When a requested label in the build matrix is not available on any online build agent, the build job will be queued indefinitely by jenkins.
TODO

Add alfa-ci build jobs

---

base/sim/FairMCApplication.cxx
base/steer/FairRootManager.cxx

Two stability fixes:
a) proper cleanup of vmc instance (solves part of https://github.com/AliceO2Group/AliceO2/issues/640)
b) temporary removal of a line (in a singleton destructor) identified as source of a segfault.

Stability fixes

---

fairmq/FairMQDevice.cxx
fairmq/FairMQDevice.h
fairmq/options/FairMQProgOptions.cxx
fairmq/options/FairMQProgOptions.h

Devices implementing the conditional run method are typically source
devices and a rate control can be desireable. New option '--rate' with
a float number argument in Hz can be used to configure rate control.
By default it is switched off.
There has been a good fraction of identical code for the boost options description in `FairMQProgOptions` which is now in one single function.

Adding rate control for ConditionalRun function

---

fairmq/Plugin.h
fairmq/PluginServices.h
fairmq/options/FairMQProgOptions.h
fairmq/plugins/DDS/DDS.cxx
fairmq/plugins/DDS/DDS.h

The `*AsString` property subscription API, I presented last week, was not yet in the repo - here it is :)
The other two commits are enhancements to the DDS plugin and needed for the O2 DDS workflow executor I showed. Even though, this is not likely to be used as a production implementation (heartbeats won't scale, waiting on FairRootGroup/DDS#180), @rbx and I thought we should still merge it for now and improve it later.

Offline week follow up

---

base/steer/FairRunSim.cxx
base/steer/FairRunSim.h

Allow for the possibility to setup the simulation
without interpreting macros at runtime;
The user can now simply register a hook which is supposed
to call into compiled library code that sets up the simulation
The change is fully backward compatible and the hook
is not used by default

Allow simulation setup via compiled library hook

---

base/sim/FairMCApplication.h

This allows to inherit from FairMCApplication and access
the data members directly (as not accessible through getters).

Make members of FairMCApplication protected

---

base/sim/FairGenericStack.h
base/sim/FairMCApplication.cxx

- Added FairGenericStack::FinishPrimary() function and it call
in FairMCApplication (to allow a clean-up in ALICE use case)
- Removed obsolete code prforming an sxplicit registration of stack
in MT mode

Updated FairGenericStack interface and clean-up:

---

CMakeLists.txt
fairmq/CMakeLists.txt

Hi, 
(not so sure the PR should be made to master, I'm a bit unclear on how to work with the alisw/FairRoot vs this repo...)
After a long and painful debugging session on my Mac which was refusing to build FairRoot (using alibuild or using "direct" cmake) (tag alice-dev-20171027)...
```
> aliBuild --defaults o2 build FairRoot
...snip...
[ 63%] Building CXX object fairmq/test/CMakeFiles/testsuite_FairMQ.PluginServices.dir/plugin_services/runner.cxx.o
[ 63%] Building CXX object fairmq/test/CMakeFiles/testsuite_FairMQ.StateMachine.dir/state_machine/_state_machine.cxx.o
[ 63%] Building CXX object fairmq/test/CMakeFiles/testsuite_FairMQ.PluginServices.dir/plugin_services/_config.cxx.o
[ 63%] Linking CXX shared library ../../../lib/libFairMQPlugin_dds.dylib
ld: file not found: …
```

Missing explicit reference to lib boost_signals

---

CMakeLists.txt

Recently added `CACHE` keyword to the setting of custom `FAIRROOT_VERSION` variable was causing all but first cmake runs to fail, because the `project` command also sets `<project name>_VERSION`.
With the `CACHE` keyword, second cmake run evaluated `project` first, set version to empty string and did not update it later because of the way `SET` with `CACHE` keyword work.
This fixes it and sets version via `project`.

Set FAIRROOT_VERSION in the project command & remove CACHE from manual version set

---

fairmq/test/protocols/_push_pull_multipart.cxx

In some cases the tests are run in a working dir where `test` directory exists, thus ipc is unable to create its file with the same name (e.g.: https://cdash.gsi.de/viewTest.php?onlyfailed&buildid=168870).
Give it a more unique name for the tests.

Fix occasionally failing ipc tests due to existing file

---

Jenkinsfile

remove cmake --version call from jenkins file as it is called before setting the enviroment from Dart.cfg which could stop the build if cmake was not installed in the system but in our packages

remove "cmake --version" call from Jenkins file 

---

fairmq/options/FairMQProgOptions.cxx
fairmq/options/FairProgOptions.cxx
fairmq/options/FairProgOptions.h
fairmq/plugins/Control.cxx
fairmq/shmem/FairMQSocketSHM.cxx
fairmq/shmem/FairMQTransportFactorySHM.cxx
fairmq/test/message_resize/_message_resize.cxx
fairmq/test/protocols/_push_pull_multipart.cxx

- FairMQProgOptions: initialize defaults in the constructor, not in ParseAll.
- shmem: Fix missing session name resize if running without FairMQProgOptions.
- Fix reorder warnings.

FairMQProgOptions: initialize defaults in the constructor

---

parbase/FairContFact.cxx
parbase/FairRuntimeDb.cxx
parbase/FairRuntimeDb.h

Hi @MohammadAlTurany
With new ROOT/v6-12-04 we get double delete on root exit cleanup due to the FairRoot static  FairContFact mechanism:
``root -l -x -b -q /home/shahoian/alice/sw/BUILD/FairRoot-latest/FairRoot/lib/libTrkBase.so
Processing /home/shahoian/alice/sw/BUILD/FairRoot-latest/FairRoot/lib/libTrkBase.so...
Error in <TList::Clear>: A list is accessing an object (0x7f17821558a0) already deleted (list name = TList)
``
The reason is that different static FairContFact-derived objects (e.g. ````FairRoot/base/sim/FairBaseContFact.cxx:static FairBaseContFact gFairBaseContFact````) register themselves in the ````static TList contFactories```` defined in ````FairRuntimeDb.h```` via their base FairContFact constructor. On exit from root these static FairContFact objects are deleted once as …

~FairContFact must remove itself from contFactories list to avoid double deletion

---

fairmq/FairMQDevice.cxx
fairmq/options/FairMQParser.cxx
fairmq/options/FairMQParser.h
fairmq/options/FairMQProgOptions.cxx
fairmq/options/FairMQProgOptions.h
fairmq/options/FairMQSuboptParser.cxx
fairmq/options/FairMQSuboptParser.h
fairmq/options/FairProgOptions.cxx
fairmq/options/FairProgOptions.h
fairmq/options/FairProgOptionsHelper.h
fairmq/options/ProgOptionTest/run/testMQoptions2.cxx
fairmq/run/startMQBenchmark.sh.in

- Remove singular key names from JSON schema.
- Align the property tree created by `FairMQSuboptParser` with the format required by the main parser (plural names).
- Fix `--print-options` to print all options (not only those that have their value set).
- remove XML parser (outdated and unused).
- various code cleanup.

FairMQProgOptions fixes and cleanup

---

fairmq/FairMQDevice.cxx
fairmq/options/FairMQProgOptions.cxx
fairmq/shmem/FairMQTransportFactorySHM.cxx
fairmq/shmem/FairMQTransportFactorySHM.h
fairmq/shmem/Monitor.cxx
fairmq/shmem/Monitor.h
fairmq/shmem/runMonitor.cxx

- add `--clean-on-exit`.
- Use boost::process to optionally autostart the monitor.
- Add monitor command to see a list of devices that use shared memory.

shmmonitor update

---

base/sim/FairMCApplication.cxx
base/steer/FairRunSim.cxx
base/steer/FairRunSim.h

FairMCApplication.cxx unconditionally calls TVirtualMC::GetMC()->SetRootGeometry()
Materials/Media created via VMC are added both to TGeo and VMC geometry, so that
the importing the TGeo to VMC in the e.g. TGeant3TGeo::FinishGeometry() leads to
materials duplication and the loss of special (e.g. optical) properties set directly
on VMC materials 1st copy. This patch introduces a flag in the AliRunSim, which tells
to FairMCApplication if the TGeo should be imported to VMC. The flag is set to TRUE
in the constructor, therefore default behaviour of FairRoot is not altered. Those
applications which do not importing of TGeo (e.g. O2 always created the geometry
for the simulation on the fly) can set FairRunSim::SetImportTGeoToVMC(false)
BEFORE building the geometry

Ask FairRunSim if TGeo should be imported to VMC

---

base/event/FairMultiLinkedData_Interface.h

Closes issue #544.
The virtual keyword was removed from all FairMultiLinkedData_Interface methods.

Removing virtuality of methods in FairMultiLinkedData_Interface

---

base/sim/FairDetector.h
base/sim/FairMCApplication.cxx
base/sim/FairModule.h

This promotes the SetSpecialPhysicsCuts interface to FairModule,
so that cuts can be adjusted for passive modules.
Correspoding changes were done in FairMCApplication.

Move SetSpecialPhysicsCuts API from FairDetector to FairModule

---

base/sim/FairModule.cxx

to correct the bug: when geometric radial segmented figures, like TGeoTubeSeg, TGeoConeSeg, TGeoCtub, are specified, particle tracks can not pass through such volumes

adding initialization of angles for TGeoTubeSeg, TGeoConeSeg and TGeoCtub shapes

---

cmake/modules/GenerateVersionInfo.cmake

This aligns things to the same behavior used elsewhere and allows non-annotated tags like the one we use for the O2 nightlies to work.

Use --tags when detecting version via git

---

Jenkinsfile
base/sink/FairRootFileSink.h
base/steer/FairRun.cxx
base/steer/FairRun.h

@karabowi According to #771 the removed `FairRun::GetOutputFile()` member function is used in PandaRoot. Should we put it back as deprecated like the setters?

Ease interface change

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

Hope, this helps @TobiasStockmanns' transition to the new `FairSink` interfaces (#773).

Reintroduce removed interface as deprecated

---

examples/MQ/9-PixelDetector/src/CMakeLists.txt
examples/advanced/Tutorial3/CMakeLists.txt
examples/common/passive/CMakeLists.txt
examples/simulation/Tutorial1/src/CMakeLists.txt
examples/simulation/Tutorial2/src/CMakeLists.txt
examples/simulation/Tutorial4/src/CMakeLists.txt
examples/simulation/rutherford/src/CMakeLists.txt

This is not relevant for FairSoft, but for aliBuild, where we do not
have a shared installation prefix.

Add missing include paths

---

geane/FairGeanePro.cxx
geane/FairGeanePro.h

- added FairGeanePro::GetTimeAtPCA() method.
solves #751 
@TobiasStockmanns can you check please if it works for you?

Provide access to time-of-flight of a particle.

---

base/sim/FairMCApplication.cxx
base/sim/FairMCApplication.h

Allow to switch off the writing of an event to the output file in
case of a simulation run. A task running after the simulation in
FairRunSim events loop can set the flag to false which skips writting
the whole event to the output file. The flag is restored after each
event such the the decision has to be done for each event. The default
setting is to write each event.

Make writting an event to the output optional in FairRunSim.

---

CMakeLists.txt

This change is needed to compile FairRoot v-17.10_patches with alfadist.

Don't require SIMPATH when using MODULAR_BUILD.

---

base/sink/FairRootFileSink.cxx

It appears more robust to retrieve a dictionary using a typeid
rather than a demangled string describing the type.
This is solving an issue (https://github.com/AliceO2Group/AliceO2/issues/1186) where dictionaries where not found for types having a very long name.

FairRootFileSink: Stability fix to retrieve dictionary

---

fairtools/FairLogger.h
fairtools/README.md

Add better deprecation warnings.
Contributes to resolution of #814.
---
Checklist:

Add better deprecation warnings

---

examples/MQ/serialization/1-simple/Ex1Processor.h
examples/MQ/serialization/data_generator/runGenerateData.cxx

During the investigation why some tests are failing as shown in #819 I found two memory leaks which have led to a (occasional for GCC older than 8) segfault in the global ROOT end of program cleanup. I have not understood how the segfault and the memory leaks were related exactly, though.
---
Checklist:

Fix serialization ex

---

base/sim/FairDetector.cxx
base/sim/FairDetector.h
examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx

- Removed FairDetector::DefineSensitiveVolumes() not needed and causing warning in MT mode
- Fixed FairTutorialDet4.cxx compilation with ROOT 6.14/04
---
Checklist:

Fixes in FairDetector and FairTutorialDet4.cxx:

---

examples/MQ/pixelDetector/run/CMakeLists.txt

This can be reversed once we made sure, the test can run in parallel
with others.
---
Checklist:

Do not run pixel_static test in parallel

---

examples/CMakeLists.txt
examples/MQ/histogramServer/CMakeLists.txt
examples/MQ/histogramServer/FairMQExHistoCanvasDrawer.cxx
examples/MQ/histogramServer/FairMQExHistoCanvasDrawer.h
examples/MQ/histogramServer/FairMQExHistoCanvasDrawerExample.cxx
examples/MQ/histogramServer/FairMQExHistoCanvasDrawerExample.h
examples/MQ/histogramServer/FairMQExHistoDevice.cxx
examples/MQ/histogramServer/FairMQExHistoDevice.h
examples/MQ/histogramServer/FairMQExHistoLinkDef.h
examples/MQ/histogramServer/FairMQExHistoServer.cxx
examples/MQ/histogramServer/FairMQExHistoServer.h
examples/MQ/histogramServer/fairmq-start-ex-histo.sh.in
examples/MQ/histogramServer/runExHistoCanvasDrawer.cxx
examples/MQ/histogramServer/runExHistoDevice.cxx
examples/MQ/histogramServer/runExHistoServer.h

A device sending multiple histograms to the generic server. Server publishes the histograms using THttpServer. Implementation with the generic CanvasDrawer.
---
Checklist:

Example of histogram server, implemented in a device

---

base/MQ/devices/FairMQSampler.h
base/MQ/policies/Serialization/BoostSerializer.h
examples/MQ/serialization/2-multipart/Ex2Sink.h
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSink.h
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkBin.tpl
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkBoost.tpl
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkFlatBuffers.tpl
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkMsgpack.tpl
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkProtobuf.tpl
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkTMessage.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTask.h
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskBin.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskBoost.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskFlatBuffers.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskMsgpack.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskProtobuf.tpl
examples/advanced/Tutorial3/MQ/processorTask/FairTestDetectorMQRecoTaskTMessage.tpl
examples/advanced/Tutorial3/MQ/run/README.md
examples/advanced/Tutorial3/MQ/run/runTestDetectorFileSink.cxx
examples/advanced/Tutorial3/MQ/run/runTestDetectorProcessor.cxx
examples/advanced/Tutorial3/MQ/run/runTestDetectorSampler.cxx
examples/advanced/Tutorial3/MQ/run/startMQTut3All.sh.in
examples/advanced/Tutorial3/MQ/run/startMQTut3AllProxy.sh.in
examples/advanced/Tutorial3/MQ/run/startMQTut3ExtraProcessor.sh.in
examples/advanced/Tutorial3/MQ/run/startMQTut3PushPull.sh.in
examples/advanced/Tutorial3/MQ/run/startMQTut3Three.sh.in
examples/advanced/Tutorial3/MQ/samplerTask/FairTestDetectorDigiLoader.h
examples/advanced/Tutorial3/MQ/samplerTask/FairTestDetectorDigiLoaderBoost.tpl

- Use the common base/policies/Serialization/BoostSerializer in Tutorial3 MQ part, which was previously implemented inline.
- Remove support for boost text archive from BoostSerializer (it is very slow) - leaves only binary archive as a single possibility - simplifies interface.
---
Checklist:

Use BoostSerializer in Tutorial3

---

CMakeLists.txt

Set the minimum Cmake version required to 3.11 and Boost to 1.67
see issue #845 
---
Checklist:

Set the minimum Cmake version required to 3.11 and Boost to 1.67

---

CMakeLists.txt

Set the minimum Cmake version required to 3.11 and Boost to 1.67
see issue #845

force CMake 3.11 and Boost 1.67 as minimum, issue #845

---

base/MQ/devices/FairMQUnpacker.h

This is needed for FairMQ 1.3.7
---
Checklist:

Remove const from channel ref to allow non-const receive

---

base/sim/FairMCApplication.cxx

The exception occurs when a user adds new particles to Geant4 to transport
Geant 4 calls AddParticles() function (FairMCApplication class) in own constructor but fMC pointer is initialized later in FairRunSim (fApp->InitMC).
fMC pointer (which is 0x00 in the case) was replaced by TVirtualMC::GetMC in FairMCApplication::AddParticles(), and some cosmetic modifications were made to simplify reading the function.

Correct a bug because of adding particles to Geant4 (fMC is null)

---

CMakeLists.txt
base/steer/FairRunOnline.cxx

The order of the initialization is important since FairSource may register
objects to the output. To do this the output has already to exist which is
the case if FairSink was already initialized.
Bump the version info.
---
Checklist:
* [ x] Rebased against `v18.0_patches` branch

Initialize FairSink before initializing FairSource

---

base/sim/FairMCApplication.cxx
base/sim/FairMCApplication.h
base/sim/FairModule.cxx

- Abort if a detector class has called FairModule::ProcessNodes, while outside of FairMCApplication::ConstructGeometry()
- Will probably break parts of experiment code. Fix: when creating geometry from ASCII file, call templated function FairModule::ConstructASCIIGeometry() from ConstructGeometry() of the detector class.
- FairRoot tests will fail. Fix is in #869

Add LOG(fatal) when ProcessNodes is called outside of ConstructGeometry

---

base/sink/FairRootFileSink.cxx
base/steer/FairRootManager.cxx
fairtools/FairMonitor.cxx
fairtools/FairMonitor.h

Changed the logic of FairMonitor::StoreHistograms.
This is no more called by FairRootManager, but by the FairRootFileSink
at the end of the run.
Fixes the crash of the FairMonitor with recent FairSofts.
---
Checklist:

Quick fix.

---

CMakeLists.txt
base/MQ/devices/FairMQUnpacker.h
examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx

This pull request fixes some issues of the v18.0 patches branch when using the upcoming FairSoft version (RC_feb19). With the proposed changes the code of branch v18.0_patches compiles with the release candidate as well as with the latest FairSoft release.
---
Checklist:
* [x ] Rebased against `v18.0_patches` branch
* [x ] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

Allow to compile v18.0 using FairSoft RC_feb19

---

CMakeLists.txt
cmake/modules/CheckCompiler.cmake

When SIMPATH was unset, running cmake resulted in: 
-- fairsoft-config not found
--- Found a Linux system
--- Found GNU compiler collection
--- Build Type: RelWithDebInfo
--- Compiler Flags:   -O2 -g -Wshadow
CMake Error at CMakeLists.txt:95 (String):
String sub-command FIND requires 3 or 4 parameters.
CMake Error at CMakeLists.txt:96 (If):
if given arguments:
"EQUAL" "-1"
Unknown arguments specified
This was not found to be a very helpful. Thus, I added "'s around the find arguments so they work even when empty, plus added a hint on the fairsoft-config not found info message. 
---
Checklist:

Fixed issue when SIMPATH was unset, added hint.

---

CMakeLists.txt

Without this I get:
```bash
CMake Error at MbsAPI/CMakeLists.txt:19 (CHECK_SYMBOL_EXISTS):
Unknown CMake command "CHECK_SYMBOL_EXISTS".
```

Add CheckSymbolExists

---

fairtools/FairLogger.h
parbase/FairParAsciiFileIo.cxx

Since the new logger interface is available for over a year now, this would help to get rid of useless code.
Any use of `FairLogger::endl` will produce something like:
```
parbase/FairParAsciiFileIo.cxx:103:92: warning: ‘FairLogger::endl’ is deprecated: Line break is now added automatically by the LOG macro, this variable only adds empty space. [-Wdeprecated-declarations]
LOG(FATAL) << "Parameter file " << strParPath << " does not exist." << FairLogger::endl;
^~~~
In file included from /home/orybalch/dev/FairRoot/parbase/FairParAsciiFileIo.cxx:24:
/home/orybalch/dev/FairRoot/fairtools/FairLogger.h:127:23: note: declared here
static char const endl __attribute__((deprecated("Line break is now added automatically by the LOG macro, this variable only adds empty space.")));
```
A deprecation …

Deprecate fairlogger endl

---

base/sim/FairMCApplication.cxx

Fixes undefined behavior, caused by a missing return value in `FairMCApplication::MisalignGeometry()`

Fixed undefined behaviour (Fixes #887)

---

base/MQ/devices/BaseMQFileSink.h
base/MQ/devices/FairMQLmdSampler.h
base/MQ/devices/FairMQSampler.h
base/MQ/devices/FairMQUnpacker.h
examples/MQ/parameters/FairMQExParamsClient.cxx
examples/MQ/pixelAlternative/src/devices/FairMQPixAltFileSinkBin.cxx
examples/MQ/pixelAlternative/src/devices/FairMQPixAltSamplerBin.cxx
examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx
examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx
examples/MQ/pixelDetector/src/devices/FairMQPixelSampler.cxx
examples/MQ/pixelDetector/src/devices/FairMQPixelSamplerBin.cxx
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx
parmq/ParameterMQServer.cxx

In these files the FairMQProgOptions class is not used directly, but only as a member of FairMQDevice (if at all), which includes the header itself.
---
Checklist:

remove unused FairMQProgOptions includes

---

base/sim/FairPrimaryGenerator.cxx
base/sim/FairPrimaryGenerator.h
fairtools/CMakeLists.txt

Implements functionality described in #893.
Fixes #893.
---
Checklist:

Enhance fair primary generator

---

CMakeLists.txt

Tested on Fedora 30 with CMake `3.15.1` only.
Resolve #905

Hotfix v18.0 to support CMake 3.15

---

CMakeLists.txt
CONTRIBUTORS

Fix YAML include dirs cont.

---

CMakeLists.txt
CONTRIBUTORS

Remove "signals" from the required boost modules, otherwise it fails to compile with boost 1.70
---
Checklist:

Remove signals from required boost modules (not needed anymore)

---

CMakeLists.txt
examples/common/mcstack/CMakeLists.txt

Support new dependency of fair::Logger - fmt (introduced in FairRootGroup/FairLogger#20).
The dependency is bundled by default but can be overridden by the user to an external fmt installation. This PR is to support such a case - it adds the entry in the CMake output table and modifies the `FairLogger_INCDIR` to include the path to fmt.
This is backwards-compatible.
---
Checklist:

Support for external fmt

---

base/event/FairMultiLinkedData_Interface.cxx
base/steer/FairRootManager.cxx
base/steer/FairTSBufferFunctional.cxx

Fix bug in copy and assignment opertor of FairMultiLinkedData_Interface class described in issue #927.
---
Checklist:

Fix FairMultiLinkedData insert history bug

---

CMakeLists.txt
examples/simulation/Tutorial4/src/CMakeLists.txt

When compiling FairRoot without OpenGL support, cmake throws an error that Tutorial4 depends on eventdisplay library, but the corresponding target was not found. The problem is in the ROOT_HAS_OPENGL flag. In the main CMakeLists.txt it is of type String, but in Tutorial4/CMakelists.txt it is treated as boolean. This PR fixes this issue.
---
Checklist:

Fix cmake error when ROOT has no opengl

---

examples/common/mcstack/FairStack.h

When running multi-threaded Geant4 the stack settings 
are now cloned properly.
---
Checklist:
[*] Rebased against `dev` branch
[*] My name is in the resp. CONTRIBUTORS/AUTHORS file
[*] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

Fix the bug in FairStack::CloneStack()

---

cmake/modules/FindROOT.cmake

This is needed to find the imported ROOT dependencies when linking against the VMC packages (geant4_vmc, vgm)
This modification is needed to get FairRoot compiled with the latest versions of VMC packages, which require to be built with ROOT CMake configuration file. As FairRoot defines ROOT definition in its own Find module, the library targets were missing.
---
Checklist:

Update in CMake: Added Root libraries as targets:

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

Implemented check if FairRootManager. If attempt to store data
and no sink detected the application will crash.
Fixes issue #935.
[*] Rebased against `dev` branch
[*] My name is in the resp. CONTRIBUTORS/AUTHORS file
[*] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

Fix the bug of storing data in nonexisting sink

---

CONTRIBUTORS
cmake/modules/FindFairRoot.cmake

Under some circumstances (spack + other things) outputting UTF-8 strings can confuse/break other systems. As this output is not critical in any form, replace the strings with ASCII-only versions.
Yes, those other systems should be fixed. But this workaround is much easier and quicker.
---
Checklist:

cmake: Replace UTF-8 message strings

---

README.md

`FAIRROOT_MODULAR_BUILD` was replaced in favor of the standard CMake package lookup strategy.
Closes #900

Remove section about FAIRROOT_MODULAR_BUILD

---

examples/simulation/Tutorial2/macros/read_digis.C
parbase/FairGenericParAsciiFileIo.cxx
parbase/FairParamList.cxx
parbase/FairParamList.h

Improve performance of FairParamList.
Detailed description is found in the commit message.

Improve fairparamlist

---

examples/MQ/pixelDetector/run/CMakeLists.txt
examples/MQ/pixelDetector/run/scripts/startFairMQPixelSimulation.sh.in
examples/MQ/pixelSimSplit/run/scripts/test-splitMQ.sh.in

Increase the max running time, reduce number of parallel jobs,
automatic control over individual runninng processes for pixel_simulation.
Check for and kill old running processes, improve process cleaning
after the test end for pixelSimSplit.
---
Checklist:

Fix test running for pixel examples

---

parbase/FairContFact.cxx
parbase/FairContFact.h

Add a function to add a container to the factory that also checks if the
container already exist. If the container already exist it is not added
again and kFALSE is returned. Otherwise it is added and kTRUE is returned.
The "normal" way to add containers is to use the TList data member directly
which will not report any errors when adding the container. Only when the
destructor of the runtime database is called one will see an error message
Error in <TList::Delete>: A list is accessing an object (0x55d2e2220550)
already deleted (list name = TList)
---
Checklist:

Improve adding container to the container factory

---

base/event/FairMultiLinkedData_Interface.cxx
base/event/FairMultiLinkedData_Interface.h

* Fix nullptr deref in dtor
* Fix memory leak in setter
* Clarify raw pointer semantics
* Add new setter overload
Resolves #955
---
It looks like we do not have test coverage of this code. @MohammadAlTurany @TobiasStockmanns @RalfKliemt Can you point me to some code/macro that calls the changed code, so we can gain some confidence that the code still does what it is expected to do?

Fix mem mgmt of fLink member

---

base/sim/fastsim/CMakeLists.txt

Take into account the namespace in Geant4 libraries targets in fastsim/CMakeLists.txt
Checklist:

Fix for building with Geant 10.6.x:

---

base/sim/FairModule.cxx

Till the replacement of the CheckIfSensitive function with IsSensitive
in the daughter projects, we have to call the CheckIfSensitive depracated
function.
Addresses issue #973.
--
Checklist:

Suppress the warning on usage of depracated function

---

base/steer/FairRootManager.h

Addresses the issue #983.
---
Checklist:

Fix the null fSource ptr in FRM::InitObjectAs

---

base/event/FairPrintFairLinks.h
fairtools/MCStepLogger/MCStepLoggerImpl.cxx

ROOT 6.22 removes some unneeded includes in its headers. This results in FairRoot missing some includes, which are added explicitly in this commit/PR.
Adding these headers fixes the build with ROOT 6.22 and should not result in any changes for ROOT <6.22 due to the include guards.
Please let me know if you have any comments or would like me to make any changes.
---
Checklist:

Add missing includes for ROOT 6.22

---

examples/MQ/serialization/1-simple/testSerializationEx1.sh.in
examples/MQ/serialization/2-multipart/testSerializationEx2.sh.in

Some devices fail without a proper environment setup when accessing ROOT objects.
See https://github.com/FairRootGroup/FairSoft/pull/238.

Serialization example tests: setup environment

---

base/sim/FairIon.cxx
base/sim/FairIon.h

FairIon::SetA()    - set the atomic mass of the ion, to set the mass use SetMass()
FairIon::SetMass() - set the mass of the ion in GeV/c2
The buggy version had SetMass() that scaled the value with AMU before setting the mass.
Removed the amu constant from the class completely.
Addresses the issue #1007.
---
Checklist:

Fix the bug in FairIon::SetMass function

---

cmake/modules/FindGeant4.cmake

Replace set_target_properties syntax that doesn't seem to work on many platforms with `set_property(TARGET … APPEND PROPERTY …)` which seems to work better.
Fixes: https://cdash.gsi.de/testDetails.php?test=7336361&build=250931
---
Checklist:

Fix cmake for external CLHEP

---

CMakeLists.txt

* Check if added include path exists, there is packaging bug in
Debian/Ubuntu, see https://bugs.launchpad.net/ubuntu/+source/yaml-cpp/+bug/1880419
* Limit workaround application up to and including version 0.6.2

CMake: Refine condition for yaml-cpp workaround

---

base/source/FairFileSource.cxx

Fixes the wrong event time setting in the FairFileSource.
This merge request is connected to the issue #1023
---
Checklist:

Fix time setting for EventHeader in FairFileSource

---

examples/advanced/Tutorial3/CMakeLists.txt
examples/advanced/Tutorial3/FairTestDetectorLinkDef.h
examples/advanced/Tutorial3/simulation/FairConstFieldCreator.cxx
examples/advanced/Tutorial3/simulation/FairConstFieldCreator.h
examples/common/eventdisplay/FairEveMCTracks.cxx

When no magnetic field available from FairRunAna, the event
display crashes when drawing events.
Small fix in FairEveMCTracks fixes the issue - it will not exptrapolate tracks when no magnetic field.
Introduce the FairFieldCreator in the Tutorial3 advanced example,
which allows FairRunAna to retrieve magnetic field from the parameter file.
---
Checklist:

Fix for the missing magnetic field in the event display

---

base/sim/FairGenericVMCConfig.cxx
base/sim/FairGenericVMCConfig.h
base/steer/FairRunSim.cxx
base/steer/FairRunSim.h
examples/common/gconfig/g4ConfigPostInit.C
examples/common/gconfig/g4ConfigPostInit.yaml
examples/common/gconfig/g4configPostInit.in
examples/simulation/Tutorial1/macros/run_tutorial1.C
fairtools/MCConfigurator/FairYamlVMCConfig.cxx
fairtools/MCConfigurator/FairYamlVMCConfig.h
trackbase/FairRKPropagator.cxx
trackbase/FairRKPropagator.h

Introduce the gConfig PostInit in the configuration of MC simulation.
Added both the old implementation with the C macro and .in file,
as well as the new one based on yaml.
This change is triggered by the introduction of setup flags
in G4_VMC which can only be set after initilization.
It addresses the issue #1031.
---
Checklist:

Implement the gConfig PostInit

---

CMakeLists.txt

The old way of passing the wanted C++ language level into FairRoot was to set (CMAKE_)CXX_FLAGS with a "-std=c++11" flag.
In a more modern cmake world, one uses CMAKE_CXX_STANDARD and target_compile_features() to let cmake choose the right language level.
The problem starts here: cmake doesn't parse CMAKE_CXX_FLAGS and so flags from both sources end up in the final compile command.
If one wants to configure a project using the modern methods, one does not want to use the old method.
This commit removes a fatal check, that enforces the user to use the old method to set the language level.  That way the user can choose the old or the modern way of doing it.
To be precise: This does not stop any current use. It only removes some (old) "safety guards". And thus allows more modern uses.
Some …

Drop check for "-std=*" in CXX_FLAGS

---

base/steer/FairRunSim.cxx

Also check if there is really a function bound.
Fixes #1041 .
The fix has also to be ported to the v18.6_patches branch. 
---
Checklist:

Use correct flag for post init configuration

---

FairRoot_build_test.cmake
Jenkinsfile

Containers are created from the official dockerhub base images + system update + FairSoft legacy setup script + FairSoft legacy installations to `/fairsoft/<value>` (`<value>` from the spec table in the Jenkins file). No automation for linux image generation yet.
On macOS, the `<value>` corresponds to `brew install fairrootgroup/fairsoft/fairsoft@<value>` to setup the environment.

CI: Add FairSoft apr21 checks

---

MbsAPI/fLmd.c
MbsAPI/f_evt.c

`strncpy()` is a really bad API for copying strings over. For example it always pads the destination with NUL bytes. But does not NUL terminate in case of overflow. See first stackoverflow link.
The nicest alternative to `strncpy` is `strlcpy`.  But that one is not portable.  The second simplest one is using `snprintf()`.  Yes, this feels like overkill. But it's really the by far most readable solution. So unless performance is highly critical (in which case you shouldn't be using `strncpy` anyway, as it pads!), `snprintf` should be fine.
Fixes: #1052
See: https://stackoverflow.com/questions/2114896/why-are-strlcpy-and-strlcat-considered-insecure/2115015#2115015
See: https://stackoverflow.com/questions/41869803/what-is-the-best-alternative-to-strncpy/41885173#41885173
---
Checklist:

Calm `strncpy` Warnings in MbsApi

---

base/steer/FairRunOnline.cxx

This was an unintended consequence/oversight following #940 (fixing issue #935).
The newly introduced FATAL was triggered by the hard-coded `write output flag = kTRUE` (persistence) when the header object was registered in the FairRoot manager.
The change keeps the original behavior in case a Sink is existing and skip the writing otherwise, avoiding the FATAL for pure monitoring tasks without ROOT file output .
Affected branches and releases:
- master and dev
- v18.4.x
- v18.6.x
---
Checklist:

Avoid mandatory Fatal in FairRunOnline if no Sink defined

---

examples/MQ/parameters/CMakeLists.txt
examples/MQ/pixelAlternative/run/CMakeLists.txt
examples/MQ/pixelDetector/macros/CMakeLists.txt
examples/MQ/pixelDetector/run/CMakeLists.txt
examples/MQ/pixelSimSplit/run/CMakeLists.txt
examples/MQ/serialization/CMakeLists.txt
examples/advanced/MbsTutorial/CMakeLists.txt
examples/advanced/Tutorial3/macro/CMakeLists.txt
examples/advanced/propagator/macros/CMakeLists.txt
examples/simulation/Tutorial1/macros/CMakeLists.txt
examples/simulation/Tutorial2/macros/CMakeLists.txt
examples/simulation/Tutorial4/macros/CMakeLists.txt
examples/simulation/rutherford/macros/CMakeLists.txt
test/fairtools/CMakeLists.txt

There's a simple syntax
```cmake
add_test(test_name command arg1 arg2)
```
This syntax captures *everything* after the command as arguments.
Let's use the better syntax everywhere!
```cmake
add_test(NAME test_name COMMAND command arg1 arg2)
```
---
Checklist:

Update add_test Syntax

---

CMakeLists.txt
cmake/modules/FairMacros.cmake
cmake/modules/FairRootTargetRootDictionary.cmake
cmake/modules/FindHEPMC.cmake
cmake/modules/FindPythia8.cmake
examples/CMakeLists.txt

* Drop AlFa_DIR variable 
* Drop GCC_TOOLCHAIN_ROOT variable
* Clean up Pythia8 env usage
* Move example installation into examples/
* Drop global include directories
---
Checklist:

cmake: Drop some variables, little cleanup

---

CMakeLists.txt
MbsAPI/CMakeLists.txt
alignment/CMakeLists.txt
base/CMakeLists.txt
base/MQ/CMakeLists.txt
base/sim/fastsim/CMakeLists.txt
cmake/private/FairRootTargets.cmake
datamatch/CMakeLists.txt
eventdisplay/CMakeLists.txt
fairtools/CMakeLists.txt
fairtools/MCConfigurator/CMakeLists.txt
fairtools/MCStepLogger/CMakeLists.txt
geane/CMakeLists.txt
generators/CMakeLists.txt
geobase/CMakeLists.txt
parbase/CMakeLists.txt
parmq/CMakeLists.txt
test/testlib/CMakeLists.txt
trackbase/CMakeLists.txt

This is an internal function only.  It encapsulates things that already happened and one new.
It is meant for all those libraries that get installed and are expected to be used by other projects.
It is explicitly not meant for the examples. Because they're not meant to be consumed by other projects.
Already happened:
* Add the FairRoot::${target} alias
* Set PROJECT_LIBRARY_PROPERTIES properties
New: fairroot_compile_features()
This sets cxx_std_* on the target.  This isn't very granular, but hopefully fits the current development model better.
The value being used depends on CMAKE_CXX_STANDARD or PROJECT_MIN_CXX_STANDARD.
So when exported targets come, consumers will at least use the CMAKE_CXX_STANDARD.
---
Checklist:

cmake: Introduce fairroot_library_settings()

---

CHANGELOG.md

It is good style to document Release Notes in a file in the repository to avoid vendor lockin.
Document our current status for the 19.0 release here.
---
Checklist:

Add Initial Version of CHANGELOG.md

---

examples/MQ/serialization/1-simple/Ex1Processor.h
examples/MQ/serialization/1-simple/Ex1Sampler.h
examples/MQ/serialization/1-simple/Ex1Sink.h
examples/MQ/serialization/1-simple/testSerializationEx1.sh.in
examples/MQ/serialization/2-multipart/Ex2Processor.h
examples/MQ/serialization/2-multipart/Ex2Sampler.h
examples/MQ/serialization/2-multipart/Ex2Sink.h
examples/MQ/serialization/2-multipart/testSerializationEx2.sh.in
examples/MQ/serialization/CMakeLists.txt

Fixes the race in the serialization examples tests, where a device could exit before transferring all the messages.
Fixes #1048.

Fix serialization examples

---

examples/MQ/serialization/1-simple/Ex1Sampler.h
examples/MQ/serialization/2-multipart/Ex2Sampler.h
examples/simulation/rutherford/src/FairRutherfordGeo.cxx
examples/simulation/rutherford/src/FairRutherfordGeo.h
geobase/FairGeoRootBuilder.cxx

* Use `override` in methods that actually override base functions.
* Increase string buffers to have enough space for 32bit integeers, and use snprintf so to not overwrite any buffer boundaries.
Should fix: #1005
---
Checklist:

Fix Warnings: sprintf and missing override

---

CONTRIBUTORS
parbase/FairRuntimeDb.cxx

Contains the original commits proposed in #1081, but based against `dev`. Will create backports from these commits, once this PR is merged.

Make Rtdb IO backends user-extensible again

---

parbase/FairRuntimeDb.cxx

Part of #1081 
Thanks @patternoia!
cherry-picked from `feature/parbase_refactor` ( ca5d0f7a50df7954866a06685b6fb6000913505c )
---
Checklist:

Remove USE_DB_METHOD define and dependent code

---

parbase/FairContFact.h
parbase/FairDetParAsciiFileIo.h
parbase/FairDetParIo.h
parbase/FairDetParRootFileIo.h
parbase/FairGenericParAsciiFileIo.h
parbase/FairGenericParRootFileIo.h
parbase/FairParAsciiFileIo.h
parbase/FairParGenericSet.h
parbase/FairParIo.h
parbase/FairParRootFileIo.h
parbase/FairParSet.h
parbase/FairParamList.h
parbase/FairRtdbRun.h
parbase/FairRuntimeDb.cxx
parbase/FairRuntimeDb.h

* Lots of `override`
* Use `ClassDefOverride` when deriving from a class already using `ClassDef`
* Mark `fill`/`store` for deprecation
* Little cleanup of `FairRuntimeDb::writeContainer`
* Drop commented out `HDetector*`, `HDet*`, `HGeom*`
I would like to put a `[[deprecated("Not used in FairRoot, will be removed soon")]]` on `fill`/`store`. But that would require to bump to C++14.
See: #1088
---
Checklist:

Small parbase Cleanup

---

examples/MQ/histogramServer/FairMQExHistoDevice.cxx
examples/MQ/histogramServer/FairMQExHistoServer.cxx
examples/MQ/parameters/FairMQExParamsClient.cxx
examples/MQ/pixelAlternative/src/devices/FairMQPixAltTaskProcessorBin.h
examples/MQ/pixelDetector/src/devices/FairMQPixelFileSink.cxx
examples/MQ/pixelDetector/src/devices/FairMQPixelMerger.cxx
examples/MQ/pixelDetector/src/devices/FairMQPixelSampler.cxx
examples/MQ/pixelDetector/src/devices/FairMQPixelTaskProcessor.h
examples/MQ/pixelDetector/src/devices/FairMQPixelTaskProcessorBin.h
examples/MQ/pixelDetector/src/devices/FairMQRunDevice.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQChunkMerger.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQPrimaryGeneratorDevice.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx
examples/MQ/serialization/1-simple/Ex1Processor.h
examples/MQ/serialization/1-simple/Ex1Sampler.h
examples/MQ/serialization/1-simple/Ex1Sink.h
examples/MQ/serialization/2-multipart/Ex2Processor.h
examples/MQ/serialization/2-multipart/Ex2Sampler.h
examples/MQ/serialization/2-multipart/Ex2Sink.h
examples/advanced/Tutorial3/MQ/fileSink/FairTestDetectorFileSinkBoost.tpl
parmq/ParameterMQServer.cxx

These methods are now deprecated in FairMQ, because they do nothing.

Do not use deprecated serialization methods

---

CHANGELOG.md
cmake/modules/ROOTMacros.cmake

ROOT_GENERATE_ROOTMAP is only called for ROOT 5.x.
If anybody uses it nowadays, they should rewrite their build system.
Also improve the ChangeLog a bit.
---
Checklist:

Drop ROOT_GENERATE_ROOTMAP; Improve ChangeLog

---

cmake/modules/ROOTMacros.cmake

As suggested here: https://github.com/FairRootGroup/FairRoot/pull/1100#pullrequestreview-751078921 by @fuhlig1 
ROOT_GENERATE_DICTIONARY calls ROOT_GENERATE_DICTIONARY_OLD, if given args, otherise ROOT_GENERATE_DICTIONARY_NEW is called.
As ROOT_GENERATE_DICTIONARY is only called without args, drop the _OLD version.
Refactor/Cleanup:
* As ROOT_GENERATE_DICTIONARY just calls _NEW, rename _NEW to the main function and drop the "dispatcher".
* All of this is not called from inside FairRoot. It's only used by users of FairRoot. Remove all the code that was intended for internal use.
* Drop the part for ROOT 5.x
---
Checklist:

Drop ROOT_GENERATE_DICTIONARY_OLD, Cleanup

---

examples/advanced/Tutorial3/macro/CMakeLists.txt

In CMake tests `DEPENDS` is only asking for proper ordering. That is "A depends on B" only means that B runs before A, but nothing more.
if A should only start if B was successful, one needs fixtures.  B will declare a "setup fixture" and A then lists this fixture as required.
---
Checklist:

Tutorial3: Use Fixtures Instead of Depends

---

CMakeLists.txt
fairtools/MCConfigurator/FairYamlVMCConfig.cxx
fairtools/MCConfigurator/FairYamlVMCConfig.h

Open questions:
* Is fast simulation Geant4 specific? Or should we call the option rather generically just `UseFastSim`?
* Is the default value of `true` a good default?

fairtools: Add yaml vmc config option "UseFastSim"

---

fairtools/MCConfigurator/FairYamlVMCConfig.cxx

By mistake a PostInitConfig was called by default.
Removed the wrong line from the constructor.
---
Checklist:
[X] Rebased against `dev` branch
[X] My name is in the resp. CONTRIBUTORS/AUTHORS file
[X] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

Fix a bug in FairYamlVMCConfig

---

examples/MQ/pixelAlternative/run/CMakeLists.txt
examples/MQ/pixelDetector/macros/CMakeLists.txt
examples/MQ/pixelDetector/run/CMakeLists.txt

It is not the order of the Pixel tests that
matter, but the existance of the output data
of the previous stages.
---
Checklist:

Pixel: Use Fixtures Instead of Depends

---

CMakeLists.txt
Jenkinsfile

cmake: it doesn't look like setting the compiler variables is still needed any more. So remove it.
ci: SDKROOT setting has been moved onto the ci machine's internal setup. It's really a host specific setup.
---
Checklist:

build/ci: Remove some Apple Special Cases

---

cmake/modules/CheckCompiler.cmake
eventdisplay/FairEventManagerEditor.cxx
eventdisplay/datasource/FairTimebasedSource.h
examples/MQ/pixelSimSplit/src/devices/FairMQChunkMerger.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQChunkMerger.h
examples/MQ/serialization/2-multipart/Ex2Sampler.h
examples/advanced/propagator/src/FairTutPropTrack.cxx
parbase/FairRuntimeDb.cxx
parbase/FairRuntimeDb.h

* Add `-Wall` to all GCC based build types
* Fix most of the low hanging fruits of warnings
This gives 6 new warnings in a typical build that aren't completely easy to fix.
---
Checklist:

cmake: Add `-Wall` to all Build Types for GCC

---

base/event/FairRunInfo.cxx
base/sim/FairModule.cxx
base/sink/FairRootFileSink.cxx
base/source/FairFileSource.cxx
base/source/FairMixedSource.cxx
base/steer/FairRootManager.cxx
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
parbase/FairParRootFileIo.cxx
parbase/FairParamList.cxx

Instead of
```c++
tfile->cd();
tobj->Write();
```
one can also do
```c++
tfile->WriteTObject(tobj);
```
This has the advantage that it does not modify the global gDirectory/gFile (which the calling code might want to keep).
See-Also: https://root.cern/root/htmldoc/guides/users-guide/InputOutput.html#saving-objects-to-disk
---
Checklist:

Use WriteTObject instead of cd + Write

---

CMakeLists.txt
base/steer/FairRun.cxx
test/tgeo/CMakeLists.txt
test/tgeo/test_tgeo_units.C

Add a test which checks if the correct unit system is used in the TGeoManager.
The test should fail for the moment for some versions of FairSoft. A bug was introduced in the contained ROOT versions which changed the default unit system used in FairRoot.
Checklist:
* [x ] Rebased against `dev` branch

Add tgeo test

---

CHANGELOG.md
CMakeLists.txt
FairRoot_build_test.cmake
examples/CMakeLists.txt
examples/MQ/pixelAlternative/run/CMakeLists.txt
examples/MQ/pixelAlternative/run/scripts/startFairMQPixAlt.sh.in
examples/MQ/pixelDetector/CMakeLists.txt
examples/MQ/pixelDetector/run/CMakeLists.txt
examples/MQ/pixelDetector/src/devices/FairMQPixelFileSinkBin.cxx
examples/advanced/Tutorial3/macro/CMakeLists.txt
examples/simulation/Tutorial1/macros/CMakeLists.txt
examples/simulation/Tutorial4/macros/CMakeLists.txt
examples/simulation/rutherford/macros/CMakeLists.txt

The Geant3 based tests are highly unstable.
Rerunning tests like 10 times to get a stable result is no good.
So introduce a new option to enable/disable these tests:
`ENABLE_GEANT3_TESTING`
The default is OFF.
Only branch CI builds will run these tests.
Fixes: #995
---
Checklist:

CI: Disable Geant3 Tests by Default

---

CHANGELOG.md
base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

Add SetTreeName and SetFolderName setters
Reworked the setting of the tree and folder names.
Added the possibility to set these names in the macro
by calling either FairRootManager::Instance()->SetTreeName()
or FairRootManager::Instance()->SetFolderName().
These setters have to be called before calling run->Init().
Addresses issue #1111.
---
Checklist:
[ x ] Rebased against `dev` branch
[ x ] My name is in the resp. CONTRIBUTORS/AUTHORS file
[ x ] Followed [the seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

Treename fix

---

CHANGELOG.md
base/steer/FairRunAna.h
base/steer/FairRunAnaProof.h
base/steer/FairRunOnline.h
base/steer/FairRunSim.h
examples/advanced/Tutorial3/macro/run_digi_reco_proof.C

* No examples use ::Instance
* No internal code uses ::Instance
So deprecate `::Instance` method.
---
Checklist:

FairRunAnaProof: Deprecate `::Instance()`

---

.clang-tidy
FairRoot_build_test.cmake
Jenkinsfile
test/ci/container/fairsoft-install.sh
test/ci/container/ubuntu.rolling.def

* New container based on latest Ubuntu Rolling release.
- FairSott legacy dev branch
- clang-tidy for the clang-tidy part
- clang-format and doxygen for [Hfuture checks
* Initial Jenkins and CTest driver setup for clang-tidy
* No special tests on clang-tidy, just defaults
* jenkins warnings NG plugin integration
---
Checklist:

CI: Initial clang-tidy Setup

---

CHANGELOG.md
base/sim/FairModule.h
base/steer/FairRun.cxx
base/steer/FairRun.h
base/steer/FairRunAnaProof.cxx
base/steer/FairRunAnaProof.h
examples/simulation/rutherford/macros/run_rutherford.C
geane/FairGeanePro.h

Many methods in FairRun have already been deprecated by runtime warnings (and partly notes in the .h).
Turn all of them into C++ `[[deprecated]]` attributes. Also mark them with the doxygen `\deprecated` qualifier and note that they will go away in FairRoot 20.
---
Checklist:

chore: Turn Deprecations into C++ Ones; Schedule Removal

---

base/CMakeLists.txt
base/FairLinkDef.h
base/steer/FairRun.cxx
base/steer/FairRun.h
base/steer/FairRunAna.h
base/steer/FairRunAnaProof.cxx
base/steer/FairRunOnline.cxx
base/steer/FairRunOnline.h
examples/simulation/Tutorial2/macros/create_digis_mixed.C

FairRunAna and FairRunOnline both had a SetSource method. Both used to just call SetSource on FairRootManager. Move this into FairRun.
FairRootManager deletes the source in its destructor. As FairRootManager is a singleton, this happens very late in the process lifetime. Too late for some ROOT interpreter use cases.
So move the ownership to FairRun. FairRun makes sure that FairRootManager does not have a pointer to delete.
Fixes: #1154 
This also contains a small fix for non-mbs builds.
---
Checklist:

FairRun: Now Owns the FairSource

---

examples/MQ/pixelAlternative/run/CMakeLists.txt
examples/MQ/pixelDetector/macros/CMakeLists.txt
examples/MQ/pixelDetector/macros/run_sim.C

(Cherry picked from #889, thanks @karabowi)
This improvement is useful without #889 and we should have it in the tree sooner than later.
Original commit text:
> ### Modify the pixelDetector run_sim macro
> 
> Implement test for the content of the output root file.
> The test will fail if not enough entries or if not enough points is registered in the output tree.
> 
> Added three dart measurements points: number of entries, number of points, and, just as an example, points' mean time.
> 
> Reduce the number of events in the pixel examples.
---
Checklist:

Improve pixel test specificity

---

.clang-tidy
Jenkinsfile
geobase/FairGeoAsciiIo.cxx
geobase/FairGeoAsciiIo.h
geobase/FairGeoAssembly.h
geobase/FairGeoBrik.h
geobase/FairGeoCompositeVolume.h
geobase/FairGeoCone.h
geobase/FairGeoCons.h
geobase/FairGeoEltu.h
geobase/FairGeoNode.h
geobase/FairGeoOldAsciiIo.cxx
geobase/FairGeoOldAsciiIo.h
geobase/FairGeoPcon.h
geobase/FairGeoPgon.h
geobase/FairGeoRootBuilder.h
geobase/FairGeoSphe.h
geobase/FairGeoTorus.h
geobase/FairGeoTrap.h
geobase/FairGeoTrd1.h
geobase/FairGeoTube.h
geobase/FairGeoTubs.h

* Use `override` around in geobase
* Instead of pointing to an `std::fstream` just include it.
* clang-tidy on headers, not on root dictionaries
---
Checklist:

clang-tidy on headers, geobase: `override` and value member variable

---

Jenkinsfile

clang-tidy warning extraction in jenkins seems a bit unstable. Some warnings arrive while others / the same disappear at the same time.
So allow two new warnings compared to the reference build.
---
Checklist:

ci(warnings): Allow Some Fluctuation

---

CHANGELOG.md
base/sim/FairMCApplication.cxx
base/steer/FairRadLenManager.cxx
base/steer/FairRadLenManager.h
base/steer/FairRadMapManager.cxx
base/steer/FairRadMapManager.h

* `AddPoint`: Pass in the TVirtualMC, so that the already known value can be used
* Deprecate `Instance`. It's not needed in FairRoot.
---
Checklist:

FairRad{Len,Map}Manager: AddPoint and Instance

---

examples/simulation/rutherford/macros/eventDisplay.C
examples/simulation/rutherford/macros/run_rad.C
examples/simulation/rutherford/macros/run_rutherford.C
examples/simulation/rutherford/src/FairRutherford.cxx
examples/simulation/rutherford/src/FairRutherford.h
examples/simulation/rutherford/src/FairRutherfordContFact.cxx
examples/simulation/rutherford/src/FairRutherfordContFact.h
examples/simulation/rutherford/src/FairRutherfordGeo.h
examples/simulation/rutherford/src/FairRutherfordGeoPar.cxx
examples/simulation/rutherford/src/FairRutherfordGeoPar.h
examples/simulation/rutherford/src/FairRutherfordPoint.h

eventDisplay.C already uses Geant4 by default Switch run_rutherford.C and run_rad.C to use Geant4 by default as well.
---
Checklist:

Rutherford: Default to Geant4

---

parbase/FairParRootFileIo.cxx
parbase/FairParRootFileIo.h

Refactor the part of `FairParRootFileIo::open(TList *)` that merges multiple ROOT files from a list of names into one file into a new static `mergefile` method.
---
Checklist:

ParRootFileIo: Refactor Multi File Merging

---

CHANGELOG.md
base/sim/FairMCApplication.h
base/steer/FairRadGridManager.h
base/steer/FairRunSim.h
examples/simulation/Tutorial1/macros/run_tutorial1_mesh.C

Introduce getter to allow accessing FairRadGridManager on FairMCApplication.
And introduce getter to access FairMCApplication on FairRunSim.
---
Checklist:

Deprecate `FairRadGridManager::Instance`

---

base/sink/FairRootFileSink.cxx
base/sink/FairRootFileSink.h
base/steer/FairRootManager.h

If registering branches after they have been setup, output a warning.
This is trying to improve the situation for #1183
---
Checklist:

FairRootFileSink: Warn on Branch Registration

---

CHANGELOG.md
geobase/FairGeoVector.h

round(d, n) modifies `d` but didn't take it as a reference.
So it used to do nothing.
round(n) just called round(d, n) for all three coordinates.
So it effectively did nothing also.
Deprecate both and tell people why.
---
Checklist:

Deprecate `FairGeoVector::round`

---

examples/simulation/Tutorial1/src/FairTutorialDet1.cxx
examples/simulation/Tutorial1/src/FairTutorialDet1.h

Change the Initialize function such that it asserts when the function is
called twice.
Closes #1195
Checklist:
* [ x] Rebased against `dev` branch

Fail test when calling function twice

---

base/steer/FairRun.cxx
base/steer/FairRun.h
base/steer/FairRunAnaProof.cxx
base/steer/FairRunOnline.cxx

We already moved the ownership for the FairSource from FairRootManager to FairRun. Let's do that as well for FairSink.
Also provide an additional unique_ptr based `SetSink` API, so that it is more obvious, that it takes an owning pointer.
See-Also: f7c9d7cd44ec75b4e7711be4fdc45e343f3d123b
---
Checklist:

FairRun: Now Owns the FairSink as Well

---

base/MQ/policies/Sampler/SimpleTreeReader.h
base/MQ/policies/Storage/RootOutFileManager.h
base/source/FairFileSource.cxx
base/source/FairFileSourceBase.cxx
base/source/FairMixedSource.cxx
examples/MQ/pixelDetector/macros/run_sim.C
examples/MQ/serialization/1-simple/Ex1Sampler.h
examples/MQ/serialization/2-multipart/Ex2Sampler.h
parbase/FairParRootFileIo.cxx

ROOT 6.18 added `TDirectory::Get<T>(const char*)` to get a
properly checked and casted object from a File / Directory.
Use it everywhere.
See: https://root.cern/doc/v618/release-notes.html#io-libraries-1
---
Checklist:

Use `TDirectory::Get<T>()` Around

---

examples/common/eventdisplay/FairEveMCTracks.cxx
examples/common/eventdisplay/FairEveMCTracks.h
trackbase/FairRKPropagator.cxx

If there is no magnetic field object, then the `FairEveMCTracks` did not try to draw any tracks.
Also `FairRKPropagator` was not able to handle that case either.
The current implementation doesn't try to be efficient for this case, as it is not expected to be the common case.
fixes: #1190
---
Checklist:

Handle non-existant Magnetic Field in Track Display

---

.clang-tidy
base/source/FairFileSourceBase.h
eventdisplay/FairGetEventTime.h
fairtools/FairLogger.h
fairtools/FairMonitor.cxx
fairtools/FairMonitor.h

classes with virtual methods basically should have a virtual destructor.
C++ Core Guidelines
C.35: A base class destructor should be either public and virtual, or protected and non-virtual
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-dtor-virtual
Check: cppcoreguidelines-virtual-class-destructor
---
Checklist:

clang-tidy: Check for Virtual Destructor

---

CHANGELOG.md
base/sim/FairGeaneApplication.h
geane/FairGeanePro.cxx
geane/FairGeanePro.h

It's not used in any relevant places.
And if access to it is needed, then a new getter on FairGeane should be implemented.
---
Checklist:

Deprecate FairGeaneApplication::Instance

---

base/MQ/devices/FairMQSampler.h
base/sim/FairMCApplication.cxx
base/steer/FairAnaSelector.cxx
examples/simulation/Tutorial1/macros/run_tutorial1.C
examples/simulation/Tutorial1/macros/run_tutorial1_binary.C
examples/simulation/Tutorial1/macros/run_tutorial1_mesh.C
examples/simulation/Tutorial1/macros/run_tutorial1_pythia6.C
examples/simulation/Tutorial1/macros/run_tutorial1_pythia8.C
examples/simulation/Tutorial1/macros/run_tutorial1_urqmd.C
examples/simulation/Tutorial2/macros/create_digis.C
examples/simulation/Tutorial2/macros/create_digis_mixed.C
examples/simulation/Tutorial2/macros/read_digis.C
examples/simulation/Tutorial2/macros/run_background.C
examples/simulation/Tutorial2/macros/run_signal.C
examples/simulation/Tutorial2/macros/run_tutorial2.C
examples/simulation/Tutorial4/macros/run_reco.C
examples/simulation/Tutorial4/macros/run_tutorial4.C
examples/simulation/rutherford/macros/run_rad.C
examples/simulation/rutherford/macros/run_rutherford.C

Now that FairRun::SetSink supports unique_ptr, use it  around to promote good style.
---
Checklist:

Use unique_ptr based SetSink Around (1/2)

---

examples/MQ/pixelDetector/macros/run_digi.C
examples/MQ/pixelDetector/macros/run_digiToBin.C
examples/MQ/pixelDetector/macros/run_sim.C
examples/MQ/pixelDetector/run/runMQSim.cxx
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.h
examples/MQ/pixelSimSplit/run/runMQTrans.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.h
examples/advanced/Tutorial3/macro/run_digi.C
examples/advanced/Tutorial3/macro/run_digi_reco_proof.C
examples/advanced/Tutorial3/macro/run_digi_timebased.C
examples/advanced/Tutorial3/macro/run_reco.C
examples/advanced/Tutorial3/macro/run_reco_timebased.C
examples/advanced/Tutorial3/macro/run_sim.C
examples/advanced/propagator/macros/runMC.C
examples/advanced/propagator/macros/runProp.C

Now that FairRun::SetSink supports unique_ptr, use it around to promote good style.
---
Checklist:

Use unique_ptr based SetSink Around (2/2)

---

cmake/modules/FindFairRoot.cmake
templates/CMakeLists.txt
templates/project_root_containers/CMakeLists.txt
templates/project_root_containers/MyProjData/MyProjMCTrack.cxx
templates/project_root_containers/NewDetector/NewDetector.cxx
templates/project_root_containers/passive/MyMagnet.cxx
templates/project_stl_containers/CMakeLists.txt
templates/project_stl_containers/MyProjData/MyProjMCTrack.cxx
templates/project_stl_containers/NewDetector/NewDetector.cxx
templates/project_stl_containers/passive/MyMagnet.cxx
templates/test_project_root_containers.sh.in
templates/test_project_stl_containers.sh.in

A typical "ExperimentRoot" project uses FairRoot by using its find-Module (by adding the right path) and calling find_package(FairRoot).
This setup worked for the first call to CMake (configure step), but reconfiguring (running CMake again) did not work correctly.
Add a test for this (that failed without this fix).
The find module recursively calls find_package(FairRoot CONFIG) to load the new config mode package.
This sets FairRoot_DIR to the directory containing the config mode package. This variable is a cache variable and persists into the next run of CMake.
The old find module used to think, that FairRoot_DIR could be the prefix of the FairRoot installation.
Rewrite:
* Use FAIRROOTPATH and ENV{FAIRROOTPATH} only to extend CMAKE_PREFIX_PATH to search the config mode package
* Use …

fix(cmake): Handle Double CMake in Using Projects

---

base/field/FairField.h
base/steer/FairTask.h
examples/MQ/Lmd/README.md
examples/MQ/README.md
examples/MQ/parameters/README.md
examples/MQ/pixelAlternative/README.md
examples/MQ/pixelDetector/README.md
examples/MQ/pixelSimSplit/README.md
examples/MQ/serialization/README.md
examples/README.md
examples/advanced/MbsTutorial/README.md
examples/advanced/README.md
examples/advanced/Tutorial3/MQ/README.md
examples/advanced/Tutorial3/MQ/run/README.md
examples/advanced/Tutorial3/README.md
examples/advanced/Tutorial3/simulation/FairConstField.h
examples/common/README.md
examples/simulation/README.md
examples/simulation/Tutorial1/README.md
examples/simulation/Tutorial2/README.md
examples/simulation/Tutorial4/README.md
templates/README.md
templates/project_root_containers/field/MyConstField.h
templates/project_stl_containers/field/MyConstField.h

Doxygen has a concept of "pages". These are somewhat independent of the usual C++ stuff. Markdown files are converted to "pages".
Pages can have subpages and form a hierarchy that way. This is even shown in the left sidebar.
So turn the whole `examples/` into a proper hierarchy.
---
Checklist:

docs: Turn Examples into Page Hierarchy

---

eventdisplay/tracks/FairEveGeoTracks.cxx
examples/common/eventdisplay/FairEveMCTracks.cxx

1. When FairGeoTracksDraw/FairMCTrackDraw does not find data, it returns kFATAL - which closes the event display. I propose to change it into the kERROR - thanks to this rest of the event display tasks should still work.
2. Another change is using TClass to check if MCTrack branch contains FairMCTrack-based class - if not - then deactivate the task. This prevents the situation when branch "MCTrack" is present but contains a different class (which leads to unexpected behavior).
---
Checklist:

Change EveDisplay check for tracks to fatal

---

CHANGELOG.md
base/steer/FairRunSim.cxx
base/steer/FairRunSim.h
examples/simulation/Tutorial1/macros/run_tutorial1.C

Switch `FairRunSim::SetSimulationConfig()` to `unique_ptr` (from raw pointer with unknown ownership).
Base idea by @karabowi in #1236
---
Checklist:

Use `unique_ptr` API for SimulationConfig

---

base/field/FairFieldFactory.cxx
base/steer/FairRun.cxx
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
base/steer/FairRunOnline.cxx
base/steer/FairRunSim.cxx
eventdisplay/FairEventManager.cxx
geobase/FairGeoLoader.cxx

The singleton like pattern in FairRoot has globals pointing to an instance that was created by `new`.
If those instances get destructed (for example by `delete`) then the global variable is now invalid.
So reset it to nullptr in the destructor.
---
Checklist:

fix: Do not Point to Destructed Objects

---

CHANGELOG.md
base/field/FairFieldFactory.cxx
base/field/FairFieldFactory.h
examples/advanced/Tutorial3/simulation/FairConstFieldCreator.cxx
templates/project_root_containers/field/MyFieldCreator.cxx
templates/project_stl_containers/field/MyFieldCreator.cxx

fCreator is a normal member variable inside each instance that points to that exact instance.
Deprecate this.
And some default member functions used to have infinite recursion that way.
* createFairField is now abstract.  You really have to override it.
* SetParm is now a noop, If you need it, override it.
---
Checklist:

Deprecate fCreator in FairFieldFactory

---

base/field/FairField.h
examples/MQ/serialization/README.md
examples/advanced/Tutorial3/simulation/FairConstField.h

These two show up often in unrelated PRs
* Fix simple formatting of `<...>` which doxygen's markdown parser might consider for HTML
* Drop docs on overriden member functions, if the base class has good docs.
---
Checklist:

Fix some Simple Doxygen Warnings

---

examples/MQ/pixelDetector/src/devices/FairMQRunDevice.cxx
examples/MQ/pixelDetector/src/devices/FairMQRunDevice.h
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.h
examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.h

Both FairMQSimDevice and FairMQTransportDevice implemented the same SetSink method. Move it into the base class.
Add a new SetupRunSink to setup the sink in the FairRun from the sink in the FairMQRunDevice and transfer ownership that way.
---
Checklist:

Move SetSink into base class FairMQRunDevice

---

base/sim/FairMCApplication.cxx
base/sim/FairMCApplication.h
base/steer/FairRun.cxx

CloneForWorker creates a FairRunSim. But this was not cleaned up anywhere.
So clean it up during destruction of FairMCApplication.
Also use the fRun member variable more instead of FairRun{,Sim}::Instance.
---
Checklist:

FMCApp: Do not Leak FairRunSim

---

CHANGELOG.md
CMakeLists.txt
base/CMakeLists.txt
base/event/FairHit.h
base/event/FairMCPoint.h
base/event/FairTimeStamp.h
examples/CMakeLists.txt

solves #1228
AliceO2 does not use the `FairRoot::BaseMQ` target. Because it cannot be disabled, FairRoot pulls in quite heavy dependencies like Boost and FairMQ, which are not used through FairRoot. @ktf has requested a possibility to disable those libraries in FairRoot.
One approach is certainly to exactly define a build switch based on the request, such as `DISABLE_BOOST=ON` or similar. However, longterm maintenance of such a dependency-based build switch may grow complicated as FairRoot is a collection of dozens of libraries which may each have their own rationale when and why they want to depend on a Boost library.
Therefore, I propose to add a simple build switch `BUILD_BASEMQ=ON/OFF` which just disables the `FairRoot::BaseMQ` library and all that depends on it (`FairRoot::FairMQ`, …

Support disabling `BaseMQ` and dependencies

---

base/field/FairFieldFactory.h
base/sim/FairGeaneApplication.h
base/sim/FairModule.h
base/steer/FairRadGridManager.h
base/steer/FairRadLenManager.h
base/steer/FairRadMapManager.h
base/steer/FairRootManager.h
base/steer/FairRunAnaProof.h
base/steer/FairTask.h
geane/FairGeanePro.h
geobase/FairGeoVector.h

Now that all those deprecations have been moved to 18.8 update the appropriate docs.
NOTE: If the 18.8 branch gets to be like this, then this should be forward ported to `dev`.
---
Checklist:

Doxygen: Update Deprecations for 18.8

---

base/steer/FairRun.cxx

FairRunAna might add fTask to ROOT's "ListOfBrowsables". FairRun deallocates it during its desctructor.
So let's remove it from the list there as well.
(cherry picked from commit f9f1648108e58ca998cd0b8a0d67601440934ad0)
---
Checklist:

[18.6] FairRun: Remove fTask from Browsables

---

base/steer/FairTSBufferFunctional.h
eventdisplay/FairEventManagerEditor.cxx
examples/simulation/rutherford/src/FairRutherfordGeo.cxx
examples/simulation/rutherford/src/FairRutherfordGeo.h
online/steer/FairRunOnline.cxx

I verified 3e31ea4b4b698715865e47e108885443e75fa615 manually with Tutorial1, the GUI element didn't show any difference and worked as before, so I assume, there was no hidden side effect.

Fix warnings

---

CHANGELOG.md
base/steer/FairRootManager.h
base/steer/FairRun.h
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
online/steer/FairRunOnline.cxx

`FairRootManager::FillEventHeader()` is only called from FairRun (and derived classes). So create an appropriate `FairRun::FillEventHeader()` and use it around.
Deprecate `FairRootManager::FillEventHeader()`.
---
Checklist:

[18.8] Move FillEventHeader from FRM to FairRun

---

.clang-tidy
FairRoot_doxygen_test.cmake

Now that all warnings from this check have been fixed, enable it.
See-Also: 990d473a532769f0d45414d7be92b57c3b571736
---
Checklist:

clang-tidy: readability-simplify-boolean-expr

---

base/sim/FairMCApplication.h

The order of calling these two functions by TGeant3 and TGeant4 is different.
Especially, when registering output branches in the Init() of event generators (called by AddIons()), these action will not be taken into account when creating the output tree, which takes place in the InitGeometry() function of FairMCApplication.
---
Checklist:

Add comments to AddIons() and InitGeometry()

---

templates/project_root_containers/MyProjData/CMakeLists.txt
templates/project_root_containers/NewDetector/CMakeLists.txt
templates/project_root_containers/field/CMakeLists.txt
templates/project_root_containers/passive/CMakeLists.txt
templates/project_stl_containers/MyProjData/CMakeLists.txt
templates/project_stl_containers/NewDetector/CMakeLists.txt
templates/project_stl_containers/field/CMakeLists.txt
templates/project_stl_containers/passive/CMakeLists.txt

Now that we have FairRoot:: targets, use them in the templates.
After this has merged to dev, I intend to backport it to 18.8.
---
Checklist:

build: Use FairRoot:: targets in templates

---

CHANGELOG.md
base/steer/FairRootManager.h
base/steer/FairRun.h
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
online/steer/FairRunOnline.cxx

FairRootManager::FillEventHeader is only called from FairRun (and derived classes). So create an appropriate FairRun::FillEventHeader and use it around.
Deprecate FairRootManager::FillEventHeader.
(cherry picked from commit b46784a7ebe819e7780e05f9a1944b9b1dfd8235)
See: #1255
---
Checklist:

Forward Port: Move FillEventHeader from FRM to FairRun

---

templates/project_root_containers/MyProjData/CMakeLists.txt
templates/project_root_containers/NewDetector/CMakeLists.txt
templates/project_root_containers/field/CMakeLists.txt
templates/project_root_containers/passive/CMakeLists.txt
templates/project_stl_containers/MyProjData/CMakeLists.txt
templates/project_stl_containers/NewDetector/CMakeLists.txt
templates/project_stl_containers/field/CMakeLists.txt
templates/project_stl_containers/passive/CMakeLists.txt

Now that we have FairRoot:: targets, use them in the templates.
(cherry picked from commit a4b5cf78ef5d5a8e7adb87b7b9fa90bfd1c4a06a)
See: #1279
---
Checklist:

[18.8 backport] build: Use FairRoot:: targets in templates

---

base/steer/FairRootManager.h

FairRootManager::FillEventHeader already deprecated in v18.8.
Thanks @fuhlig1 for noticing!
---
Checklist:

fix: Correct Deprecation Version

---

CHANGELOG.md
base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

Undeprecated the FairRootManager::GetOut{File,Tree}.
Reverted the FairRootManager::GetOut{File,Tree}
removed by commit 1094179b9fa5fc9bffdc4ff413ea465c227dc2b8.
---
Checklist:

Revert get out file

---

CHANGELOG.md
datamatch/CMakeLists.txt
datamatch/FairMCDataCrawler.h
datamatch/FairMCEntry.h
datamatch/FairMCList.h
datamatch/FairMCMatch.h
datamatch/FairMCMatchCreatorTask.h
datamatch/FairMCMatchLoaderTask.h
datamatch/FairMCMatchSelectorTask.h
datamatch/FairMCObject.h
datamatch/FairMCResult.h
datamatch/FairMCStage.h

By default it will not be built.
Enable it by -DBUILD_DATAMATCH=ON
Addresses issue #1270.
---
Checklist:

Deprecate DataMatch

---

base/event/FairEventBuilderManager.cxx
base/event/FairEventBuilderManager.h
base/event/FairPrintFairLinks.cxx
base/event/FairPrintFairLinks.h
base/steer/FairRingSorterTask.h
datamatch/FairMCMatchCreatorTask.cxx
datamatch/FairMCMatchCreatorTask.h
datamatch/FairMCMatchLoaderTask.cxx
datamatch/FairMCMatchLoaderTask.h
datamatch/FairMCMatchSelectorTask.cxx
datamatch/FairMCMatchSelectorTask.h
eventdisplay/FairBoxSetDraw.cxx
eventdisplay/FairBoxSetDraw.h
eventdisplay/FairPointSetDraw.cxx
eventdisplay/FairPointSetDraw.h
examples/MQ/pixelAlternative/src/PixelAltDigiWriteToRootVector.cxx
examples/MQ/pixelAlternative/src/PixelAltDigiWriteToRootVector.h
examples/MQ/pixelDetector/src/PixelDigiWriteToBinFile.h
examples/MQ/pixelDetector/src/PixelDigiWriteToFile.h
examples/advanced/Tutorial3/digitization/FairTestDetectorHitProducerSmearing.cxx
examples/advanced/Tutorial3/digitization/FairTestDetectorHitProducerSmearing.h
examples/simulation/Tutorial4/src/reco/FairTutorialDet4MilleWriter.cxx
examples/simulation/Tutorial4/src/reco/FairTutorialDet4MilleWriter.h
examples/simulation/Tutorial4/src/reco/FairTutorialDet4StraightLineFitter.cxx
examples/simulation/Tutorial4/src/reco/FairTutorialDet4StraightLineFitter.h

Many classes derive from FairTask and override
SetParContainers with either an empty method, or one that effectively does nothing useful.
FairTask::SetParContainer() exists, does nothing and thus is a good default/fallback.
So remove all those empty/useless methods.
---
Checklist:

Drop Empty/Useless SetParContainers()

---

alignment/FairAlignmentHandler.cxx
alignment/FairAlignmentHandler.h
examples/simulation/Tutorial4/macros/plots.C

1. Refresh the geometry once done (needed in any case)
2. Fix for GeoAssembly bounding box having 0 dx/dy after alignment (#1243)
Fix could be removed once proper fix is done in Root, should not hurt if done twice
Should be backported to the next v18.6.x if accepted as probably needed for next CbmRoot release.
---
Checklist:

Improve geometry state after alignment

---

base/sim/fastsim/FairFastSimDetector.h
examples/MQ/pixelDetector/src/Pixel.cxx
examples/MQ/pixelDetector/src/Pixel.h
examples/advanced/propagator/src/FairTutPropDet.cxx
examples/advanced/propagator/src/FairTutPropDet.h
examples/simulation/Tutorial1/src/FairFastSimExample.cxx
examples/simulation/Tutorial1/src/FairFastSimExample.h
examples/simulation/Tutorial1/src/FairFastSimExample2.cxx
examples/simulation/Tutorial1/src/FairFastSimExample2.h
examples/simulation/Tutorial2/src/FairTutorialDet2.cxx
examples/simulation/Tutorial2/src/FairTutorialDet2.h
examples/simulation/rutherford/src/FairRutherford.cxx
examples/simulation/rutherford/src/FairRutherford.h

A few examples override FairDetector::Initialize and just call FairDetector::Initialize(), so effectively do the same as not overriding it at all.
So drop the overriden methods.
---
Checklist:

Drop useless overriden Initialize()

---

cmake/private/FairRootConfig.cmake.in
cmake/private/FairRootPackage.cmake

On FairCMakeModules 1.0.0 export all the information about needed packages and their (optional) components.
Previous versions of FairCMakeModules can't handle `OPTIONAL_COMPONENTS` properly.  So don't export stuff there.

build(Packaging): Setup Dependency-Exporting

---

CHANGELOG.md
online/steer/FairRunOnline.cxx

Return values of the calls to `source->InitUnpackers()` and `source->ReinitUnpackers()` in `FairRunOnline` are now checked. Should the value be `false`,
the fatal message will be printed.
Addresses issue #1301.
---
Checklist:

Check the return value `source->InitUnpackers`

---

base/event/FairEventHeader.cxx
base/event/FairEventHeader.h
base/steer/FairRun.cxx
base/steer/FairRun.h
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
online/steer/FairRunOnline.cxx

Classes derived from FairRun often call GetRunId() on fEvtHeader. So let's have a shortcut.

Add FairRun::GetEvtHeaderRunId and use it

---

base/sim/FairMCApplication.cxx
base/sim/FairMCApplication.h

In the Worker, the `fModules` are cloned.
So they need to be cleaned up afterwards.
Also add `fListModules` as a mirror of fModules to improve
some parts of the code.
Also drop the unsed `fDetectors`.
---
Checklist:

FMCApp: Do not leak Modules

---

base/FairLinkDef.h

Added `+` to `FairEventHeader` in `LinkDef`.
Without `+`, there is no information printed
about `FairEventHeader` in the tree->Print() output.
Addresses issue #1306.
---
Checklist:

Add streamer for the `FairEventHeader`

---

.clang-tidy
examples/MQ/pixelDetector/src/FairOnlineSink.cxx
examples/MQ/pixelDetector/src/FairOnlineSink.h
examples/MQ/serialization/2-multipart/SerializerExample2.h

Enable two `bugprone-*` checks in clang-tidy.
Fix the issues found and improve related code:
* Fix sizeof in Serializer
* Improve/Fix the Constructors of FairOnlineSink and utilize the improved copy constructor.
---
Checklist:

Start to enable two bugprone-* checks

---

parbase/FairParAsciiFileIo.cxx
parbase/FairParAsciiFileIo.h

Enables the users to choose the name of the merged file. Analogue to `FairParRootFileIo::MergeFiles()`.
Triggered by issue #1314.
---
Checklist:

Add `MergeFiles` to `FairParAsciiFileIo`

---

CHANGELOG.md
base/event/FairEventHeader.cxx
base/event/FairEventHeader.h
base/steer/FairRun.cxx
base/steer/FairRun.h
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
examples/MQ/serialization/1-simple/Ex1Processor.h
online/steer/FairRunOnline.cxx

Backport:
- #1305 
- #1311 
- Add date to the 18.8.0 entry in changelog.
P.S.: Our new Pull Request Template at work!
---
Checklist:

[18.8] Backport #1311, #1305

---

examples/MQ/pixelDetector/README.md

Properly escape code snippets so that doxygen doesn't think these might be html/xml tags.
Should fix some warnings by Doxygen that show up regularly.
---
Checklist:

fix(docs): Proper code Formatting

---

base/sim/FairMCApplication.cxx
base/sink/FairRootFileSink.cxx
base/sink/FairRootFileSink.h
base/steer/FairRunSim.cxx

After a FairRunSim::Run the Sink is sometimes still open.
Close it properly.
Also close the ROOT-File if a FairRootFileSink gets destructed.
See: https://cdash.gsi.de/testDetails.php?test=13258151&build=366624
---
Checklist:

fix: Close Sink at end of a Run

---

examples/simulation/Tutorial1/macros/CMakeLists.txt

Increase the number of events for Geant4MT test from 10 to 20. 
With the previous number of events the test `ex_sim_tutorial1_Geant4MT` could interfere with test `ex_sim_tutorial1_TGeant4`.
Added `sim` to the tests names for persistency.
---
Checklist:

Tutorial1: quick fixup

---

examples/MQ/serialization/data_generator/RooDataGenerator.h

```
[#0] WARNING:InputArguments -- The parameter 'fSigmaT' with range [-1e+30, 1e+30] of the RooGaussian 'fGaussT' exceeds the safe range of (0, inf). Advise to limit its range.
```
The sigma of a Guassian has to be positive.
So limit the range of the sigma variable to some arbitrary positive values.
See: https://github.com/FairRootGroup/FairRoot/pull/1341#issuecomment-1420771138
---
Checklist:

fix(ex_MQ_serialization): InputArguments WARNING

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

* Turn fObj2 into std::vector
* Drop fCurrentEntryNo, fTimeforEntryNo
This is a little step towards making the `GetObject` code more readable.
---
Checklist:

Little Cleanup FairRootManager

---

AUTHORS
codemeta.json

codemeta.json is becoming a standard format for describing software. Let's start to add it.
This is also starting to get relevant in the context of ESCAPE.
I created the current codemeta.json to match the entry on zenodo as closely as possible. That means, that any issues with the zenodo entry are also issues with the codemeta data.
Helpful:
* There is a codemeta generator/viewer: https://codemeta.github.io/codemeta-generator/
You can even paste the suggested codemeta.json there and view it.
---
Checklist:

Add initial codemeta.json

---

eventdisplay/FairEventManager.cxx
eventdisplay/FairEventManager.h
eventdisplay/tracks/FairEveGeoTracks.cxx
examples/common/eventdisplay/FairEveMCTracks.cxx
examples/common/eventdisplay/FairEveMCTracks.h

Part of this is from #1317 thanks to Daniel Wielanek (@DanielWielanek)!
ab58c0136e9f2a671365ebbb6a329b9c477c25ed changed our pointer formatting to be consistent around the whole project (and not consistent within one file). So that means we need to (slowly) update all our formatting.
While at it, added some `auto`, some `static_cast` instead of C style casts, used some newer methods (`GetRootManager` instead of a `::Instance`).
---
Checklist:

eventdisplay: Update Formatting, some Cleanup

---

.clang-tidy

clang-tidy's bugprone-* checks flag common issues that can cause real bugs.

clang-tidy: enable many bugprone-*

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

Removed unused `fRootFolder`.
Removed code present anyways in `ActivateBranch`.
---
Checklist:

Clean `FairRootManager::GetObject` function

---

base/steer/FairRootManager.cxx
base/steer/FairRootManager.h

* Improve fListFolder Handling
* fMap Cleanup
* Drop fOldEntryNr, ClassImp
* Use std::atomic for fId
---
Checklist:

FRM: Cleanup of fListFodler, fMap

---

CHANGELOG.md
base/steer/FairRootManager.cxx
base/steer/FairRunAna.cxx
base/steer/FairRunAnaProof.cxx
examples/advanced/Tutorial3/MQ/sampler.cxx

Replaced `LOG(fatal)` with `LOG(error)`
in `FairRootManager::RegisterImpl()`.
Now running without `sink` will not crash.
Note that in this mode also persistent branches would not be stored anywhere.
Addresses issue #1355.
---
Checklist:

Allow running without sink

---

examples/MQ/pixelDetector/src/PixelDigiBinSource.cxx
examples/MQ/pixelDetector/src/PixelDigiBinSource.h
examples/MQ/pixelDetector/src/PixelDigiSource.cxx
examples/MQ/pixelDetector/src/PixelDigiSource.h

Use valued members instead of heap objects.
FairRootManager::GetObject uses FairSource::ActivateObject as a backend. Let's start and fix the memory handling there.
---
Checklist:

Fix memory leak in PixelDigi*Source

---

examples/MQ/pixelDetector/src/FairOnlineSink.cxx
examples/MQ/pixelDetector/src/devices/FairMQRunDevice.cxx
examples/MQ/pixelDetector/src/devices/FairMQRunDevice.h
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.h

We know the FairOnlineSink when calling SendBranches. So just pass it in instead of asking FairRootManager.
---
Checklist:

chore: Pass FairOnlineSink to SendBranches in Pixel

---

fairroot/fairmq/FairMQ.h
fairroot/fairmq/FairRunFairMQDevice.h
fairtools/MCStepLogger/MCStepInterceptor.cxx

```cpp
#define  A  3 + 7
const int b = 10*A;
```
b is 37, Not what you usualy want.
So put parentheses around things.
---
Checklist:

fix bugprone-macro-parentheses

---

base/source/FairFileSourceBase.cxx
base/source/FairFileSourceBase.h
base/source/FairSource.h

ActivateObjectAnyImpl is really specific to TTree, TFile and friends.  Move it into FairFileSourceBase and remove the template part.
---
Checklist:

Move ActivateObjectAnyImpl to FairFileSourceBase

---

base/source/FairFileSourceBase.cxx
base/steer/FairRootManager.h
examples/MQ/pixelDetector/src/FairOnlineSink.h

> No other guarantees are given: std::type_info objects referring to
> different types may have the same hash code
This is not good for comparisons.
Use direct comparisons instead.
See: https://en.cppreference.com/w/cpp/types/type_info/hash_code
See: https://en.cppreference.com/w/cpp/types/type_info/operator_cmp
---
Checklist:

fix: Do not use std::type_info::hash_code

---

fairroot/parbase/FairParAsciiFileIo.cxx
fairroot/parbase/FairParAsciiFileIo.h
fairroot/parbase/FairParRootFileIo.cxx
fairroot/parbase/FairParRootFileIo.h
fairroot/parbase/FairRuntimeDb.cxx

FairParAsciiFileIo and FairParRootFileIo call
FairRuntimeDb::activateParIo (from their open functions). activateParIo then does some things very specific to those both classes.
Instead perform those actions directly in the classes before calling activateParIo.
---
Checklist:

chore: Fefactor FairRuntimeDb::activateParIo

---

fairroot/base/event/FairPrintFairLinks.cxx
fairroot/base/event/FairPrintFairLinks.h

`fSelectedBranches` was not deallocated.
Also drop empty methods and general cleanup
---
Checklist:

fix leak in FairPrintFairLinks

---

examples/simulation/Tutorial4/src/reco/FairTutorialDet4StraightLineFitter.cxx
examples/simulation/Tutorial4/src/reco/FairTutorialDet4StraightLineFitter.h
fairroot/base/steer/FairLinkManager.cxx
fairroot/base/steer/FairLinkManager.h
fairroot/base/steer/FairRun.cxx
fairroot/base/steer/FairRun.h

* FairRun's constructor used to allocate a FairLinkManager, but the destructor did not deallocate it.
Switch it over to a valued member so that default behaviour allocates and deallocates it.
* Replace multiple heap allocated objects by either value members of the class or just local stack variables.
Introduce more `override`.
And drop empty ReInit and Finish methods that override the original methods that are also doing the same.
---
Checklist:

fix leaks in FairRun and FairTutorialDet4StraightLineFitter 

---

fairroot/base/sim/FairMCApplication.cxx
fairroot/base/sim/FairMCApplication.h
fairroot/base/steer/FairRunSim.cxx
fairroot/base/steer/FairRunSim.h

Turned multiple member variables from raw pointers to unique_ptrs so that the allocated objects get destructed at destruction of FMCA.
Allocation of FairTrajFilter also moved from FairRunSim to FMCA and that way avoids the ::Instance methods.
Also turned one member variable into a valued member to simplify some code.
---
Checklist:

fix multiple leaks in FairMCApplication

---

fairroot/base/sim/FairMCApplication.cxx

In the MT mode FairRunSim cannot close the sinks,
only FairMCApplication can.
---
Checklist:

Geant4MT: Fix closing sink in MT mode

---

CHANGELOG.md
fairroot/online/steer/FairRunOnline.cxx
fairroot/online/steer/FairRunOnline.h

The function is not being invoked, and was not used.
Addresses issue #1346.
---
Checklist:

Remove unused FairRunOnline::InitContainers() function

---

examples/advanced/propagator/src/FairEveRecoTracksExample.cxx
examples/common/eventdisplay/FairEveMCTracks.cxx
fairroot/eventdisplay/CMakeLists.txt
fairroot/eventdisplay/FairEventManager.cxx
fairroot/eventdisplay/FairEventManager.h
fairroot/eventdisplay/tracks/FairEveGeoTracks.cxx
fairroot/eventdisplay/xml/FairXMLEveConf.cxx
fairroot/eventdisplay/xml/FairXMLEveConf.h
fairroot/eventdisplay/xml/FairXMLPdgColor.cxx
fairroot/eventdisplay/xml/FairXMLPdgColor.h

This is part of a bigger patchset by @DanielWielanek.
Move the color configuration from FairEventManager to a new FairXMLPdgColor.
FairXMLPdgColor can also read config from an xml file, which is not yet used.
Co-Authored: Christian Tacke @ChristianTackeGSI
---
Checklist:

chore(eventdisplay): Refactor PDG To Color

---

fairroot/eventdisplay/tracks/FairEveTracks.cxx
fairroot/eventdisplay/tracks/FairEveTracks.h

This is part of a bigger patchset by @DanielWielanek.
Extracted from #1386.
@DanielWielanek : This should be pretty straight forward, right?
---
Checklist:

chore: Cleanup FairEveTracks

---

fairroot/base/steer/FairRootManager.cxx
fairroot/base/steer/FairRootManager.h

`FairRootManager::fOutFolder` is a private member variable. It is initialized to nullptr and never set to another value later on.
So drop this member variable and any code that depends on it being non-nullptr.
NOTE: This further simplifies `GetObject`.
---
Checklist:

chore(FRM): Drop private never set member variable

---

examples/simulation/Tutorial2/src/FairTutorialDet2DigiPar.cxx
examples/simulation/Tutorial2/src/FairTutorialDet2DigiPar.h
fairroot/base/source/FairFileSource.cxx
fairroot/base/source/FairFileSource.h
fairroot/base/source/FairFileSourceBase.cxx
fairroot/base/source/FairFileSourceBase.h
fairroot/base/source/FairMixedSource.cxx
fairroot/base/source/FairMixedSource.h

* fix: Do not leak fListFolder in Fair\*Source
* fix: Do not leak TArrayF in FairTutorialDet2DigiPar
Use value semantics!
---
Checklist:

fix leaks in Fair*Source and  FairTutorialDet2DigiPar

---

examples/simulation/Tutorial2/macros/CMakeLists.txt
examples/simulation/Tutorial2/macros/compare_seed_value.C
examples/simulation/Tutorial2/macros/create_digis.C
examples/simulation/Tutorial2/macros/create_digis_mixed.C
examples/simulation/Tutorial2/macros/read_digis.C
examples/simulation/Tutorial2/macros/run_background.C
examples/simulation/Tutorial2/macros/run_signal.C
examples/simulation/Tutorial2/macros/run_tutorial2.C
fairroot/base/steer/FairRunSim.cxx
templates/project_root_containers/MyProjGenerators/Pythia8Generator.h
templates/project_stl_containers/MyProjGenerators/Pythia8Generator.h

This PR brings first a test which checks if the set seed value is properly stored in FairBasParSet container during the simulation. Due to a breaking change in ROOT 6.24 the return value of the function TRandom3::GetSeed() doesn't return the seed value but a fixed value of 624. The newly added test should fail for FairSoft versions apr22 and nov22.
The PR will be updated with the proper fix for the problem in a second step.
---
Checklist:
* [x ] Followed the [Contributing Guidelines](https://github.com/FairRootGroup/FairRoot/blob/dev/CONTRIBUTING.md)

Fix root GetSeed

---

fairroot/base/steer/FairRunAna.cxx
fairroot/base/steer/FairRunAna.h
fairroot/base/steer/FairRunAnaProof.cxx
fairroot/online/steer/FairRunOnline.cxx
fairroot/online/steer/FairRunOnline.h

Introduce a CheckRunIdChanged in FairRunAna and FairRunOnline that handles RunId changes.
Fix FairRunAna::RunEventReco: It always used runid for the "new current runid".  Now it just uses CheckRunIdChanged as well.
Inspired by #1396
---
Checklist:

chore(FairRun*): Refactor RunId Changes

---

CHANGELOG.md
CMakeLists.txt
FairRoot_build_test.cmake
fairroot/base/CMakeLists.txt
fairroot/base/LinkDef.h
fairroot/base/steer/FairRunAna.h

Introduced `BUILD_EVENT_BUILDER` flag, that allows 
disabling build of `FairEventBuilder` and `FairEventBuilderManager` classes.
Set it to `OFF`.
Consequence of discussion in PR #1406.
---
Checklist:

Disable event builder

---

CHANGELOG.md
CONTRIBUTORS
fairroot/base/steer/FairRun.cxx
fairroot/base/steer/FairRun.h
fairroot/base/steer/FairRunAna.cxx
fairroot/base/steer/FairRunAnaProof.cxx
fairroot/online/steer/FairRunOnline.cxx

Encapsulate member pointer FairEventHeader from FairRun inside `std::unique_ptr`. This specifies the ownership of the event header and prevents it from being deleted multiple times.
Fixes #1242
Checklist:

Make member pointer fEvtHeader of FairRun into unique pointer

---

.clang-tidy
examples/common/mcstack/FairStack.h
fairroot/base/sim/FairGenericStack.h

This will not mark all C Style Casts, but those that could be problematic and should be looked at.
And start to fix them in `FairStack.h`
---
Checklist:

clang-tidy: Enable cppcoreguidelines-pro-type-cstyle-cast

---

examples/MQ/parameters/FairMQExParamsParOne.cxx
examples/MQ/parameters/FairMQExParamsParOne.h
examples/MQ/pixelDetector/src/PixelDigiPar.cxx
examples/MQ/pixelDetector/src/PixelDigiPar.h
examples/MQ/pixelDetector/src/PixelDigiWriteToBinFile.cxx
examples/MQ/pixelDetector/src/PixelDigiWriteToBinFile.h
examples/MQ/pixelDetector/src/PixelFitTracks.cxx
examples/MQ/pixelDetector/src/PixelFitTracks.h
examples/simulation/Tutorial2/src/FairTutorialDet2DigiPar.cxx
examples/simulation/Tutorial2/src/FairTutorialDet2DigiPar.h
fairroot/geobase/FairGeoNode.cxx
fairroot/parbase/FairParSet.cxx
fairroot/parbase/FairParSet.h

A ctor should set up all members in a proper way.  No need to call a clear method to reset member variables to the same value again. (Or an empty clear method.)
A dtor only needs to release resources. Member variables do not need to be reset to any values.
Member variables of base classes should be handled in the methods of base classes.
---
Checklist:

chore: Do not call clear in ctor/dtor

---

codemeta.json
examples/MQ/pixelDetector/macros/CMakeLists.txt
examples/MQ/pixelDetector/macros/run_dAsciiSource.C
examples/MQ/pixelDetector/macros/run_dBinSource.C
fairroot/base/steer/FairRun.h

Also update examples to current standards and compile check
them.
Also update `codemeta.json`.
---
Checklist:

chore: Use new unique_ptr based SetEventHeader

---

fairroot/base/steer/FairRun.h
fairroot/base/steer/FairRunAnaProof.cxx
fairroot/base/steer/FairRunAnaProof.h

It was made `virtual` only to override it in `FairRunAnaProof`. Removed this function from `FairRunAnaProof` and moved the contents of the function to `Init` on the main thread.
It addresses a comment from PR #1423 .
---
Checklist:

Remove `virtual` from `FairRun::SetSource()`

---

CHANGELOG.md
fairroot/base/steer/FairRunAna.cxx
fairroot/base/steer/FairRunAna.h
fairroot/eventdisplay/FairEventManager.cxx

Deprecated `FairRunAna::Run(Long64_t)` and replaced by newly introduced `FairRunAna::RunSingleEntry(Long64_t)`.
Changed description of `FairRunAna::Run(Int_t, Int_t)` to match the actual function behaviour.
Addresses issue #1397.
Mention any issue this PR resolves or is related to.
---
Checklist:

Replace `FairRunAna::Run(Long64_t)` by `RunSingleEntry(Long64_t)`

---

examples/MQ/serialization/sampler.cxx
examples/advanced/propagator/macros/runPull.C
examples/simulation/Tutorial4/macros/plots.C
fairroot/base/source/FairFileSourceBase.cxx
fairroot/base/steer/FairRootManager.cxx
fairroot/base/steer/FairRootManager.h
fairroot/parbase/FairParRootFileIo.cxx
fairroot/parbase/FairParRootFileIo.h

It turned out that `TFile::Get<>` returns an owning pointer.  So store this into a unique_ptr as soon as possible, so that the memory is handled correctly.
If one stores a TList in a root file, it is best to mark it as an owning TList (if it is), so that readers do not have to explicitly `->Delete()` the contents of the TList.
This fixes a first set of instances.
See: https://root-forum.cern.ch/t/solved-memory-leak-with-tfile-get/19683/8
---
Checklist:

fix: First set of TFile::Get Related leaks

---

examples/MQ/pixelDetector/src/devices/FairMQSimDevice.cxx
examples/MQ/pixelDetector/src/devices/FairMQSimDevice.h
examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.cxx
examples/MQ/pixelSimSplit/src/devices/FairMQTransportDevice.h
examples/advanced/Tutorial3/macro/run_sim_sep.C
examples/advanced/propagator/macros/runMC.C
examples/advanced/propagator/macros/runMM.C
examples/simulation/Tutorial1/macros/run_tutorial1_fastsim.C
examples/simulation/Tutorial1/macros/run_tutorial1_mesh.C
examples/simulation/Tutorial1/macros/run_tutorial1_pythia6.C
examples/simulation/Tutorial1/macros/run_tutorial1_pythia8.C
examples/simulation/Tutorial1/macros/run_tutorial1_urqmd.C
examples/simulation/Tutorial4/macros/run_tutorial4.C
examples/simulation/Tutorial4/macros/run_tutorial4_createGeometryFile.C
examples/simulation/Tutorial4/macros/run_tutorial4_createMatrices.C
examples/simulation/rutherford/macros/run_rad.C
examples/simulation/rutherford/macros/run_rutherford.C

Use value semantics to not leak the FairRunSim in some examples.
And use unique_ptr in some others.
---
Checklist:

fix(examples): Memory Leak of FairRunSim

---

examples/simulation/Tutorial2/macros/CMakeLists.txt
examples/simulation/Tutorial2/macros/create_digis.C
examples/simulation/Tutorial2/macros/create_digis_mixed.C
examples/simulation/Tutorial2/macros/read_digis.C
fairroot/base/event/FairTimeStamp.h

Many of the newer macros are actually valid C++ files. So let's compile them to get all the warnings and checks from the main compile checks.
Also fix some warnings in `FairTimeStamp.h`
---
Checklist:

Try Compiling Macros to Check them

---

CMakeLists.txt
FairRoot_build_test.cmake
cmake/private/FairRootCodemeta.cmake

* Let CI fail on CMake developer warnings
* Let CI throw a developer warning, if the versions in CMake and codemeta.json do not match.
---
Checklist:

ci: Check codemeta version field being correct

---

CMakeLists.txt
fairroot/mcconfigurator/CMakeLists.txt

With the latest version of yaml-cpp (0.8.0) the name of the exported target has changed from yaml-cpp to yaml-cpp::yaml-cpp which breaks the compilation.
To work around the problem an alias yaml-cpp::yaml-cpp is created in case the exported target name is yaml-cpp.
---
Checklist:
* [ x] Followed the [Contributing Guidelines](https://github.com/FairRootGroup/FairRoot/blob/dev/CONTRIBUTING.md)

Fix exported target name

---

CMakeLists.txt
third_party/CMakeLists.txt

1. Move catch2 setup into third_party/
Declutter the main CMakeLists.txt a bit.
2. Use FetchContent_Declare(SYSTEM)
CMake 3.25 allows setting a "SYSTEM" option on FetchContent_Declare. Declare Catch2 using this option (if supported). This way consumers of Catch2 targets will consider catch2 includes as system includes and not show warnings for them.
---
Checklist:

build: Move catch2 setup into third_party/ and use SYSTEM

---

examples/simulation/Tutorial2/macros/read_digis.C

Fix license header which was corrupted by one of the previous commits.
The 4 previous commits brought in the proper handling of TRandom::GetSeed() which was implemented with #1412.
Unfortunately these commits were pushed accidentely directly to the main repository instead of my fork.
Please review also the commits
f111598f7cb9cb29d9812ea0d45d63366c58feec
b4c42d35d0d3aa647a263c99b6b5fa599cb3d83a
b40931eb2c26ec311408328aee662a16d2a846a5
36584050e395169ff65af7ccba0a4847104142a9 
such that they can be either be accepted or removed as early as possible by another commit which reverts the changes.
---
Checklist:

Fix license header

---

fairroot/base/sim/FairModule.cxx
fairroot/base/sim/FairModule.h

Static thread_local member variables initialization in the source file does not work within pyROOT.
Moved all member initialization to the header file.
---
Checklist:

FairModule: move member variable initialization to the header file

---

examples/advanced/Tutorial3/macro/run_sim.C
fairroot/base/sim/FairMCApplication.cxx
fairroot/base/sim/FairMCApplication.h
fairroot/base/sim/FairPrimaryGenerator.cxx
fairroot/base/sim/FairPrimaryGenerator.h
fairroot/base/sink/FairSink.cxx
fairroot/base/sink/FairSink.h
fairroot/base/steer/FairRun.cxx
fairroot/base/steer/FairRun.h
fairroot/base/steer/FairRunSim.cxx
fairroot/base/steer/FairRunSim.h
fairroot/parbase/FairContFact.cxx
fairroot/parbase/FairContFact.h
fairroot/parbase/FairRtdbRun.cxx
fairroot/parbase/FairRtdbRun.h
fairroot/parbase/FairRuntimeDb.cxx
fairroot/parbase/FairRuntimeDb.h

Allow to list the object hierarchy under a FairRunSim.
Scroll to the end of this [CDash log](https://cdash.gsi.de/testDetails.php?test=15939953&build=406391) to see a typical output.
---
Checklist:

feat: Start with FairRunSim::ls()

---

examples/advanced/Tutorial3/digitization/FairTestDetectorDigiTask.h
examples/common/eventdisplay/FairEveMCTracks.h
examples/common/eventdisplay/FairEveMCTracksEditor.h
examples/common/eventdisplay/FairMCTracksDraw.h
examples/simulation/rutherford/src/FairRutherfordGeoPar.h
examples/simulation/rutherford/src/FairRutherfordPoint.h
fairroot/eventdisplay/FairEventManagerEditor.h
fairroot/eventdisplay/gui/FairEveCut.h
fairroot/eventdisplay/gui/FairEveTransparencyControl.h
fairroot/eventdisplay/tracks/FairEveGeoTracks.h
fairroot/eventdisplay/tracks/FairEveGeoTracksEditor.h
fairroot/eventdisplay/tracks/FairEveRecoTrack.h
fairroot/eventdisplay/tracks/FairEveRecoTrackList.h
fairroot/eventdisplay/tracks/FairEveTrack.h
fairroot/eventdisplay/tracks/FairGeoTracksDraw.h
fairroot/trackbase/FairGeaneUtil.h
fairroot/trackbase/FairPropagator.h
fairroot/trackbase/FairRKPropagator.h
fairroot/trackbase/FairTrackPar.h
fairroot/trackbase/FairTrackParH.h
fairroot/trackbase/FairTrackParP.h
templates/project_root_containers/CTestCustom.cmake
templates/project_stl_containers/CTestCustom.cmake

No code in FairRoot needs a TMemberInspector directly. If anything from ROOT needs it, then that include should declare it.
---
Checklist:

chore: Drop TMemberInspector declaration

---

fairroot/tools/FairMemory.h
fairroot/tools/tests/maybe_owning.cxx

The default behaviour is not an accidental side effect. So document and test it.
---
Checklist:

document/test default behaviour of maybe_owning_ptr

---

examples/MQ/pixelAlternative/src/PixelAltFindHits.cxx
examples/MQ/pixelDetector/src/FairOnlineSink.cxx
examples/MQ/pixelDetector/src/FairOnlineSink.h
examples/MQ/pixelDetector/src/PixelDigiBinSource.cxx
examples/MQ/pixelDetector/src/PixelDigiSource.cxx
examples/MQ/pixelDetector/src/PixelDigitize.cxx
examples/MQ/pixelDetector/src/PixelFindHits.cxx
examples/MQ/pixelDetector/src/PixelFindTracks.cxx
examples/advanced/propagator/src/FairTutPropTr.cxx
fairroot/base/event/FairEventBuilderManager.cxx
fairroot/base/event/FairMultiLinkedData.cxx
fairroot/base/event/FairTrackParam.cxx
fairroot/base/sim/FairGenerator.h
fairroot/base/sim/FairRunIdGenerator.cxx
fairroot/base/source/FairFileSource.cxx
fairroot/base/source/FairMixedSource.cxx
fairroot/base/source/FairSource.h
fairroot/base/steer/FairRunAnaProof.cxx
fairroot/geobase/FairGeoBasicShape.h
fairroot/geobase/FairGeoSet.cxx

`return;` at the end of a function is quite pointless.
Also fix some C-Style Casts
---
Checklist:

chore: Drop useless `return;`

---

examples/simulation/Tutorial4/macros/run_tutorial4_createParameterFile.C
fairroot/base/sim/FairModule.cxx
fairroot/base/steer/FairRunAna.cxx
fairroot/base/steer/FairRunAna.h
fairroot/base/steer/FairRunAnaProof.cxx

`TKey::ReadObj` returns an owning pointer.
Using dynamic_cast and ignoring the "not castable" case can leak memory.
Also one `std::unique_ptr`
See: https://root-forum.cern.ch/t/possible-leak-with-dynamic-cast-and-tkey-readobj/56799
See: https://github.com/root-project/root/pull/13931
---
Checklist:

fix: Use TKey::ReadObject<T> instead of ReadObj

---

cmake/modules/FindROOT.cmake

Apparently ROOT changed the version string.

Fix FindROOT.cmake to work with v6.30.00

---

fairroot/online/source/FairLmdSource.cxx
fairroot/online/source/FairLmdSource.h

`Close` is a virtual method. It's getting called internally in a scenario where only FairLmdSource specific resources should be closed.
Also the desctructor did not close.
This was triggered by a comment here: https://github.com/FairRootGroup/FairRoot/pull/1464#pullrequestreview-1738378541
---
Checklist:

chore: Improve closing on FairLmdSource

---

.github/workflows/check_metadata.yaml

If AUTHORS or CONTRIBUTORS are changed,
check that the changes are merged into codemeta.json, and .zenodo.json.
See: https://github.com/ChristianTackeGSI/FairRoot/actions/runs/7267260698/job/19800680021
And a failing one: https://github.com/ChristianTackeGSI/FairRoot/actions/runs/7267235927/job/19800601329
---
Checklist:

ci: Check codemeta/zenodo with AUTHORS/CONTRIBUTORS

---

examples/simulation/Tutorial1/src/FairSimConfig.cxx
examples/simulation/Tutorial1/src/FairSimConfig.h

When using boost/program_options in a header file the generated dictinonary can't be loaded at runtime and the macro crashes. Guard the usage of boost/program_options in the header file such that code is only used during compilation but not when using cling.
The problem was already reported to the ROOT team and will not be fixed since the underlying problem is obviously in the libc++ shipped by Apple. (see https://github.com/root-project/root/issues/12762)
---
Checklist:
* [ x] Followed the [Contributing Guidelines](https://github.com/FairRootGroup/FairRoot/blob/dev/CONTRIBUTING.md)

Fix a runtime error with newer XCode versions

---

examples/simulation/Tutorial1/src/FairSimConfig.cxx
examples/simulation/Tutorial1/src/FairSimConfig.h

When using boost/program_options in a header file the generated dictinonary can't be loaded at runtime and the macro crashes.
Don't use boost in the header file such that there is no problem when using cling.
The problem was already reported to the ROOT team and will not be fixed since the underlying problem is obviously in the libc++ shipped by Apple. (see https://github.com/root-project/root/issues/12762)
(cherry picked from commit 65ea0a8a4acbc22c39598f34b7ce1ea2715dbbf4)
---
Checklist:

[backport 18.8] Fix a runtime error with newer XCode versions

---

base/steer/FairTSBufferFunctional.h

https://en.cppreference.com/w/cpp/utility/functional/binary_function technically already removed in C++17
fix #1257
(cherry picked from commit b243e218017682256ef1efb4fa1fb4474e662a60)

[18.6] fix(base): -Wdeprecated-declarations

---

cmake/modules/CheckCompiler.cmake
cmake/modules/ROOTMacros.cmake

exec_program was deprecated in CMake 3.0.
It got a FATAL_ERROR with CMake 3.28.
See CMP0153.
So replace with the newer execute_process.
See: https://cmake.org/cmake/help/latest/policy/CMP0153.html
(extracted from #1486)

build: Replace exec_program by execute_process

---

fairroot/CMakeLists.txt

So only build it, if FairRoot::FastSim is available.
Before: https://cdash.gsi.de/viewConfigure.php?buildid=439647
After: https://cdash.gsi.de/viewConfigure.php?buildid=439706
---
Checklist:

build: MCConfigurator needs FairRoot::FastSim

---

Jenkinsfile

centos 7 and ubuntu 20.x are failing always.
Until we fix the CI images, let's disable this.
---
Checklist:

Reduce fail-always-level: ci: Disable always failing checks

---

examples/MQ/pixelDetector/src/PixelDigiSource.cxx
examples/MQ/serialization/data_generator/dataGenerator.cxx
fairroot/base/event/FairMultiLinkedData.cxx
fairroot/base/sim/FairVolumeList.cxx
fairroot/base/source/FairFileSource.cxx
fairroot/base/steer/FairRingSorterTask.cxx
fairroot/base/steer/FairRunAna.cxx
fairroot/base/steer/FairTSBufferFunctional.cxx
fairroot/geobase/FairGeoMedium.cxx
fairroot/geobase/FairGeoNode.cxx
fairroot/geobase/FairGeoNode.h
fairroot/geobase/FairGeoVolume.cxx
fairroot/online/steer/FairRunOnline.cxx
fairroot/parbase/FairDetParRootFileIo.cxx
fairroot/parbase/FairParRootFileIo.cxx
fairroot/parbase/FairParSet.h
fairroot/trackbase/FairTrackParH.cxx

- chore: Mark some free standing functions static
If free standing functions are only ever used in one compile unit, they should be marked `static` to not pollute the namespace during linking.
- chore: Remove useless casts
Casting to the exact same type is quite useless.
---
Checklist:

chore: Mark some functions static, Remove some useless casts

---

fairroot/base/sim/FairDetector.cxx
fairroot/base/sim/FairMCApplication.cxx
fairroot/base/sim/FairModule.cxx
fairroot/base/sim/FairModule.h
templates/NewDetector_root_containers/NewDetector.cxx
templates/NewDetector_stl_containers/NewDetector.cxx
templates/project_root_containers/NewDetector/NewDetector.cxx
templates/project_stl_containers/NewDetector/NewDetector.cxx

`FairModule::svList` can very well be implemented using `std::vector` without all the casting.
And rename to `fAllSensitiveVolumes`.
Follow up from #1497
---
Checklist:

Use std containers for FairModule::svList

---

fairroot/base/steer/FairRunSim.cxx
fairroot/base/steer/FairRunSim.h
fairroot/geobase/FairGeoLoader.cxx
fairroot/geobase/FairGeoLoader.h
fairroot/geobase/FairGeoRootBuilder.cxx
fairroot/geobase/FairGeoRootBuilder.h

Also some small other stylistic changes
---
Checklist:

fix: Multiple Leaks around FairGeoLoader

---

examples/MQ/pixelSimSplit/run/scripts/test-splitMQ.sh.in

ex_MQ_pixel_split seems to fail sometimes.
Let's output the last lines of the logs of the failing processes.
See for example: https://cdash.gsi.de/testDetails.php?test=19708497&build=448242
---
Checklist:

feat: Improve test logging

---

fairroot/fastsim/FairFastSimModel.cxx

Geant4 (geant4-11.2) deprecates functions G4FastStep::Set...(),
and advices usage of corresponding G4FastStep::Propose...().
Replaced them all in FairFastSimModel.cxx.
---
Checklist:

chore(fastsim) Replace deprecated Geant4 APIs

---

Jenkinsfile
fairroot/base/steer/FairRunSim.cxx
tests/ci/slurm-submit.sh

Not leaking fGeoLoader on FairRunSim seems to cause some memory issues (probbaly a double free/delete). Until we find it, let's leak the Geoloader, as before.
See: https://github.com/FairRootGroup/FairRoot/issues/1514
See: ede7137bd698df6ba9a6b4e6807e8225e68e121b
---
Checklist:

workaround: Avoid geoloader memory issues

---

CHANGELOG.md
fairroot/base/sim/FairModule.h

(prompted by <https://github.com/FairRootGroup/FairRoot/pull/1500#issuecomment-2152317249>)
The FairModule::svList API was dropped in 19.0.
It was thought of as an internal API anyway. But let's at least document
- that it's gone
- that the new fAllSensitiveVolumes IS an internal API
See: 54ad232ffe416e9c650b3d0d4aadce7b48e48746
(Should be backported to 19.0 after it's merged.)
---
Checklist:

docs: breaking change of FairModule::svList

---

cmake/CMakeLists.txt
cmake/modules/FindFairRoot.cmake
cmake/private/FairRootConfig.cmake.in
cmake/private/FairRootPackage.cmake

Shall be backported to `v19.0` and `v18.8` as well.

Export CMAKEMOD dir

---

CONTRIBUTING.md

Proposal of new guidelines
* G.4 Conventional Commits
* G.5 Signed Commits and Tags
Rendered: https://github.com/dennisklein/FairRoot/blob/new-guidelines/CONTRIBUTING.md#g4-conventional-commits

New guidelines G.4 and G.5

---

examples/common/passive/FairCave.cxx
examples/common/passive/FairPipe.cxx
fairroot/base/sim/FairMCApplication.cxx
fairroot/base/sim/FairModule.cxx
fairroot/base/sim/FairModule.h
fairroot/base/steer/FairRunSim.cxx
fairroot/base/steer/FairRunSim.h
fairroot/fastsim/FairFastSimDetector.cxx
templates/project_root_containers/passive/MyCave.cxx
templates/project_stl_containers/passive/MyCave.cxx

Instead add a few GetGeometryLoader() getters and use them. Also let FairModule know to which FairRunSim it belongs.
---
Checklist:

refactor: Avoid FairGeoLoader::Instance()

---

fairroot/base/steer/FairRootManager.h

Fix the UB found in the issue #1556 related to `FairRootManager::GetObject`.
The branch address of the TTree must be fixed during the data reading. In other words, if an object of type `T` needs to be read from a tree, the value `T**` must be fixed and cannot be changed during the whole reading process.  However, in the GetObject function, the variable `newentry` is a reference to the `T*` pointer stored in the `std::vector<T*>`. If the size of the vector grows beyond its capacity, the whole vector will be moved to another memory location, which means the `T**` value will be changed.
This makes sense as in my real practice from R3BRoot, I didn't get all zeros but rather direct segmentation fault.
Let `newentry` refer to the `T*` in the object of `std::map<TString, TObject*>` fixes the …

Fix FairRootManager::GetObject

---

examples/MQ/pixelDetector/src/Pixel.cxx
examples/advanced/Tutorial3/simulation/FairTestDetector.cxx
examples/advanced/propagator/src/FairTutPropDet.cxx
examples/simulation/Tutorial1/src/FairFastSimExample.cxx
examples/simulation/Tutorial1/src/FairFastSimExample2.cxx
examples/simulation/Tutorial1/src/FairTutorialDet1.cxx
examples/simulation/Tutorial4/src/mc/FairTutorialDet4.cxx
examples/simulation/rutherford/src/FairRutherford.cxx
fairroot/base/sim/FairDetector.h
fairroot/base/sim/FairMCApplication.cxx
fairroot/base/steer/FairRootManager.h
templates/NewDetector_root_containers/NewDetector.cxx
templates/NewDetector_stl_containers/NewDetector.cxx
templates/project_root_containers/MyProjGenerators/Pythia8Generator.cxx
templates/project_root_containers/NewDetector/NewDetector.cxx
templates/project_stl_containers/MyProjGenerators/Pythia8Generator.cxx
templates/project_stl_containers/NewDetector/NewDetector.cxx

Especially classes deriving from FairDetector and
implementing the Register member function need access to FairrootManager. Give them a proper getter.
---
Checklist:

feat(base): Introduce FairDetector::GetRootManager

---

examples/simulation/Tutorial1/macros/run_tutorial1.C

As our tests run in parallel, the output filenames must be unique across different run types. So add more properties to the filename (MT, postinit).
---
Checklist:

fix(examples): More unique output filenames

---

fairroot/parbase/FairDetParRootFileIo.cxx
fairroot/parbase/FairParSet.cxx
fairroot/parbase/FairParSet.h
fairroot/parbase/FairRuntimeDb.cxx

And re-arrange some if statements
See-Also: #1541
Included one commit from #1552
---
Checklist:

refactor(parbase): Improve logging in FairParSet

---

CHANGELOG.md
fairroot/base/LinkDef.h
fairroot/base/steer/FairRootManager.h
fairroot/base/steer/FairRun.cxx
fairroot/base/steer/FairRun.h

@ChristianTackeGSI Here are some bits of the FairRootManager work I am currently preparing as separate PR as requested.

Disable streamer for FairRootManager and fix unconditional dereference in `SetSink()`

---

fairroot/eventdisplay/xml/FairXMLPdgColor.cxx
fairroot/eventdisplay/xml/FairXMLPdgColor.h

Currently only used in the ctor.
Exposed for possible other users.
Also added a bit of const.
---
Checklist:

feat(eventdisplay): Add FairXMLPdgColor::SetColorsFromXML

---

.zenodo.json
CONTRIBUTORS
codemeta.json
fairroot/generators/FairBoxGenerator.cxx
fairroot/generators/FairBoxGenerator.h

The current FairBoxGenerator allows only for generating particles over a plane as the depth of the box, `dZ`, is hard-coded to be 0.
In this pull request, the `SetBoxXYZ` method is overloaded to accept also two values of z (`z1` and `z2`) from which `dZ` is computed in the same way as `dX` and `dY`.
---
Checklist:

Allow for 3D box in FairBoxGenerator

---

.clang-format
examples/MQ/pixelDetector/src/Pixel.cxx
examples/MQ/pixelDetector/src/PixelDigitize.cxx
examples/advanced/Tutorial3/simulation/FairTestDetector.cxx
examples/advanced/propagator/src/FairTutPropDet.cxx
fairroot/base/event/FairMultiLinkedData.cxx
fairroot/base/steer/FairRadGridManager.cxx
fairroot/base/steer/FairWriteoutBuffer.cxx
fairroot/generators/FairBoxGenerator.cxx
fairroot/online/source/FairMbsSource.cxx
fairroot/online/source/FairRemoteSource.cxx
templates/project_root_containers/NewDetector/NewDetector.cxx
templates/project_stl_containers/NewDetector/NewDetector.cxx
tests/geobase/checks_FairGeoBasicShape.h

Multi-line control statements with the opening brace on the last line can be a little confusing to read:
```cpp
if (auto foo = something;
foo.extra_data.check_for(17)) {
foo.extra_data.check_and_act(19);
}
```
It is not easy to see the end of the condition and the start of the "then" block.
This gets much easier when putting the opening brace on its own line:
```cpp
if (auto foo = something;
foo.extra_data.check_for(17))
{
foo.extra_data.check_and_act(19);
}
```
To show the difference, a few files have been reformatted with this.
---
Checklist:

clang-format: Put braces on own line in special cases

---

fairroot/base/sim/FairGenericStack.cxx
fairroot/base/sim/FairGenericStack.h

FairGenericStack is the base class of all "Stacks". Instead of redirecting via `TVirtualMC::GetMC()->GetStack()`, just use `this`.
discovered by @dennisklein here: https://github.com/FairRootGroup/FairRoot/pull/1584#discussion_r1718396204
---
Checklist:

refactor(Base): Call GetCurrentTrackNumber directly from FairGenericStack

---

fairroot/base/sink/FairRootFileSink.h

This is just a thin wrapper that calls TFile::Open.
It's not used in FairRoot.
And everybody else should use TFile::Open.
---
Checklist:

deprecate(Base): FairRootFileSink::OpenRootFile

---

examples/simulation/rutherford/macros/CMakeLists.txt
fairroot/base/sim/FairMCApplication.cxx
fairroot/base/sim/FairMCApplication.h
fairroot/base/sink/FairRootFileSink.cxx
fairroot/base/steer/FairRootManager.cxx
fairroot/base/steer/FairRootManager.h
fairroot/base/steer/FairRunSim.h

Introduced new function `FairMCApplication::InitFinalizer()` which initializes event generator, tasks, and triggers `FairRootManager::WriteFolder()` function.
This new function is called from the latter of
`InitGeometry()` and `AddIons()`.
Previously the funcionality of `InitFinalizer` was split between `InitGeometry()` and `AddIons()`, which caused problems because
TGeant3 calls `AddIons()` first, `InitGeometry()` second, TGeant4 calls `InitGeometry()` first, `AddIons()` second.
Current implementation assures that initialization of event generators and tasks come before `WriteFolder`.
Fixes issues #1183 and #1567.
---
Checklist:

feat(sim): Allow branch registration in `FairGenerator`

---

fairroot/base/sink/FairRootFileSink.cxx
fairroot/base/source/FairFileSource.cxx
fairroot/base/source/FairMixedSource.cxx
fairroot/base/steer/FairRootManager.cxx
fairroot/base/steer/FairRootManager.h

After introducing RemoveOutputFolder, let's also introduce `Create…` to improve the lifecycle management.
Using `FairRootManager::Instance` is not nice, but fixing that is not in scope for this PR.
---
Checklist:

refactor(Base): Introduce FairRootManager::CreateOutputFolder

---

examples/common/mcstack/FairStack.cxx
examples/common/mcstack/FairStack.h
fairroot/base/sim/FairGenericStack.h
templates/project_root_containers/MyProjData/MyProjStack.cxx
templates/project_root_containers/MyProjData/MyProjStack.h
templates/project_stl_containers/MyProjData/MyProjStack.cxx
templates/project_stl_containers/MyProjData/MyProjStack.h

Instead of letting each derived "Stack" implement everything, provide some basic functionality in FairGenericStack.
Derived classes can just use it, extend it, or completely replace, as they see fit.
---
Checklist:

feat(FairGenericStack): Provide better default functions

---

examples/MQ/pixelDetector/src/Pixel.h
examples/advanced/Tutorial3/simulation/FairTestDetector.h
examples/advanced/propagator/src/FairTutPropDet.h
examples/simulation/Tutorial1/src/FairTutorialDet1.h
examples/simulation/Tutorial2/src/FairTutorialDet2.h
examples/simulation/Tutorial4/src/mc/FairTutorialDet4.h
examples/simulation/rutherford/src/FairRutherford.h
fairroot/base/sim/FairModule.h
templates/NewDetector_root_containers/NewDetector.h
templates/NewDetector_stl_containers/NewDetector.h
templates/project_root_containers/NewDetector/NewDetector.h
templates/project_stl_containers/NewDetector/NewDetector.h

Most classes that derive from FairDetector override a bunch of member functions with an empty function. But the original one is already empty. So there is no need to override them.
Just remove all of this.
If someone wants to customize / use those hooks, they can override the hook that they need.
---
Checklist:

refactor: Drop empty overriden methods in FairDetector classes

---

.github/workflows/stale.yml

After a year of inactivity, mark issues and PRs as stale to help with triaging.
Runs only weekly and acts on very few items to reduce flooding developers.
Docs: https://github.com/actions/stale
Merge to master, because otherwise it wont work.
---
Checklist:

workflow: Mark issues/PRs as stale
